### ISSUE TITLE
[ServiceWorkers] Add a test for service worker debugging

### ISSUE THREAD

**Issue by jasonLaster** [firefox-devtools/debugger#3344]
We support debugging service workers so we should have a test that demonstrates that we can attach to a worker and debug it.

https://dxr.mozilla.org/mozilla-central/source/devtools/client/debugger/test/mochitest/browser_dbg_WorkerActor.attachThread.js#1

**Comment by jasonLaster** [comment]
@juliandescottes do you think we need this or having a worker test is sufficient?

**Comment by juliandescottes** [comment]
From a debugger point of view, I suppose the codepaths are similar. From a connection/toolbox point of view it makes sense to have a dedicated test though. Feel free to close this one.

**Comment by janodvarko** [comment]
@bhackett1024 what is our current test strategy for SW?
I am closing this report as part of our GH-issue-list clean up effort but perhaps we should file bugs to cover this work in bugzilla?

Honza
