### ISSUE TITLE
Can't debug modal dialogs with Browser Toolbox

### ISSUE THREAD

**Issue by Standard8** [firefox-devtools/debugger#3539]
I'm trying to debug the "Bookmark All Tabs" modal dialog, however I can't get it to work.

STR:

1) In bookmarkProperties.js, find onDialogLoad, add a debugger statement at the start of it.
2) Build FF, and run it
3) Open up the Browser Toolbox
4) Open a couple of tabs, then right click on one of them and select "Bookmark All Tabs"

Actual Results

-> The dialog opens, debugger doesn't kick in.

Expected Results

-> The debugger kicks in.

Additionally, if I manually set breakpoints whilst the dialog is open, restart the browser, then try again it still doesn't break.

**Comment by jasonLaster** [comment]
@Standard8 I'm sorry for letting this issue sit for sometime. Does this test still reproduce? I could not find `bookmarkProperties.js`...

**Comment by Standard8** [comment]
No idea what fixed this, but the original STR work now :-)
