### ISSUE TITLE
[Breakpoints] we should resume if we pause at an old breakpoint

### ISSUE THREAD

**Issue by jasonLaster** [firefox-devtools/debugger#4104]
With AST BPs and original BPs, it's possible that we've paused at a breakpoint before we've had a chance to move it to a new location. See GIF. In that case, we should check to see if the breakpoint is missing... or in an old location...

![](https://files.slack.com/files-pri/T3V7H1198-F762ZAB9A/debugger_pinned_bp.gif)

#### Missing

```diff
diff --git a/src/actions/pause.js b/src/actions/pause.js
index 4fa84b5..4462642 100644
--- a/src/actions/pause.js
+++ b/src/actions/pause.js
@@ -104,6 +104,11 @@ export function paused(pauseInfo: Pause) {
       dispatch(evaluateExpressions(frame.id));
     }

+    const bp = getBreakpoint(getState(), frame.location);
+    if (why.type == "breakpoint" && !bp) {
+      dispatch(resume());
+    }
+
     dispatch(
       selectSource(frame.location.sourceId, { line: frame.location.line })
```

#### has moved 

```diff
+    const { location, astLocation } = pendingBreakpoint;
+    const previousLocation = { ...location, sourceId };
+
+    const scopedLocation = await makeScopedLocation(
+      astLocation,
+      previousLocation,
+      source
+    );
+
+    const scopedGeneratedLocation = await getGeneratedLocation(
+      getState(),
+      source,
+      scopedLocation,
+      sourceMaps
+    );
+
+    const hasMoved = locationMoved(generatedLocation, scopedGeneratedLocation);
+
+    const bp = getBreakpoint(getState(), frame.location);
+    if ((why.type == "breakpoint" && !bp) || hasMoved) {
+      dispatch(resume());
+    }
+
```

**Comment by jacobjzhang** [comment]
@jasonLaster where's the GIF mentioned in the post?

**Comment by jasonLaster** [comment]
![debugger_pinned_bp.gif](https://shipusercontent.com/ae1ce8e578afe95390ad9a4f1ff75947/debugger_pinned_bp.gif)

**Comment by jasonLaster** [comment]
I started this and got pretty close:

```diff
diff --git a/src/actions/pause/paused.js b/src/actions/pause/paused.js
index 40b7589..9763516 100644
--- a/src/actions/pause/paused.js
+++ b/src/actions/pause/paused.js
@@ -7,7 +7,8 @@
 import {
   getHiddenBreakpointLocation,
   isEvaluatingExpression,
-  getSelectedFrame
+  getSelectedFrame,
+  getBreakpointForLine
 } from "../../selectors";
 import { mapFrames } from ".";
 import { removeBreakpoint } from "../breakpoints";
@@ -16,6 +17,7 @@ import { selectLocation } from "../sources";
 import { togglePaneCollapse } from "../ui";

 import { fetchScopes } from "./fetchScopes";
+import { resume } from "./commands";

 import type { Pause } from "../../types";
 import type { ThunkArgs } from "../types";
@@ -48,6 +50,18 @@ export function paused(pauseInfo: Pause) {
       dispatch(evaluateExpressions());
     }

+    const frame = frames[0];
+    if (
+      why.type == "breakpoint" &&
+      !getBreakpointForLine(
+        getState(),
+        frame.location.sourceId,
+        frame.location.line
+      )
+    ) {
+      return resume();
+    }
+
```

**Comment by jasonLaster** [comment]
Hey @zaggy still interested?

**Comment by jasonLaster** [comment]
Hey, @zaggy i'm un-assigning you as it's been a month. Feel free to-reclaim it.

**Comment by jasonLaster** [comment]
This is a really cool issue that I would be happy to mentor someone on

**Comment by Sekhmet** [comment]
/unassign

I unassign myself as I'm short on time currently, and don't want to block this issue for others.

**Comment by Sekhmet** [comment]
/unclaim

I unclaim myself as I'm short on time currently, and don't want to block this issue for others.

**Comment by jasonLaster** [comment]
sure. ping me on slack if you want to jump on a call.

the best thing to do, i think is to find a way to fake it in the paused action and then play with it

**Comment by loganfsmyth** [comment]
@rohanprasad Is this something you're still looking into?

**Comment by rohanprasad** [comment]
@loganfsmyth sorry, I am unable to find time to look into this issue. Unclaiming for now.

**Comment by jacobjzhang** [comment]
Is this still a relevant issue? I can't seem to reproduce it. In the GIF from a year ago, was that a handspun page or one of the existing examples?

**Comment by jacobjzhang** [comment]
Disregard, was able to replicate it. I did some digging, haven't done much except copy @jasonLaster's example from a year ago and [tweak it in this PR](https://github.com/devtools-html/debugger.html/pull/7150/files)

It seems to just work? I'm not sure of all the scenarios we're trying to cover, but I'm sure there's more. Perhaps one of the mozilla folks can enlighten?

**Comment by WenInCode** [comment]
It seems like this may have been resolved by something else? I am unable to reproduce it any more. Altering the source and refreshing, the breakpoint moves to the proper location and pauses. I'm going to close this and we can re-open if someone manages to reproduce it.
