### ISSUE TITLE
[SourceTree] 30000 files in the tree

### ISSUE THREAD

**Issue by yurydelendik** [firefox-devtools/debugger#4168]
STR:
1. Open and debug http://firefox-dev.tools/debugger-examples/examples/f30k/index.html
2. Browse source tree

Actual result:

Browser hangs

Expected result:

Able to open and browse source tree with 30000 files.

**Comment by jasonLaster** [comment]
```diff
diff --git a/src/utils/sources-tree/createTree.js b/src/utils/sources-tree/createTree.js
index de18287..fd007f6 100644
--- a/src/utils/sources-tree/createTree.js
+++ b/src/utils/sources-tree/createTree.js
@@ -7,10 +7,25 @@ import { addToTree } from "./addToTree";

 import type { SourcesMap } from "../../reducers/types";

+function addSources(sources, uncollapsedTree) {
+  for (const source of sources) {
+    addToTree(uncollapsedTree, source);
+  }
+}
+
 export function createTree(sources: SourcesMap, debuggeeUrl: string) {
   const uncollapsedTree = createNode("root", "", []);
-  for (const source of sources.valueSeq()) {
-    addToTree(uncollapsedTree, source, debuggeeUrl);
+
+  const sourceList = sources.valueSeq();
+
+  if (huge) {
+    // 30K
+    // batches of 1000
+    sourceListPartitions.forEach(
+      requestIdleCallback(() => addSources(sources, uncollapsedTree))
+    );
+  } else {
+    addSources(sources, uncollapsedTree);
   }

   const sourceTree = sortEntireTree(collapseTree(uncollapsedTree), debuggeeUrl);
(END)

```

**Comment by yurydelendik** [comment]
I measured performance of source tree with 3,000 files (10x less of the target), and following pain points are:

* addTree operation ~470ms
* tree sort ~160ms
* tree batch component update ~5900ms

I was able to reduce time to 30%, by:

1. Removing SVG {icon} (improvement)-> tree batch component update ~2100ms
2. Not parsing debuggee domain all the time -> tree sort ~5ms
3. Having an name index for nodes -> addTree operation ~205ms

See blueprint at https://gist.github.com/yurydelendik/0b10038753f4facf750f727a9db49844

**Comment by dholbert** [comment]
>I was able to reduce time to 30%, by ... Removing SVG {icon}

If the debugger is putting zillions of copies of the same SVG content into the DOM for this use-case,  it's possible you'd get a benefit from replacing this duplicated SVG content with an `<img> (or` an element with "background-image") which points at some single local SVG helper file (or a resource:// URI or somesuch). That way, we'd have a single copy of the SVG document/content, and a single rasterization cached in imagelib's surface cache, and the duplicated thing would be `<img>` which is probably lighter-weight.

**Comment by dholbert** [comment]
Yeah, looks like the "document" icon here is: the following (whitespace tweaked for readability):
````svg
<!-- This Source Code Form is subject to the terms of the Mozilla Public
   - License, v. 2.0. If a copy of the MPL was not distributed with this
   - file, You can obtain one at http://mozilla.org/MPL/2.0/. -->
<svg viewBox="0 0 16 16" xmlns="http://www.w3.org/2000/svg">
  <path d="M4 2v12h9V4.775L9.888 2H4zm0-1h5.888c.246 0
.483.09.666.254l3.112 2.774c.212.19.334.462.334.747V14c0 .552-.448
1-1 1H4c-.552 0-1-.448-1-1V2c0-.552.448-1 1-1z">
  </path>
  <path d="M9 1.5v4c0
.325.306.564.62.485l4-1c.27-.067.432-.338.365-.606-.067-.27-.338-.432-.606-.365l-4
1L10 5.5v-4c0-.276-.224-.5-.5-.5s-.5.224-.5.5z">
  </path>
</svg>
````

This seems to come from https://github.com/devtools-html/debugger.html/blob/0ab605e797178aac92e9fd5480b63844ca4be15b/assets/images/file.svg -- which is already represented as a standalone file in the repository here.  But it seems debugger.html is extracting its SVG DOM and directly appending that to the document for the source-list-pane.

Anyway -- if we're running some operation that synchronously appends a zillion of these to the document (for a zillion source files), I'd bet we could get a speedup by appending a zillion `<img>` elements instead, all pointing to file.svg.

**Comment by digitarald** [comment]
Thanks a lot for the investigation, @dholbert (and confirming my hunch of `background-image` 🕺   ) !

I wonder why that isn't the default for SVG icon use, like here on Github. Regardless for devtools it seems to be the best solution though.

**Comment by amitzur** [comment]
is this the same work as #4350 ?

**Comment by yurydelendik** [comment]
> is this the same work as #4350 ?

Yes, #4350 will help with this issue a lot.

**Comment by jasonLaster** [comment]
So... I think we've made progress here, but the 30K demo still crashes nightly :P

**Comment by jasonLaster** [comment]
still crashes. I wonder if the recent changes @calebstdenis made to add the JS file re-introduces the inline svgs?

**Comment by rebornix** [comment]
Only putting visible nodes to DOM helps with tree creation, scrolling and the overall performance of dev tools, we did that for the editor and any tree view in VSCode, and we are satisfied with the performance gain.

I can take a look at this one if no one else is working on it.

**Comment by jasonLaster** [comment]
That'd be great, I think I can share a version of the tree that buffered the nodes.

Would love your help on it

**Comment by jasonLaster** [comment]
Here is the [commit][c] where we removed the virtualization: 

[c]: 1ab726442e84125378bafb3c871af8a02c2d418d

**Comment by AnshulMalik** [comment]
I did some hacking on this one, this is where I got so far

![source](https://user-images.githubusercontent.com/7821757/38666504-b56e0c5a-3e5c-11e8-9c85-8890fa5496e4.gif)

**Comment by jasonLaster** [comment]
hey, that's cool! It's only crashed for me lately

**Comment by janodvarko** [comment]
Cloned into https://bugzilla.mozilla.org/show_bug.cgi?id=1695200

Firefox Developer Tools (including Debugger tool) development is now entirely happening in Bugzilla and new issues should be reported here: https://bugzilla.mozilla.org/enter_bug.cgi?product=DevTools&component=Debugger

Honza
