### ISSUE TITLE
[Breakpoints] don't trigger on page restart

### ISSUE THREAD

**Issue by yurydelendik** [firefox-devtools/debugger#4200]
STR:

1. Open [example][e] and start debugging
2. Set breakpoints at fetch-brk.html line 6
3. Refresh the page
4. Press 'resume' when needed

Expected result:
Debugger stops at breakpoints

Actual result:
Only stops at debugger statements

[e]:https://yurydelendik.github.io/old-man-sandbox/fetch-brk.html

**Comment by jasonLaster** [comment]
it looks like promises would work by themselves work. https://dbg-then-bp.glitch.me/

this makes me think that there is something do with a race condition w/ fetch.

**Comment by jasonLaster** [comment]
it looks like promises would work by themselves work. https://dbg-then-bp.glitch.me/

this makes me think that there is something do with a race condition w/ fetch.

**Comment by darkwing** [comment]
Can confirm this is still an issue.  I get why it may be a timing issue but the console statement's breakpoint should get hit at some point

**Comment by janodvarko** [comment]
I can still reproduce this issue.
Reported in Bugzilla
https://bugzilla.mozilla.org/show_bug.cgi?id=1603444

Closing
Honza
