### ISSUE TITLE
[Scopes] Right-Click/Copy on properties in tooltip and scopes

### ISSUE THREAD

**Issue by digitarald** [firefox-devtools/debugger#4319]
Console has Copy on properties, Debugger shows a similar object representation but doesn't have any interactions.

My user story here is that I tried to file a useful issue for a broken UI, copying the state of the property that caused the issue. I knew Console has copy in right-click, but Debugger didn't have it. The page I was debugging was https://gregglind.github.io/x-shield-inflight-dashboard/, which fails during the loading process.

**Comment by janodvarko** [comment]
Firefox Developer Tools (including Debugger tool) development is now entirely happening in Bugzilla and new issues should be reported here: https://bugzilla.mozilla.org/enter_bug.cgi?product=DevTools&component=Debugger

Please reopen this report in Bugzilla if it's still valid.

Honza
