### ISSUE TITLE
[SourceTree] JSX files are missing

### ISSUE THREAD

**Issue by jasonLaster** [firefox-devtools/debugger#4373]
STR:

1. navigate to [react todomvc](http://todomvc.com/examples/react/#/active)
2. expand the sources tree

Notice, JSX files are missing.

### firefox
<img src='https://shipusercontent.com/a0d1892ece38fa3b518cbee0424e8cdd/Screen%20Shot%202017-10-13%20at%2010.32.14%20PM.png' title='Screen Shot 2017-10-13 at 10.32.14 PM.png' width=429>

### chrome
<img src='https://shipusercontent.com/262a6c0167c7ee8dd693653c04fa602a/Screen%20Shot%202017-10-13%20at%2010.32.01%20PM.png' title='Screen Shot 2017-10-13 at 10.32.01 PM.png' width=441>

**Comment by bomsy** [comment]
Tried to investigate this a little bit, it seems like we don't even get any of those from the server

**Comment by tromey** [comment]
I think this is probably the problem where `sourceURL` doesn't really work correctly for inline `<script>`.  It's part of the last remaining "big" source map bug.  One approach to fixing it is described in the [source map status document](https://docs.google.com/document/d/19TKnMJD3CMBzwByNE4aBBVWnl-AEan8Sf4hxi6J-eps/edit#heading=h.lyqktbjlcoi6) -- there is at least one outright bug (see [this comment](https://bugzilla.mozilla.org/show_bug.cgi?id=1192882#c3)), but I think there are also some debugger server changes that would have to happen.

**Comment by jasonLaster** [comment]
It looks like the problem is that the script tags are added to the page as inert `<script type="text/jsx" src="js/todoItem.jsx">` and then converted into new `<script>` tags with a text attribute.

```js
function run(code, url, options) {
  var scriptEl = document.createElement('script');
  scriptEl.text = transformCode(code, url, options);
  headEl.appendChild(scriptEl);
}
```

The new script has a text field, which has a `//# sourceMappingURL=` which maps to an original `jsx` source, but it doesn't have a `//# sourceURL=` stanza. This creates some issues for the server/platform which doesnt know how to handle a script tag that doesnt have a script attr or `sourceURL`

**Comment by jasonLaster** [comment]
here's a good mochitest:

https://github.com/jasonLaster/debugger.html/tree/jsx-scripts

The STR is basically load the page and eval `injectScript`

**Comment by jasonLaster** [comment]
@jimblandy and I did a bit of digging today. Here's what we learned:

Context:

When *run* is called it creates a new `<script>` element with the transformed source code and an inline source map. 

The `dbg` handles this correctly and creates a new `Debugger.Source` object with the document's url and the sourceMapURL. 

The server is a bit more complicated and has an interesting relationship with inline scripts [1]. The gist of it is this:
  1. we do not want to show all of the inline scripts in the source tree
  2. when we pause we want to show the debug line in the document

We do this by only telling the client about the document's source and proxying everything through that...

So... how does this relate to our JSX bug!!! Well, the reason we dont see the JSX files is because they're original files that are in the map. And... the map is associated with the inline script which we're ignoring.

So... How do we fix this? The hack, would be to notify the client of each new source map for the document. This would let the client create the original sources for the document and do what it wants to do...

I'm not sure if that is what we want to do though. The reason for that is that we have another bug when we append `<script>` tags dynamically. Pause locations are relative to the script and not the document!

Let me show you :)

Take this example: 

```html
 <html>
  <head>
    <title>Simple</title>
  </head>

  <body>

    <script type="text/plain">
      function bar() {
          debugger
          foo();
      }
    </script>

    <script>
      function foo() {
        debugger;
      }

      function injectScript() {
        const simpleScript = document.querySelector("script[type='text/plain']");
        const newScript = document.createElement("script");

        // debugger;
        newScript.textContent = simpleScript.text;
        document.body.appendChild(newScript);
      }
    </script>
  </body>

</html>
```

The interesting thing is that the function `foo` is inside a `<script>` that's in the document's source. After we call `injectScript`, the function `bar` will be defined inside of a dynamically created script. The problem is that when we pause in `bar` we don't know what line we're in!

| foo | bar |
| -- | -- |
| ![foo] | ![bar] |

The difference here is that we have the correct line for foo and the wrong one for bar. 


How does chrome handle this case? When they pause in `foo` they show the line in the context of the document. When they pause in `bar` they only show bar's script. They differentiate when the script is dynamically created.

| foo | bar |
| -- | -- |
| ![foo-chrome] | ![bar-chrome] |



[foo-chrome]: https://shipusercontent.com/411044e815bac7bfa7395008c574f30e/Screen%20Shot%202018-02-01%20at%205.22.54%20PM.png

[bar-chrome]: https://shipusercontent.com/126b6edf3f157f51e41b9403a4f0ccf2/Screen%20Shot%202018-02-01%20at%205.22.47%20PM.png


[bar]: https://shipusercontent.com/2835c8ed7bca43f334ccf4df0c2f63e8/Screen%20Shot%202018-02-01%20at%205.21.48%20PM.png

[foo]: https://shipusercontent.com/b25bec8626591e41415ed29441789a28/Screen%20Shot%202018-02-01%20at%205.22.09%20PM.png




[1]: https://bugzilla.mozilla.org/show_bug.cgi?id=915433

**Comment by jasonLaster** [comment]
I'd like to punt on this for a bit while we ramp up on the server...

**Comment by jasonLaster** [comment]
I'm moving this to the icebox as it's blocked by some server refactoring. Let's re-evaluate in the next release cycle.

**Comment by digitarald** [comment]
@jasonLaster @loganfsmyth just confirming if this codepen hits the same issue:

Viewed inline with codepen: https://codepen.io/digitarald/pen/QVzJRW
<img width="765" alt="image" src="https://user-images.githubusercontent.com/8599/45779881-1fdf6480-bc11-11e8-8ce5-422cf811f548.png">

In Firefox clicking `pen.js` sources in Console error leads to a view source tab `view-source:http://pen.js/`, 404-ing.

Chrome shows the code correctly.

Chrome's presentation of `pen.js` without domain:
<img width="190" alt="image" src="https://user-images.githubusercontent.com/8599/45780104-abf18c00-bc11-11e8-8baf-381679ea1eec.png">


Viewed in Debug mode: https://s.codepen.io/digitarald/debug/QVzJRW/PBkNWNbjGKdM
<img width="752" alt="image" src="https://user-images.githubusercontent.com/8599/45779900-2b329000-bc11-11e8-8eec-7d5cb8bd6e84.png">
Links to the inline JS work correctly in both Chrome and Firefox.

**Comment by loganfsmyth** [comment]
This works now.
