### ISSUE TITLE
Improve Firefox Panel development workflow

### ISSUE THREAD

**Issue by jasonLaster** [firefox-devtools/debugger#4662]
At the moment, we encourage contributors to work on the debugger in the launchpad. This has a lot of benefits, but it has some drawbacks too: 

* it is not clear how to debug panel issues
* it is not clear that the debugger is the firefox debugger

Tasks:
- [ ] We should improve the docs so that it is clear it is the firefox debugger
- [ ] improve the workflow for building and running firefox [script](https://github.com/jasonLaster/debugger.html/commit/fea74c2676895b2091b2e534841e3eadb34a90a6)
- [ ] add sourcemaps for panel development

---

### sourcemaps

Goal: the browser toolbox shows the debugger original files e.g. Editor/Preview/Popup.js

Steps:
1. enable sourcemaps in webpack
2. add debugger.js.map to moz.build

Goal: it should just be on when doing local development, but we should find a way to not check in the maps nor have the map in moz.build during checkin

![screen shot 2017-11-10 at 11 08 45 am](https://user-images.githubusercontent.com/254562/32667069-97e0f346-c607-11e7-933f-1e4dff00f119.png)

**Comment by loganfsmyth** [comment]
This is pretty much covered now
