### ISSUE TITLE
[Sources] Scripts with Syntax Error are not listed in sources

### ISSUE THREAD

**Issue by nchevobbe** [firefox-devtools/debugger#4798]
Steps to reproduce:
1. Navigate to `data:text/html,<h1>Hello</h1><script>my syntax error</script>`
2. Open the debugger

Expected results:
I can see an item in the source list for my `<script>`

Actual results:
The source list displays `This page has no sources`

---

A direct issue to this is that, if on step `2.` I open the console instead of the debugger, an error will be logged.
And if I click on the location, it won't open the debugger, but the "view source" page.

If the script has no syntax error, the debugger shows it (even with the data url), so this is the SyntaxError which is causing an issue here.

---

_See [Bug 1420381](https://bugzilla.mozilla.org/show_bug.cgi?id=1420381) on Bugzilla._

**Comment by chopstik** [comment]
You learn something every day. Didn't realise you could enter `data:text/html,<h1>Hello</h1><script>my syntax error</script>` into a browser and have that render, slick!

**Comment by lukaszsobek** [comment]
An expanded STR is as follows:
Mentioned above:
- open fresh debugger
- open target tab on document with script error (AR: no sources)
- open same target tab on valid document (AR: no domain + source)

Vid:
![no-sources-display](https://user-images.githubusercontent.com/23530054/34380646-5ca60700-eb03-11e7-8064-a3e7f4f6f359.gif)

Furthermore:
- open valid document
- click valid document again
- reload debugger
- AR: no sources

- click valid document again
- AR: no domain + source

Vid:
![no-sources-display-reload](https://user-images.githubusercontent.com/23530054/34380916-48e330f6-eb05-11e7-8206-23cce6daf341.gif)


There are some things here that can make a person confused e.g. SourcesTree.js on line 188 does not make use of the createTree function whereas the constructor on line 81 does. One nice thing would be to bring both in line to get rid of some wet code. 

Also, a click on a valid piece of code causes the SourceTree to re-render (btw. up to 5 times, which seems to be an issue in itself), whereas a click on a website containing syntax errors causes 1 re-render and no followup reaction. This also seems to be where the lack of the diplayed sources is hiding.

**Comment by lukaszsobek** [comment]
This one is mean. If you switch the state during the same session the changes gets recorded and saved, so when reloading you get the value of the saved changes. But if you reload the tab from launchpad (e.g. close debugger and relaunch the tab) you see that an error in the syntax makes no difference in terms of displaying the source. Both syntax error and no-error result in the same "no sources" display.

**Comment by jasonLaster** [comment]
Closing this issue and moving to the [enhancements](http://github.com/devtools-html/debugger.html/projects/5) board. 

* We will hopefully be able to prioritize it in the near future. 
* The issue is closed temporarily, but feel free to continue discussing the issue

**Comment by chopstik** [comment]
Why are you moving this to enhancements? Prior to the posting of this bug a month or so ago, this behaviour wasn't happening and script errors with the corresponding line/character numbers on the script were being reported/shown correctly. Something prior to the update of FF DeveloperEdition broke this previously useful facility. What are you exactly suggesting is the enhancement if it has already been built?

**Comment by jasonLaster** [comment]
Oh thanks @chopstik. I didn't realize that worked previously.

Does this currently work with Firefox release?

**Comment by chopstik** [comment]
No the issue persists.

**Comment by nchevobbe** [comment]
@chopstik can you remember when it was working ? I tried the old debugger but the source wasn't showing up there

**Comment by chopstik** [comment]
@nchevobbe just prior to me filing the [bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1420381) two months ago. Prior to the FF upgrade to 58 the script error behavior was working fine, an error and its line/character number would take you to that line.character in the offending script. Its failure to link errors to their source prompted me to file the bug report as it was such a useful facility.

**Comment by AnshulMalik** [comment]
I can reproduce this issue on builds from 2017-01-10. I think we didn't support these type of sources from the start.

**Comment by janodvarko** [comment]
Reported as https://bugzilla.mozilla.org/show_bug.cgi?id=1603432

Closing

Honza
