### ISSUE TITLE
[Debugger/Style Editor] Requests for sourcemaps are done without credentials

### ISSUE THREAD

**Issue by cedeber** [firefox-devtools/debugger#4812]
Hi everyone.

It looks like the requests for the sourcemaps (CSS and JS) are done without credentials. I have a 401 error when the site is closed by a login. If I open the access, everything works fine again. The soucemaps work great on Safari and Chrome btw, so it’s not a sourcemaps error.

Here is a screenshot of what happens:

![sourcemaps](https://user-images.githubusercontent.com/3330814/33315765-ed230528-d431-11e7-8dce-beda2109fd42.png)

It won't be easy for you to reproduce the bug as I am using Magnolia CMS, but the project is based on https://github.com/frontools/magnolia-megaton so you can at least have a glance to the build process (done with webpack in the `/frontend` folder).
Thanks

**Comment by codehag** [comment]
related bugzilla bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1404245

**Comment by jasonLaster** [comment]
Hi, sorry for the slow reply - i'm moving this issue to devtools core where we work on source map support

https://github.com/devtools-html/devtools-core/issues/909

**Comment by loganfsmyth** [comment]
Now tracked in https://bugzilla.mozilla.org/show_bug.cgi?id=1149835
