### ISSUE TITLE
[Editor] Debugger displays empty scripts as broken

### ISSUE THREAD

**Issue by codehag** [firefox-devtools/debugger#5070]
Reported on bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1327164

I tried it again, and we are showing an infinite loading screen. would be good to show an empty script instead. we also do not show the name properly in the source tree.

STR_1:
1. Open url [1]
2. Open debugger, switch to script "about:blank"

STR_2:
1. Choose any line [2]-[4]
2. Open url in the line from Step 1
3. Open debugger, switch to script with name mentioned in the line from Step 1

My Info:   Win7_64, Nightly 49, 32bit, ID 20160526082509

1. `data:text/html,<script src="about:blank"></script><script src="data:text/javascript,onclick=function(){console.log(123)}"></script>`
2. `name: "mb"            url: data:text/html,<script src="http://montblanc.rambler.ru/mb"></script><script src="data:text/javascript,onclick=function(){console.log(123)}"></script>`
3. `name: "723233"        url: data:text/html,<script src="https://mc.yandex.ru/watch/723233?wmode=5"></script><script src="data:text/javascript,onclick=function(){console.log(123)}"></script>`
4. `name: "tt.onthe.io"   url: https://rns.online/quote_videos/Politsiya-ne-nazivaet-strelbu-v-Myunhene-teraktom-2016-07-23/?track=head_video`

AR:  Debugger shows error instead of the actual script (user doesn't know yet that it's empty)
ER:  Either X or X+Y
 X) Debugger should show empty script
 Y) Debugger should show a special button/sign saying that script is empty and debugger isn't broken
 
Note:  STR_2 is unreliable, but it proved to me that it happens with all empty scripts on the web

**Comment by janodvarko** [comment]
Let's follow the Bugzilla report.
Closing this one.

Honza
