### ISSUE TITLE
Pass an onViewSourceInDebugger prop to Reps/ObjectInspector

### ISSUE THREAD

**Issue by nchevobbe** [firefox-devtools/debugger#5430]
This props is used to add a "jump to function" icon in the function Rep.
In the debugger, it would allow to go to the definition of a function we see in the Scopes, watch expression or PreviewPopup.
The function is called with the `grip.location` object, which contains the line and column number.

**Comment by jasonLaster** [comment]
@nchevobbe do we still need this?

**Comment by nchevobbe** [comment]
that would be a nice to have. You'd have a button next to function to jump to their definition

**Comment by jasonLaster** [comment]
Oh i see, great

**Comment by loganfsmyth** [comment]
Moving to https://bugzilla.mozilla.org/show_bug.cgi?id=1651775
