### ISSUE TITLE
Blackbox a function in  a script.

### ISSUE THREAD

**Issue by karlcow** [firefox-devtools/debugger#5553]
Currently in the debugger UI, you can blackbox a full script. This is very useful to be able to get rid of a specific library for a step by step analysis of the code.

It would be cool to go a step further.

Blackbox a specific function.

Currently I'm diagnosing a Web site for webcompat https://github.com/webcompat/web-bugs/issues/15683
The page is stepping into this `autoPlayIterator` automagically. I just want to blackbox it aka "hey fx-devtools, don't bother me with it during my debugging process."

```js
  e.prototype.autoPlayClear = function () {
  …
  },
  e.prototype.autoPlayIterator = function () {
  …
  },
  e.prototype.buildDots = function () {
  …
  },
```

so the step by step will jump it without even it make it visible. There could be even a visual reference in the source code where this blackboxed function is called.

**Comment by jasonLaster** [comment]
Thanks for filing. That's a great idea @karlcow. 

We've discussed this feature in the context of blackboxing original files as well. Original files are a portion of a bundle typically and they should also be able to be blackboxed.

**Comment by jasonLaster** [comment]
I'm moving this to the icebox as we don't plan on working on this in the current release. We will re-evaluate at the start of the next release.

**Comment by AnshulMalik** [comment]
I'll try to work on this :)

**Comment by AnshulMalik** [comment]
I made some progress on this [here](https://github.com/AnshulMalik/debugger.html/tree/blackbox-functions). I'll take this off my plate for now.

/unclaim

**Comment by jasonLaster** [comment]
Thanks @AnshulMalik

**Comment by loganfsmyth** [comment]
Moving to https://bugzilla.mozilla.org/show_bug.cgi?id=905450
