### ISSUE TITLE
[Expressions] don't allow async generator functions

### ISSUE THREAD

**Issue by Loirooriol** [firefox-devtools/debugger#5595]
Create a watch expression with these codes:

 - `(function(){})`: works!
 - `(function*(){})`: works!
 - `(async function(){})`: works!
 - `(async function*(){})`: does NOT work! Why??

Analogous for function declarations instead of function expressions.

**Comment by AnshulMalik** [comment]
Hmm, not sure if someone would add function as a watch expression and since these are evaluated on next frame, so I think having an async generator in watch expressions would not meaningful.

I'd love to see if someone can make good use of this in expression. Do you have any example in mind? @Loirooriol

**Comment by Loirooriol** [comment]
Yes, I agree promises are not much useful in watch expressions. But I still think it should work, it's valid syntax after all.

**Comment by bomsy** [comment]
![image](https://user-images.githubusercontent.com/792924/37370164-3f576c3e-2703-11e8-86be-023ded29d0f6.png)

**Comment by jasonLaster** [comment]
oh that's a babel error... because we're not parsing async generators... we could add that plugin in both original and generated cases, but that could be a perf hit too.

**Comment by Loirooriol** [comment]
What about not using babel at all? Treat watch expressions really as expressions, and validate them with the native `Function` constructor.

```js
function isValidExpression(code) {
  try {
    Function("return " + code + ";");
    Function("(" + code + ")");
    return true;
  } catch (err) {
    return false;
  }
}
if (isValidExpression(code)) {
  evaluate("try { (" + code + ") } catch (e) { e }");
}
```

**Comment by loganfsmyth** [comment]
This works now, likely because we've pulled in a newer version of Babel's parser.
