### ISSUE TITLE
Update selectLocation to do less work with regard to pretty print

### ISSUE THREAD

**Issue by darkwing** [firefox-devtools/debugger#5618]
Pretty-printing, especially auto-pretty-printing, is a performance hit because the following process takes place:

1.  Original source tab is loaded, opened
2.  Pretty-print tab is loaded, opened
3.  Original source tab is closed

This hurts performance because we should only need to do point 2.  Additionally, opening the original tab triggers a bunch of unnecessary work like editor syntax highlighting and other redux calls.

Moreover `selectLocation`, the function which does all of this work, is probably doing too much based on not enough information, which in many cases leads to opening the original source tab when the pretty-print tab is already open.

**Comment by jasonLaster** [comment]
Adding this to the sprint. We can take it out if we don't start it by thursday

**Comment by lukaszsobek** [comment]
Maybe if we make an outline of steps to take here it would be easier to tackle the issue quickly?

**Comment by jasonLaster** [comment]
here's another patch - https://gist.github.com/24a120916c1c5c232a99307cbcbcccaa

**Comment by janodvarko** [comment]
Cloned into: https://bugzilla.mozilla.org/show_bug.cgi?id=1695219

Firefox Developer Tools (including Debugger tool) development is now entirely happening in Bugzilla and new issues should be reported here: https://bugzilla.mozilla.org/enter_bug.cgi?product=DevTools&component=Debugger

Honza
