### ISSUE TITLE
Slow performance with VSCode/Angular

### ISSUE THREAD

**Issue by digitarald** [firefox-devtools/debugger#5641]
Tracking issue reported via https://twitter.com/ekveel/status/971685803742121984

- Uses VSCode to remote debug Firefox
- Web app is a simple Angular app
- Reports 30s startup for the debugger after starting debug session in VSCode

**Comment by Ekveel** [comment]
Hey there, I'm the guy from twitter who wrote about this

**What do I have?:**

I have a basic Angular 5 App which represents a treeview. Nothing big. 
My Backend is a .NET Core Webservice. 
I'm using VS Code Version 1.20.1 right now.
Firefox Quantum Version 58.0.2 (64-Bit)
Debugger for Firefox Version 1.1.0 (using this in VS Code) [https://github.com/hbenl/vscode-firefox-debug](url)

**What is happenings?:**

Normally the debug tab which shows up if you press F12 works fine however once you start the debugger mentioned above, Firefox cant load the the panels in the debug tab. It either takes atleast 30seconds to show the first words (not finished) or just stops responding at all, making the browser crash. 
Stopping the debugger turns everything back to normal

**My launch settings in VS Code to debug:**

{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Launch Chrome",
            "type": "chrome",
            "request": "launch",
            "url": "http://localhost:4200",
            "webRoot": "${workspaceFolder}/wwwroot"
        },
        {
            "name": "Launch Firefox",
            "type": "firefox",
            "request": "launch",
            "reAttach": true,
            "url": "http://localhost:4200",
            "webRoot": "${workspaceFolder}"
        }
    ]
}

Hope this helps

**Comment by janodvarko** [comment]
It's been a while since this was reported, perhaps it's fixed?

Firefox Developer Tools (including Debugger tool) development is now entirely happening in Bugzilla and new issues should be reported here: https://bugzilla.mozilla.org/enter_bug.cgi?product=DevTools&component=Debugger

Please reopen this report in Bugzilla if it's still valid.

Honza
