### ISSUE TITLE
[Scopes] Default expanded view should include all scopes up to the function's parameters

### ISSUE THREAD

**Issue by julienw** [firefox-devtools/debugger#5754]
STR:
1. Break into a function that has parameters

The default expanded view only has the current block. It would be very useful to have all scopes expanded up to the current function's arguments.
Especially even when breaking at the first line of a function, at the outermost block of the function, the argument's scope isn't expanded.

As a bonus: it may be a good idea to open more enclosing scopes when we detect the function is small, but I understand this can be more work, and I'd already be very satisfied with the first part of the issue.

**Comment by jasonLaster** [comment]
@julienw can you share an STR with screenshots. I think this might be a bug with our lexical scopes ie. let and const

**Comment by julienw** [comment]
Here is a testcase:

```javascript
<!doctype html>
<html>
  <head>
    <meta charset='utf-8'>
    <meta name='viewport' content='initial-scale=1'>
  </head>
  <body>
    <button>click me!</button>
  <script>
document.querySelector('button').addEventListener('click', () => {
  runSomething(1, "foo");
});

function runSomething(arg1, arg2) {
  const foo = "foo";
  for (let i = 0; i < 10; i++) {
    console.log(i);
  }
  const result = [1, 2, 3].map(val => {
    return foo + val;
  });
}
  </script>
  </body>
</html>
```

STR for the simpler case is:
1. Break on line 15 on `const foo = "foo"`

![Capture for the simpler case](https://user-images.githubusercontent.com/454175/37798704-d622b4b8-2e1d-11e8-9fcf-da08408bb2bc.png)

STR for the complicated case is:
1. Break on line 17 on `console.log(i)`

![Capture for the complicated case](https://user-images.githubusercontent.com/454175/37798762-fe7cd614-2e1d-11e8-829c-427f77c9c05d.png)

STR for the bonus is:
1. Break on line 20.

![Capture for the bonus case](https://user-images.githubusercontent.com/454175/37798795-14388dea-2e1e-11e8-8cdb-2c1e2d279a5b.png)

**Comment by jasonLaster** [comment]
I believe that this bug fixes this. https://bugzilla.mozilla.org/show_bug.cgi?id=1431461

@jorendorff what do you think?

**Comment by julienw** [comment]
This will likely fix case 1, but not case 2. This is correct that we have several block scopes here. But in the UI my view is that they should be expanded already.

**Comment by jorendorff** [comment]
@julienw's last comment seems right to me.

**Comment by janodvarko** [comment]
Cloned into Bugzilla https://bugzilla.mozilla.org/show_bug.cgi?id=1661696

Our bug tracking is moved to Bugzilla, so please use this link to file new bugs: 
https://bugzilla.mozilla.org/enter_bug.cgi?product=DevTools&component=Debugger

Honza
