### ISSUE TITLE
[Breakpoints] The debugger breaks at unexpected places when addons inject code

### ISSUE THREAD

**Issue by julienw** [firefox-devtools/debugger#5817]
STR:
1. Install the [React Addon](https://addons.mozilla.org/en-US/firefox/addon/react-devtools/)
2. open https://spotty-walker.glitch.me/
3. Open the index file in the debugger
4. Add breakpoints at the first lines of function test2 (line 14)
5. Reload the page
=> We stop at a weird place:

![Capture](https://user-images.githubusercontent.com/454175/38080094-d9bd407a-3340-11e8-9efa-33f6011059e8.png)

Everything looks as if we stopped at the second breakpoint, but the callstack is weird. We actually stopped in the addon's code:

![Capture in React Addon's code](https://user-images.githubusercontent.com/454175/38080942-16e72126-3343-11e8-8185-375c02fb48f5.png)
`js` holds the code of their injected script.

Here is the full code for the example:
```html
<!doctype html>
<html>
  <head>
    <meta charset='utf-8'>
    <meta name='viewport' content='initial-scale=1'>
  </head>
  <body>
    <script>
function test1(foo = "bar", native = true) {
  const hello = "world";
  console.log(foo, native, hello);
}
function test2(foo, native) {
  const hello = "world";
  console.log(foo, native, hello);
}

test1();
test2();
    </script>
  </body>
</html>
```

**Comment by janodvarko** [comment]
This works for me in Fx73 closing.

Honza
