### ISSUE TITLE
[PrettyPrint] Instant crash on prettify on ravelry.com

### ISSUE THREAD

**Issue by karlcow** [firefox-devtools/debugger#5894]
With Firefox Nightly 61.0a1 (2018-04-09) (64-bit)
on macOs 10.13.4 (17E199)

1. Go to https://www.ravelry.com/account/login
2. Login and password (creation is free)
3. open the debugger tool. 
4. go to https://www.ravelry.com/patterns/search#query=
5. open https://style-cdn.ravelrycache.com/javascripts/search2_1803061301.js in the left panel of the debugger.
6. Click on the `{ }` to prettify the script.

Actual:
Instant crash of the browser

Expected
Unminified script.

Reproduced 5 times in a row.

**Comment by darkwing** [comment]
Hello @karlcow!  I tested this today on Mac Firefox Nightly and no crash:

<img width="1423" alt="nightlyonmac" src="https://user-images.githubusercontent.com/46655/40867795-d1e7a16a-65cc-11e8-8033-877523eda32e.png">

If you're still crashing, could you provide more information about your system/environment where this is happening?

**Comment by darkwing** [comment]
I tested this today on a gaming PC and found that:

1.  I clicked once on the pretty print icon and heard my PC's fan kick in but the pretty print tab did not open
2.  I clicked again and the pretty print tab opened quickly but the fan kept running
3.  There were approximately 2324 lines of code
4.  Firefox choked when trying to close and reopen Firefox ("Another Firefox process is already running...")

I see `prettyPrint` is completed in a worker so we'll need to investigate how we can make this more performant

**Comment by karlcow** [comment]
@darkwing Yup it didn't crash for me anymore.

**Comment by karlcow** [comment]
but I noticed that the CPU was going up to 200% in top -o cpu, so probably a combination of the two crashed the browser.

**Comment by darkwing** [comment]
Since the browser isn't crashing, I'm going to remove P1 but it definitely needs addressing.

**Comment by janodvarko** [comment]
@karlcow I am closing this since it seems that it doesn't crash anymore.

If you see the problem again, please create a new report in Bugzilla.
https://bugzilla.mozilla.org/enter_bug.cgi?product=DevTools&component=Debugger
Honza
