### ISSUE TITLE
[SourceTree] Script inside of iframe is not displayed in Sources pane

### ISSUE THREAD

**Issue by blikblum** [firefox-devtools/debugger#5975]
When a script is inside an iframe, is not displayed in the source tree (Sources pane). This makes impossible to evaluate such code.

Example is JSBin:

 * Open http://jsbin.com/lohexapude/edit?html,js,output
 * The JSBin output pane is displayed in an iframe which has a second iframe as child where the bin code (added to JavaScript pane) lives inside a script tag. This code is not listed in source tree becoming unreachable

For reference, Chrome list this code in their source tree in a separated item: 

\<proxy\> (runner) > JS Bin Output (about:blank) > (no domain) > lohexapude.js
 
Tested with debugger.html from master and in firefox 60

**Comment by ZhangYue-vhyt** [comment]
My test is below:

Chrome:
![image](https://user-images.githubusercontent.com/9450184/48665176-0a06e800-ea78-11e8-94ff-4e3f6e1e512c.png)

Firefox:
![image](https://user-images.githubusercontent.com/9450184/48665182-23a82f80-ea78-11e8-9795-fc26d3789e4b.png)

It displays but not separated.

**Comment by blikblum** [comment]
> It displays unseparated in Firefox

Just tested now with a updated Firefox Dev Edition, v64b10

There's no jsbin.com node, only static.jsbin.com:

![image](https://user-images.githubusercontent.com/3047126/48666719-5a993800-eaae-11e8-89d5-fb1fff4465f2.png)

**Comment by ZhangYue-vhyt** [comment]
> There's no jsbin.com node, only static.jsbin.com:

There is `jsbin.com` node in my picture. I did the test with the latest debugger cloned from Github. I also typed Ctrl+k in Firefox, it is not there. So I guess even the latest Firefox Dev Edition doesn't have the latest debugger.

**Comment by janodvarko** [comment]
I can still reproduce the issue in Fx73
Reported in Bugzilla:
https://bugzilla.mozilla.org/show_bug.cgi?id=1603723

Closing this one.

Honza
