### ISSUE TITLE
Firefox hangs after trying to break in PlacesUtils.jsm

### ISSUE THREAD

**Issue by juliandescottes** [firefox-devtools/debugger#5981]
BrowserToolbox bug

STRs:
- start Firefox
- open browser toolbox
- open PlacesUtils.jsm
- set a breakpoint at line 766 (`if (!parent && aNode...`)
- go back to Firefox
- Bookmarks menu > Show All Bookmarks 
  - note that before debugger v37, the breakpoint is hit at this step. Resume if it is.

=> Firefox hangs (UI unresponsive etc ...)

cc @Standard8

**Comment by Standard8** [comment]
Also, in the console, there's lots of "Unable to run script because scripts are blocked internally" that get repeated.

**Comment by jasonLaster** [comment]
I was able to reproduce it on the current central w/o Release 37 & 36.

Here are some screenshots

![Screen Shot 2018-04-16 at 8.47.49 AM.png](https://shipusercontent.com/7124608c207c3b54430d2a7ef7b74a7b/Screen%20Shot%202018-04-16%20at%208.47.49%20AM.png)
![Screen Shot 2018-04-16 at 8.46.16 AM.png](https://shipusercontent.com/096c132b358a92d81b0450411f7ae75b/Screen%20Shot%202018-04-16%20at%208.46.16%20AM.png)

**Comment by jasonLaster** [comment]
Alright... so i've narrowed the regresson window to:
14:12.31 INFO: Getting mozilla-central builds between f4fcdaef616807d1e31a849db0c60a3a4bdc8778 and 3f9a70b125f6fb9be2b209159657fd7ae5515c01

I believe this issue is in platform and not the debugger.

It looks like there are plenty of run to completion issues here as well.

Lets move this bug to bugzilla where it can be tracked closer to the issue.

**Comment by juliandescottes** [comment]
Thanks for checking the regression window. As a pushlog that gives us: https://hg.mozilla.org/mozilla-central/pushloghtml?fromchange=f4fcdaef616807d1e31a849db0c60a3a4bdc8778&tochange=3f9a70b125f6fb9be2b209159657fd7ae5515c01

At first I can't see anything suspicious here.

**Comment by janodvarko** [comment]
@juliandescottes can you still reproduce the bug? 

I couldn't follow the STRs `set a breakpoint at line 766 (if (!parent && aNode...)` Looks like the code base changed.

Honza

**Comment by juliandescottes** [comment]
Issue is 2 years old so let's close it.
