### ISSUE TITLE
CPU churn when switching back to tab with debugger open

### ISSUE THREAD

**Issue by digitarald** [firefox-devtools/debugger#6010]
Had debugger open on a react/babel app and switched to another tab. After switching back, not interacting with the debugger, my fan kicked in.

https://perfht.ml/2J1LDGr

Looks like the server messages coming in causes some extra work.

**Comment by janodvarko** [comment]
Firefox Developer Tools (including Debugger tool) development is entirely happening in Bugzilla and new issues should be reported here: https://bugzilla.mozilla.org/enter_bug.cgi?product=DevTools&component=Debugger

Honza
