### ISSUE TITLE
Add back href attributes in links

### ISSUE THREAD

**Issue by nchevobbe** [firefox-devtools/debugger#6108]
_From @Loirooriol on March 30, 2018 13:53_

Previously, when viewing a JSON document, I could right-click linked resources like videos and images and just choose "Save Link As...".

In #989 you removed `href` from links. This is not semantic and breaks my workflow, because now the context menu is useless.

_Copied from original issue: devtools-html/devtools-core#1020_

**Comment by Loirooriol** [comment]
@darkwing It's devtools-html/devtools-core#989
