### ISSUE TITLE
Use object.constructor.name where available

### ISSUE THREAD

**Issue by nchevobbe** [firefox-devtools/debugger#6117]
_From @MikeRatcliffe on December 24, 2017 15:16_

#### STR

1. Type the following into the web console:
   ```
   function myClass() {}
   var instance = new myClass();
   instance
   ```
2. In Firefox DevTools we display `Object {  }`
3. Chrome DevTools checks for `instance.constructor.name` for Object types and displays the constructor name if it exists e.g. `myClass {}`, which is more informative.

_Copied from original issue: devtools-html/devtools-core#873_

**Comment by nchevobbe** [comment]
_From @Loirooriol on December 24, 2017 18:27_

What if an object has a `constructor` property but it's not a function or it's not a constructor of the object?
What if the name is e.g. `"Array"` but the object is not an exotic array? This could mislead users.
What if the constructor or the name change?

What the console displays is the class, which is supposed to be an inherent characteristic of the object. The value of `object.constructor.name` is not inherent.

So I disagree. If somebody wants to see the name of the constructor, they can expand the object, expand the [[Prototype]], and they will see something like `▶ constructor: function myClass()`

**Comment by nchevobbe** [comment]
_From @david95thinkcode on December 24, 2017 20:13_

@Loirooriol ,I understand what you're saying.
When you ask

> What if the name is e.g. "Array" but the object is not an exotic array? This could mislead users.

Seriously why somebody would choose "Array" as an object name ? I think it's rare and not a good practice.

When I dev, I don't want to have to expand the object before knowing its type. Admit, It's more efficient when you see object name. I really want that feature on Firefox Devtool.

**Comment by nchevobbe** [comment]
_From @david95thinkcode on December 24, 2017 20:22_

In my opinion, this one is more informative 
![chrome-2](https://user-images.githubusercontent.com/24503308/34328975-7daacb7c-e8ef-11e7-964d-96e72a729305.png)
We can always expand the object to see more informations about it.

**Comment by nchevobbe** [comment]
_From @Loirooriol on December 24, 2017 22:29_

> Seriously why somebody would choose "Array" as an object name?

It doesn't need to be explicitly chosen, e.g. `Object.create(Array.prototype)` creates an ordinary object that inherits from a constructor with an `"Array"` name, but it's not an exotic array, so the console should not say `Array`.

**Comment by nchevobbe** [comment]
_From @david95thinkcode on December 29, 2017 21:15_

> Object.create(Array.prototype) creates an ordinary object that inherits from a constructor with an "Array" name, but it's not an exotic array, so the console should not say Array.

I think the console should say it cause that's what we want to see (the constructor name).
Actually, 

1. when we make a `console.log` of an **Array** on firefox devtools, we see something like `Array["Baba", "Bobo", "Foo"]`. It's informative, that's right. 
2. when we make a `console.log` on a object that inherits from a constructor with an "Array" name, we will see something like :  `Object { example: "Just a test" }`. I think it won't show us `Array { }`.

For the second point, I think the console should say `Array { }` cause **Array** is the constructor name.
If we want to avoid confusion between `Array { }` and `Array [ ]`, the console should just say something like `[ number of item inside the array ]` instead of `Array [ ]`.

**Comment by nchevobbe** [comment]
_From @Loirooriol on December 29, 2017 22:26_

> I think the console should say it cause that's what we want to see (the constructor name).

Not me. What I want to see is the (Mozilla's generalization of the) ES5 [[Class]] internal slot of the object. There is no other way to see this useful info in the console, and you want to remove it and replace it with a redundant one which can be obtained just by expanding the object.

> If we want to avoid confusion between `Array { }` and `Array [ ]`

Note the brackets nor the number of items can't be used to distinguish them, and that's because there are [pseudo-array](https://searchfox.org/mozilla-central/rev/a6cfee725b9e49adda2c81ced98f27de55603d4e/devtools/server/actors/object.js#1978-1983) objects that are displayed using an array notation. This is useful and non-ambiguous because we can still see the [[Class]], which now you want to remove.

And as I said, the [[Class]] is an intrinsic value that does not change. Of course this does not work for constructor names. How do you plan to do this if the constructor name has a getter? The console must not call unsafe getters! What if the constructor is a proxy? The console must not call proxy traps! What if the constructor name changes? But this is just the tip of the iceberg! The object could not have a constructor! In fact, how do you define the constructor? It's not obvious, because there is no invariant that allows a meaningful definition.

**Comment by nchevobbe** [comment]
_From @konradpapala on April 23, 2018 21:15_

I'm just a regular user, sorry for jumping in with my comment here, but this particular feature is something I really miss in FX and so here I am :)

@Loirooriol 

I think you point out some edge cases, while in 99.99998% of situations, this would simply be a useful and nice feature.

You mention some dangerous(?) situations, like "The console must not call unsafe getters (...) What if the constructor is a proxy?" - well, can't this (again: edge cases) be detected? And then, well, you would simply go with the current solution, i.e. display only 'Object {}'?

After all, somehow Chrome did it  :smiley: 

And if all these arguments will be rejected, then what about just making it optional? 

BTW, thanks to you and everyone for your work!

**Comment by nchevobbe** [comment]
_From @Loirooriol on April 23, 2018 21:49_

> can't this (again: edge cases) be detected?

Yes, though that would mean the result would be less consistent.

But my other complaint still stands: if I have an array-like object which is not an array but inherits from `Array.prototype`, I still want to know that it's not a real array (and thus e.g. decreasing `length` won't remove properties).

Or if I have an instance of `class Foo extends Map{}`, I still want to see that the result is a map object. Getting `Foo` instead would be OK if I wrote the `Foo` class myself because I already know it extends `Map`, but if I'm debugging code from someone else I think it's less useful.

Making it optional could be a solution, but I think the problem is also that it's not totally clear how this should behave. Chrome does weird things like showing `Foo []` for `new class Foo extends Array{}`, but `Map(0) {}` for `new class Foo extends Map{}`; very inconsistent and confusing. I also wonder about constructors with huge names, should they be truncated?

**Comment by julienw** [comment]
I believe the name could be displayed separately from the "native" type.

**Comment by nchevobbe** [comment]
Filed in https://bugzilla.mozilla.org/show_bug.cgi?id=1526688
