### ISSUE TITLE
Stop using unreliable isGrip

### ISSUE THREAD

**Issue by nchevobbe** [firefox-devtools/debugger#6118]
_From @Loirooriol on December 12, 2017 16:34_

The `isGrip` function is completely unreliable:

https://github.com/devtools-html/devtools-core/blob/e9238260b69412731d3f158444be5a10eb8f2658/packages/devtools-reps/src/reps/rep-utils.js#L15-L17

It should be removed in favor of the `noGrip` parameter.

Otherwise nasty bugs like https://bugzilla.mozilla.org/show_bug.cgi?id=1377668 may happen. Just fail fast and loud to detect what uses should pass `noGrip = true`, and otherwise assume it's a grip.

_Copied from original issue: devtools-html/devtools-core#844_

**Comment by nchevobbe** [comment]
we do have a `noGrip` option now, that is passed down from the JSON Viewer

**Comment by Loirooriol** [comment]
`noGrip` already existed when I filed this. That's the point, remove the unreliable `isGrip` in favor of `noGrip`.

`isGrip` is still there: https://searchfox.org/mozilla-central/rev/df23c6e58c6be1eb8399e475878f73d4867bef87/devtools/client/shared/components/reps/reps/rep-utils.js#75-77
