### ISSUE TITLE
Users should be able to copy values

### ISSUE THREAD

**Issue by nchevobbe** [firefox-devtools/debugger#6141]
_From @jasonLaster on July 17, 2017 14:11_

It is currently difficult to copy an object inspector's value.

1. the value does not have any user-select behavior
2. the context menu does not show copy

* I think we should support text selection when it is a text value like string, number.
* we should support copy to temporary variable
  * It might be nice to explore copying a temporary variable when the user clicks on a non-serializable object...

_Copied from original issue: devtools-html/devtools-core#507_

**Comment by unsign3d** [comment]
/unclaim
sorry guys :/

**Comment by nchevobbe** [comment]
Looks like this is covered by https://bugzilla.mozilla.org/show_bug.cgi?id=1573088
