### ISSUE TITLE
Style non-enumerable/non-writables properties in the ObjectInspector

### ISSUE THREAD

**Issue by nchevobbe** [firefox-devtools/debugger#6142]
_From @nchevobbe on July 17, 2017 14:5_

In the VariableView, there was a lock at the end of the line, which has a title stating if the property was not enumerable/writable/configurable/extensible. It would be nice to have something like that in the ObjectInspector.

We should not blindly copy the original behavior, maybe we can do something better for this ?

_Copied from original issue: devtools-html/devtools-core#506_

**Comment by nchevobbe** [comment]
_From @jasonLaster on July 17, 2017 14:7_

Yeah - I think the lock is a bit much, especially because the right most column could be useful later.

I'd prefer something softer and perhaps a different hover behavior.

**Comment by nchevobbe** [comment]
_From @Loirooriol on August 15, 2017 12:32_

You could show a pencil if it's writable/configurable. Clicking the pencil would show a textbox to edit the value (#500). The lack of a pencil would mean it's not writable/configurable.

**Comment by wale-bant** [comment]
I'd like to work on the solution as described by @nchevobbe

**Comment by masihtamsoy** [comment]
@nchevobbe is this issue available? Can you provide me with initials to get started?

**Comment by nchevobbe** [comment]
sure
so the work happens in mozilla-central now, no more on github.
You can check how to setup everything to work http://docs.firefox-dev.tools/getting-started/ 

This is the place where we create the `key: value` elements [devtools/client/debugger/packages/devtools-reps/src/reps/prop-rep.js#64-72](https://searchfox.org/mozilla-central/rev/6866d3a650c826f1cabd123663e84b95ee743701/devtools/client/debugger/packages/devtools-reps/src/reps/prop-rep.js#64-72) 

So we would to need add an icon, or set a tooltip for non-enumeratable/non-writable properties

**Comment by masihtamsoy** [comment]
Thanks @nchevobbe

**Comment by nchevobbe** [comment]
filed https://bugzilla.mozilla.org/show_bug.cgi?id=1612132
