### ISSUE TITLE
Add ability to edit properties in OI

### ISSUE THREAD

**Issue by nchevobbe** [firefox-devtools/debugger#6144]
_From @bgrins on July 13, 2017 16:20_

See https://bugzilla.mozilla.org/show_bug.cgi?id=1380502.

When you double click on a property value in the OI, it could convert into a textbox and let you edit the property value, as in the variables view

_Copied from original issue: devtools-html/devtools-core#500_

**Comment by nchevobbe** [comment]
@kootoopas hey, I see you are interrested in this. Do you want me to assign the issue to you (we don't have /claim support here for now)

**Comment by nchevobbe** [comment]
_From @jasonLaster on December 13, 2017 17:5_

@bgrins @nchevobbe I'd like to discuss some of the UX here. 

I found the old debugger variable view ux confusing at times.

**Comment by nchevobbe** [comment]
_From @kootoopas on December 13, 2017 19:37_

@nchevobbe I'm eager to implement once the UX decisions are resolved! :)

**Comment by nchevobbe** [comment]
FYI, I find this feature very confusing as well :D We do definitely need to discuss about it

**Comment by darkwing** [comment]
Is this complete @nchevobbe ?

**Comment by nchevobbe** [comment]
No, we still need to discuss properly of the UX here and why people would want that.

**Comment by nchevobbe** [comment]
closing as it's tracked in Bugzilla
