### ISSUE TITLE
Reps: ArrayRep should also display custom properties

### ISSUE THREAD

**Issue by nchevobbe** [firefox-devtools/debugger#6145]
_From @janodvarko on July 12, 2017 9:24_

An array object can have custom properties just like any other regular JS object.

An example:
```
let arr = new Array(10);
arr.myCustomProp = true; // custom prop
```
ArrayRep should be able to render those properties (as an expandable tree using Object inspector?)

Honza

_Copied from original issue: devtools-html/devtools-core#497_

**Comment by nchevobbe** [comment]
the custom property is shown when the object is expanded, but not when it's not

**Comment by nchevobbe** [comment]
_From @gregtatum on November 27, 2017 15:48_

Adding myself to this to maybe take in the future @gregtatum

**Comment by masihtamsoy** [comment]
Hi @nchevobbe, is this issue available? Want to check this out? Can you provide me with initials

**Comment by nchevobbe** [comment]
The property is visible when expanding the array: 

<img width="184" alt="image" src="https://user-images.githubusercontent.com/578107/66749806-11529380-ee8b-11e9-80ed-09b247d99e79.png">

so I think we can close this issue :)
