### ISSUE TITLE
Find a better way to represent empty strings

### ISSUE THREAD

**Issue by nchevobbe** [firefox-devtools/debugger#6146]
_From @nchevobbe on July 11, 2017 15:27_

__From https://bugzilla.mozilla.org/show_bug.cgi?id=1375752__

---

If you try to render an empty string Rep (`""`), and have `useQuotes = false`, the Rep will render `<span class="objectBox objectBox-string"></span>`, i.e. an empty element.

This might be weird in some cases (e.g. `console.log` which pass `useQuotes = false` to render its arguments).
~It shouldn't hurt to always show the quotes if the string is empty, no matter what the value of `useQuotes` is, but maybe I'm missing something ?~

Let's think about better way to display empty strings.

_Copied from original issue: devtools-html/devtools-core#490_

**Comment by nchevobbe** [comment]
_From @Loirooriol on July 13, 2017 17:6_

How are you going to distinguish `console.log('""')` from `console.log('')`?

String quotes should have another color different than `--string-color`.

**Comment by nchevobbe** [comment]
Good point. @bwinton was suggesting having some styling to tackle this issue.

**Comment by nchevobbe** [comment]
_From @bwinton on July 13, 2017 21:2_

A quick example: https://drive.google.com/file/d/0B8P86wwg0hsfTm9zZ2tQWFhkcjg/view 😄
(It's about a 3 line CSS change… 😉)

**Comment by nchevobbe** [comment]
_From @bgrins on July 17, 2017 20:43_

> A quick example: https://drive.google.com/file/d/0B8P86wwg0hsfTm9zZ2tQWFhkcjg/view 😄
> (It's about a 3 line CSS change… 😉)

Even apart from the empty string situation, I like this more than the current hover state where we highlight the entire message node

**Comment by nchevobbe** [comment]
We could also use the `∅` char with some styling and a title attribute stating it's an empty string.

**Comment by nchevobbe** [comment]
`console.log("", 42)` only renders an element for 42, we should check if react does something weird or if it the string rep

**Comment by Hindelburg** [comment]
So I have been trying to track down where exactly in the code I should be making this change, and I found where I thought would be correct, "packages/devtools-reps/src/reps/string.js", but none of the changes I make seem to be having any effect whatsoever. Am I doing something wrong, or do I have to do something special with my build to be able to effect changes to the console?

**Comment by nchevobbe** [comment]
Hey @Hindelburg , you should try to use the Reps launchpad (see https://github.com/devtools-html/debugger.html/tree/master/packages/devtools-reps#getting-started) and evaluate an empty string.
Tell me how this works for you

**Comment by nchevobbe** [comment]
done in https://bugzilla.mozilla.org/show_bug.cgi?id=1375752
