### ISSUE TITLE
 Print dates in local timezone

### ISSUE THREAD

**Issue by nchevobbe** [firefox-devtools/debugger#6153]
_From @nchevobbe on June 5, 2017 12:55_

_Moved from https://github.com/devtools-html/reps/issues/114_

See https://bugzilla.mozilla.org/show_bug.cgi?id=1073533

We are using ISO string when we output a date, which might be confusing depending on your timezone.
It'd be more clear to output the local timezone.

_Copied from original issue: devtools-html/devtools-core#400_

**Comment by Hindelburg** [comment]
I'm interested in trying to fix this bug but have noticed that it is "not-available". I would assume that means that I can't claim/fix it, but want to be 100% sure. I'm really new to this whole open source thing.

**Comment by darkwing** [comment]
Hello @Hindelburg -- this is definitely available -- sorry for the errant label.  Have at it! :)

**Comment by nchevobbe** [comment]
Hey, @Hindelburg , is this something you'd be still interested in?

**Comment by GettyOrawo** [comment]
`/claim`
