### ISSUE TITLE
[Pretty Print] fails with sourceMap error when Source Maps is off

### ISSUE THREAD

**Issue by digitarald** [firefox-devtools/debugger#6328]
STR: Prettify on a js file on google.com
AR: Works for me, fails for @karlcow 

@karlcow did create a fresh profile last week and did not have `Source Maps` on in devtools.

`TypeError: sourceMaps is null – prettyPrint.js:112:9`

Issues to follow up on:
- Why is source maps off by default in a new Nightly profiles?
- Prettify should work without source maps (or don't allow disabling source maps)

**Comment by karlcow** [comment]
@jasonLaster Just to understand. Does that mean that people who do not include source maps in their projects OR all legacy Web sites with old frameworks without source maps but minified code, we will not be able to see a "prettified" version?

**Comment by jasonLaster** [comment]
@karlcow it works for all websites when "source maps" is enabled in settings

**Comment by loganfsmyth** [comment]
We fixed this a while back.
