### ISSUE TITLE
[Stability] Implement componentDidCatch to Prevent App Bricking

### ISSUE THREAD

**Issue by darkwing** [firefox-devtools/debugger#6384]
We have some high risk failure point components but we aren't using `componentDidCatch` (https://reactjs.org/docs/error-boundaries.html) so we risk the debugger completely bricking, which is something we should avoid at all costs.

## Important Components
- [ ] App
    -  Solution:  TBD
- [ ] Editor
    -  Solution:  TBD
- [ ] Preview
    -  Solution:  TBD
- [ ] SourcesTree
    -  Solution:  TBD
- [ ] PrimaryPanes/index.js ?
    -  Solution:  TBD
- [ ] SecondaryPanes/index.js ?
    -  Solution:  TBD

## Ideas
-  Move errors into telemetry or sentry
-  Display error for user?
-  Have different solution based on development mode and production

**Comment by loganfsmyth** [comment]
Closing in favor of https://bugzilla.mozilla.org/show_bug.cgi?id=1589265
