### ISSUE TITLE
Bring changes from https://bugzilla.mozilla.org/show_bug.cgi?id=1438835 into tree component.

### ISSUE THREAD

**Issue by yzen** [firefox-devtools/debugger#6404]
Changes in that bug remove dependency on native events and related target when the tree component handles focus event. This might help with getting to the root cause of source tree re-rendering on focus described in #6015

**Comment by janodvarko** [comment]
Firefox Developer Tools (including Debugger tool) development is now entirely happening in Bugzilla and new issues should be reported here: https://bugzilla.mozilla.org/enter_bug.cgi?product=DevTools&component=Debugger

Please reopen this report in Bugzilla if it's still valid.

Honza
