### ISSUE TITLE
Stop on breakpoint causes the logs to persist in console

### ISSUE THREAD

**Issue by nicofrand** [firefox-devtools/debugger#6415]
**STR:**

0. Open http://jsbin.com/nunoteqesu/1/edit?html,js,output
0. Open the devtools, with both debugger + console displayed
0. Make sure "Persist logs" is unchecked in the console
0. Check "Stop on uncaught errors" in the debugger
0. Click the "TRIGGER BUG" button
0. Do not touch the debugger (keep it on hold)
0. Refresh the page

**What happens:**

The JS error (triggered before page refresh) appears in the console after the page is refreshed.

**What I expect:**

The JS error (triggered before page refresh) **does not** appear in the console after the page is refreshed (since it is a different context, etc.).

**Comment by darkwing** [comment]
This appears to still happen @nchevobbe -- any ideas here?

**Comment by nchevobbe** [comment]
So I did not do any investigation yet, but what I can tell is that the console is cleared when we receive the `will-navigate` event.
I guess the event is emitted before the error (which might only be when we're not in a "paused" state anymore?)

**Comment by nicofrand** [comment]
My 2 cents : the error is triggered when you click on the button, not when on "beforeunload" or something like that, so way before any `will-navigate` event (you can even wait as long as you want between the error catch and the page reload).

**Comment by janodvarko** [comment]
I can still reproduce this problem. Cloned into https://bugzilla.mozilla.org/show_bug.cgi?id=1660984

We are moving our bug tracking into Bugzilla, so please report further bugs here:
https://bugzilla.mozilla.org/enter_bug.cgi?product=DevTools&component=Debugger

Thanks,
Honza
