### ISSUE TITLE
[Reps] re-enable skipped tests

### ISSUE THREAD

**Issue by jasonLaster** [firefox-devtools/debugger#6440]
![Screen Shot 2018-05-29 at 3.55.10 PM.png](https://shipusercontent.com/30ec655b97b647ced6b100046e14447e/Screen%20Shot%202018-05-29%20at%203.55.10%20PM.png)

**Comment by marcogallo566** [comment]
@jasonLaster There is the support for a lonely node, is there?
![d303b1df-d080-4c27-8117-7830bec417b2](https://user-images.githubusercontent.com/36955296/44647573-af14a600-a9de-11e8-835f-3cf6bcd846d5.jpg)

**Comment by janodvarko** [comment]
@nchevobbe is this still valid report? Should we close or clone?

**Comment by nchevobbe** [comment]
this is still an issue, so we should clone it

**Comment by janodvarko** [comment]
Cloned into: https://bugzilla.mozilla.org/show_bug.cgi?id=1695204
