### ISSUE TITLE
[Breakpoints] PrettyPrint & Original Source Weirdness

### ISSUE THREAD

**Issue by darkwing** [firefox-devtools/debugger#6473]
STR:

1.  Open TodoMVC's `app-view.js`
2.  Set a few breakpoints
3.  Pretty-print `app-view.js`
4.  For some reason the first breakpoint (in my case) representation in the Breakpoints sidebar gets transferred to the prettyprinted tab.

![breakpointyikes](https://user-images.githubusercontent.com/46655/40991381-40bd0e38-68b9-11e8-9ed3-a5f7c070a507.gif)

**Comment by darkwing** [comment]
I checked out 7f6157a4ec572e7ba5c692598cb53546c4a71ee9, the commit before the PureComponent didn't have this exact issue.

**Comment by jainsneha23** [comment]
/unclaim
As not getting time to look into this now

**Comment by darkwing** [comment]
This no longer happens.
