### ISSUE TITLE
Mangled React error stacks?

### ISSUE THREAD

**Issue by Anahkiasen** [firefox-devtools/debugger#6497]
Not sure how to report this, but since switching to Firefox I've noticed error stacks from errors happening in React are reported a bit mangled compared to how it used to be on Chrome. Example with a same error:

Firefox
![screen shot 2018-06-12 at 11 44 53](https://user-images.githubusercontent.com/1321596/41283139-197cc674-6e36-11e8-86ad-1401ea7c112f.png)

Chrome
![screen shot 2018-06-12 at 11 44 59](https://user-images.githubusercontent.com/1321596/41283140-19977492-6e36-11e8-89fb-348c5c03a551.png)

Is there anything I can do or enable to make this better, or is it something in the way the errors are thrown? Also should the links to the files be clickable here?

EDIT: Actually this seems to not even be a saga error but happening in redux-form validation so not sure why the stack would appear like this. Could it be because of a bug tracker SDK like Bugsnag and such?

**Comment by jasonLaster** [comment]
Thanks for sharing @Anahkiasen. Have you tried Firefox Nightly, I believe the console error stack has been improved quite a bit in the past couple of months.

CC @nchevobbe

**Comment by Anahkiasen** [comment]
I'm currently on the latest Dev Edition build, checked quickly in latest Nightly but output seems to be the same :/

**Comment by nchevobbe** [comment]
Hello @Anahkiasen ,
It looks like the library is using Error.stack (which is not standard and includes the error message in V8 but not in Firefox).
I'd love to have a way to experience this so I can dig a bit deeper.

**Comment by Anahkiasen** [comment]
Will try to make a small reproducible example when I get some time

**Comment by loganfsmyth** [comment]
Looks pretty old, gonna close but if this is still something you run into, please file an issue in Bugzilla.
