### ISSUE TITLE
[objectinspector] expanding an object with 50K keys is slow

### ISSUE THREAD

**Issue by jasonLaster** [firefox-devtools/debugger#6547]
STR:

1. go to http://localhost:8000/integration/examples/big-sourcemap.html
2. open debugger and browser toolbox
3. in BT add a breakpoint in firefox/commands.js#sendPausePoint
4. in debugger, add a breakpoint in bundle.js
5. when paused log `pausePoints` and try to expand the object

i got a prompt if i wanted to stop the script. By the way, when it rendered there wasn't any bucketing

![Screen Shot 2018-06-25 at 12.31.39 PM.png](https://shipusercontent.com/68ba368c2dfa8ba43ec0cccd72537a76/Screen%20Shot%202018-06-25%20at%2012.31.39%20PM.png)

**Comment by nchevobbe** [comment]
this is a known issue filed on bugzilla
