### ISSUE TITLE
Escaped backslash inside strings is rendered as double backslash


### ISSUE THREAD

**Issue by nchevobbe** [firefox-devtools/debugger#6577]
**Steps to reproduce**

1. Evaluate `"a=\\99"`

**Expected results**

Reps output `"a=\99"`

**Actual results**

Reps output `"a=\\99"`

**Comment by TheKK** [comment]
Hi, is this issue suitable for someone new to this project? 
If so I'd like to take this one and give it a try :)

**Comment by darkwing** [comment]
@TheKK I'd choose something that isn't `reps` related :)

**Comment by TheKK** [comment]
Got it, I'll find the other one.
Thanks!

**Comment by jaril** [comment]
I checked with the Reps demo app - this seems to have already been fixed and can be closed:

<img width="356" alt="Screen Shot 2019-03-27 at 10 20 51 AM" src="https://user-images.githubusercontent.com/15959269/55083541-15979a80-507a-11e9-9697-083e85015196.png">

**Comment by nchevobbe** [comment]
closing we want the string results to be able to be copied and re-evaluated straight-away
