### ISSUE TITLE
Consistent vertical rhythm in debugger panels

### ISSUE THREAD

**Issue by digitarald** [firefox-devtools/debugger#6631]
Did a quick analysis of line-heights in the side-panel. Turns out that we have a lot going on. I have not even started on font variations, this might be also considered as part of the issue.

My hypothesis is that cleaning this up a bit for a better design could make the information easier to scan.

![image](https://user-images.githubusercontent.com/8599/42604367-3aa7326e-8527-11e8-8591-1cd25e5ad750.png)

@violasong how far does https://design.firefox.com/photon/visuals/grid.html apply to devtools and could guide this? Or could this be used as case-study for a devtools-specific design system?

Edit: Updated image with grid lines and added font differences as an issue.

**Comment by violasong** [comment]
Just wanted to include the comments I wrote on Slack to keep things together :)
- one thing that will help is when we replace the blue background for current frame with an arrow icon as mentioned in the callstack PRD
- I think the difference in spacing between the three visible sections is distracting, esp call stack compared to scopes - they look like three separate worlds (lazy bug I filed about this, I can be more helpful later: https://github.com/devtools-html/debugger.html/issues/6091) 
- Do we need the bold text in the frames? Perhaps the breakpoints should be indented so the checkbox lines up with the file name. I really want to replace the dotted line focus ring with a different styling
- There's some vertical alignment polish that could be done across the sections/accordion headers - even just indenting the Scopes content seems like it would help

**Comment by digitarald** [comment]
@darkwing want to take a shot at it and try to tweak font styles and sizing to make the look a little more coherent? Not sure what will have the biggest impact here, but it seems like a set of low hanging design improvements.

cc @nchevobbe to be aware of reps and line heights consistency.

**Comment by violasong** [comment]
This arrow icon, horizontally flipped, could be used for current frame indicator
https://bugzilla.mozilla.org/show_bug.cgi?id=1479861#c7

Mockup: https://mozilla.invisionapp.com/share/N6K0U23U3ZP

**Comment by fvsch** [comment]
Would be happy to pick it up in the next week(s).

@violasong Do we have a guideline for alignment in the devtools? Things like toolbar height, item height, distance from edges? I believe we should use multiples of 4px as suggested in https://design.firefox.com/photon/visuals/grid.html

For the vertical rythm, Photon recommends 32px rows, but the DevTools seem to use smaller lines:
- 28px for the main tabs, and for some some toolbars (e.g. the Netmonitor's main toolbar)
- 24px for panel section headers, e.g. most headers or toolbars in the Inspector

In the Debugger, I’m seeing other vertical sizes:
- 21px or 21.5px for file rows in the left sidebar
- Code lines are 13.5px high (base font-size of 11px + `line-height:normal`, I’m wondering if that line-height:normal ends up depending on the font)
- And in the right sidebar I’m finding heights like 23px, 29px, and 31px (all excluding borders).

It would be great to have a more regular vertical rhythm, and given the precedent set by other DevTools part I would use multiples of 4px *excluding separating borders*. Maybe something like:

- 28px for the top row
- 24px for collapsible section headers ("Watch expressions", "Call stack", etc.)
- 20px for rows in "Sources" and "Outline" (left), "Watch expressions", "Breakpoints", "Call stack", "Scopes", etc.
- 14px for source code lines

For section content (with 20px rows), it might be a good idea to use some top and bottom padding, maybe 4px (this means a section content area with a single line would be 4 + 20 + 4 = 28px in total).

I’ve opened two other bugs for other parts of the UI:
- Top bar: #6803
- Sources/Outline content: #6804

**Comment by fvsch** [comment]
> 14px for source code lines

For the record, the Console uses `font-size:11px; line-height: 16px;` for code input.

Trying out a 16px line-height in the Debugger’s CodeMirror view, I quite like it. Works great with Menlo on mac. It does mean showing 12% fewer lines at a time, though.

**Comment by violasong** [comment]
Hi @fvsch!! Sorry for the delay in responding to this. This proposal and its diagrams are amazing! I mostly interact with these concepts in a very informal way, just eyeballing things visually and wanting a bit more space here or there, so I really appreciate this level of rigor ;___;. I can't wait to see how this would look for Debugger! And I do like the 4px vertical section padding :).

**Comment by fvsch** [comment]
@darkwing UX is finalized at https://github.com/devtools-html/ux/issues/45#issuecomment-457021260

Should this be broken up into individual issues for the different sections (aka panes)? Trying to do it all at once might be a bit too big.

**Comment by darkwing** [comment]
I think we've completed this! Wow, I'm so excited about this!
