### ISSUE TITLE
React Developer Tools Add-on does not work when debugger is paused

### ISSUE THREAD

**Issue by gerdneuman** [firefox-devtools/debugger#6684]
I see this in every React App: When debugger is paused on a breakpoint I cannot use the [React Developer Tools Add-on](https://reactjs.org/tutorial/tutorial.html#developer-tools)  (link to [AMO](https://addons.mozilla.org/en-US/firefox/addon/react-devtools/)). Since it works in Chrome I think it is an issue of Firefox Debugger (or its WebExtensions API) and not a problem of React Developer Tools. 

**Steps to reproduce:**
1. Go the the Vanilla React App at https://new.codesandbox.io/
2. Set a breakpoint and reload:
![image](https://user-images.githubusercontent.com/12525563/43129821-803ed418-8f35-11e8-9a26-9198e0f8a1c1.png)
3. Switch to React DevTools tab

Instead of Loading the React DevTools the following message `Connecting to React...` is shown forever and nothing happens:

![image](https://user-images.githubusercontent.com/12525563/43129925-bd5b8166-8f35-11e8-806b-b8ec3f4c34d0.png)

Disabling the breakpoint does not seem to help. To get the React Developer Tools working again, one needs to Reload (F5) the page. 

Setting a breakpoint to investigate and then investigating using React DevTools is a common use case for me. Not sure, maybe this is related to or caused by the general Firefox bug [Mouse selection to inspect elements doesn’t work when debugger is paused](https://bugzilla.mozilla.org/show_bug.cgi?id=1177346)

**Comment by jasonLaster** [comment]
Thanks for filing. That's really interesting. I believe they do a console eval every 30 seconds or so to initialize the devtools. Not sure why that wouldn't work here though.

**Comment by James-E-Adams** [comment]
I actually have the same experience on Chrome if I haven't already opened the React dev tools. If I want to use them whilst on a breakpoint, I have to make sure I've opened them at least once because I don't think they can initialise whilst on a breakpoint.

**Comment by janodvarko** [comment]
@gerdneuman: are you still experiencing this issue?

Note that Firefox Developer Tools (including Debugger tool) development is currently happening in Bugzilla and new issues should be reported here: https://bugzilla.mozilla.org/enter_bug.cgi?product=DevTools&component=Debugger

Could you please report again if it's still an issue, thank you!

Honza
