### ISSUE TITLE
[sources] Angular 2

### ISSUE THREAD

**Issue by jasonLaster** [firefox-devtools/debugger#6706]
Angular 2's todomvc's sources do not appear in the debugger. http://todomvc.com/examples/angular2/

I don't know if this is a systemjs thing, esmodule, or source maps...

STR  (added by @digitarald)
- Open Debugger on http://todomvc.com/examples/angular2/

AR: Application code isn't shown (e.g. `app.js`, `store.js`, etc)

<img width="256" alt="image" src="https://user-images.githubusercontent.com/8599/44870984-66f7bc80-ac46-11e8-85d3-36ab517c15cc.png">

Chrome:

<img width="225" alt="image" src="https://user-images.githubusercontent.com/8599/44871078-aaeac180-ac46-11e8-9182-cc05ac45866f.png">

**Comment by digitarald** [comment]
Same for react: http://todomvc.com/examples/react/ . Here JSX files are loaded live via JSXTransformer.js

**Comment by janodvarko** [comment]
I am not seeing clear STR for this issue. 

1) Load  http://todomvc.com/examples/angular2/
2) next?

@jasonLaster can you please provide it, thanks.

Honza

**Comment by janodvarko** [comment]
Thanks, I can easily see the problem on my machine now.
Honza

**Comment by janodvarko** [comment]
This is working for me now, I can see all, app.js, store.js, bootstrap.js (just like in Chrome)

We are moving our bug tracking into Bugzilla, so please report futher bugs here:
https://bugzilla.mozilla.org/enter_bug.cgi?product=DevTools&component=Debugger

Thanks,
Honza
