### ISSUE TITLE
[SourceTree] Blackbox files outside the Directory Root (Proposal)

### ISSUE THREAD

**Issue by digitarald** [firefox-devtools/debugger#6708]
Story: When I work in a specific part of my project, I want to focus on the code in one target directory and ignore other files, so that I debug only files I care about and nothing else.

Making directory root behave more focused, what would be the effort to blackbox all files outside of the current directory?

Would there be any trade-offs that we should be aware of?

**Comment by jasonLaster** [comment]
1. we could do this fairly easily for apps without sourcemaps
2. in some ways i prefer not to blackbox, because we have frame groups so it is nice to see the library group in the call stack
3. the only way you'd pause initially one of these other files is a breakpoint/debugger statement which seems unlikely
3.a. avoiding stepping into a library could be nice, but i'd have to see how that feels in practice.

**Comment by darkwing** [comment]
I've always taken the directory root feature to be more of a "don't visually distract me, in the tree, with files for which I don't care about right now", not as a blanket disable-all-the-other-things.  That said, we could add a blackbox icon in the directory root header, docked to the right, which would blackbox other things if it's really a desired feature.

**Comment by digitarald** [comment]
> in some ways i prefer not to blackbox, because we have frame groups so it is nice to see the library group in the call stack

The main purpose of callstack collapsing is reducing noise (by avoiding massively bloated callstacks). While having the libraries sprinkled in so you can see how everything is glued together, not having the additional entries there and only reasoning about your own code also has some advantages.

Is there a middle ground that would give us blackboxing behavior of not stepping/breaking in the ignored code but keeping the collapsed stacks visible in the callstack?

> the only way you'd pause initially one of these other files is a breakpoint/debugger statement which seems unlikely

Also pausing on error, clicking & pausing on event handlers that aren't traced back to user land, clicking on console logs.

> I've always taken the directory root feature to be more of a "don't visually distract me, in the tree, with files for which I don't care about right now", not as a blanket disable-all-the-other-things.

Sounds like an option would be nice with some sane defaults. It also sounds though that Firefox developers don't use blackboxing much, maybe due to the semi-working current state of the feature.

**Comment by digitarald** [comment]
Started a poll: https://twitter.com/FirefoxDevTools/status/1029432334179651584

**Comment by digitarald** [comment]
@jimblandy maybe you could help shine some light on:

> Is there a middle ground that would give us blackboxing behavior of not stepping/breaking in the ignored code but keeping the collapsed stacks visible in the callstack?

**Comment by digitarald** [comment]
Continued in https://bugzilla.mozilla.org/show_bug.cgi?id=1608312
