### ISSUE TITLE
Search highlight creates multiple blocks for same search term

### ISSUE THREAD

**Issue by digitarald** [firefox-devtools/debugger#6744]
STR:
- https://bl.ocks.org/ColinEberhardt/raw/6ceb7ca74aabac9c8534d7120d31b382/
- Open js file
- Search for `wasm.`

AR: Search highlights `wasm` and `.` as separate boxes. Gets worse for `wasm.s`, creating 3 boxes.

<img width="240" alt="screenshot 2018-08-03 13 17 17" src="https://user-images.githubusercontent.com/8599/43663788-90c56aa8-971f-11e8-9f0c-a30883d5258a.PNG">

**Comment by jasonLaster** [comment]
Hey @bomsy do you remember the details here?

**Comment by darkwing** [comment]
Quick ping here @bomsy; do you have more additional information here?

**Comment by kenjiO** [comment]
#1629 and #3885 are related.  When I was looking into this I also found #6896 which may be caused by the same code.

**Comment by kenjiO** [comment]
@jasonLaster if codeMirror is going to be replaced by Monaco then you might want to put this issue on hold or close it.

**Comment by bomsy** [comment]
sorry just seeing this ping! will take a quick look.

**Comment by Lathaguna** [comment]
/claim

Hello @darkwing , 

I am an Outreachy applicant. I would like to attempt resolving this issue. Let me please claim the issue as I see contributors doing it on the other issues.

Thanks.

**Comment by aditya81070** [comment]
@Lathaguna Are you still working on this issue?

**Comment by darkwing** [comment]
@violasong @mcroud  Could we use Firefox's green background highlight in the debugger instead of trying to search matches?  It would make life so much easier.  Also, what green color is this?

**Comment by fvsch** [comment]
As a side note, I'm not sure how the Debugger's CSS is built, but there is a bit of duplication. The search highlight styles are defined (identically) in 2 different style sheets.

<img width="458" alt="screenshot" src="https://user-images.githubusercontent.com/243601/49724777-67065000-fc6a-11e8-9631-10bc68d887fe.png">

**Comment by jasonLaster** [comment]
@aditya81070  how's it going? are you still interested in this?

**Comment by baronKilljoy** [comment]
/claim 
I work on this, if its ok.

**Comment by baronKilljoy** [comment]
@jasonLaster  I think this is a codemirror issue. it looks like when it hits a special character (punctuation space etc) it is creating a new span. The only thing i found that changes the search is 
`function escapeRegExp(string) {
  string = toString(string);
  return (string && reHasRegExpChar.test(string))
    ? string.replace(reRegExpChar, '\\$&')
    : string;
}`
changes wasm. to wasm\\. which I guess is needed for regexp. I will be out of town next couple days but will be back to check this tuesday or wendsday.

**Comment by darkwing** [comment]
This PR is a great start:  https://github.com/devtools-html/debugger.html/issues/6744

Once UX has approved a new look (https://github.com/devtools-html/ux/issues/14), we can move forward 👍

**Comment by fvsch** [comment]
@darkwing Do we still have this issue in Debugger, and do we have a bug on Bugzilla maybe?

We reached a decision in https://github.com/firefox-devtools/ux/issues/14#issuecomment-537047482 and are going to implement it with 3 theme variables (2 already landed, one to be done)

A quick try in Debugger gives me:
![Screen Shot 2019-10-02 at 01 18 09](https://user-images.githubusercontent.com/243601/66007739-d5dfbe80-e4b3-11e9-9694-536802fe7cd2.png)

The main issue is that we need a style variation to highlight the currently focused result (vs other results in the same document). I tried a few things but wasn't happy with the results.

**Comment by darkwing** [comment]
@fvsch Nice!  An amazing contributor, Janelle, fixed this issue of multiple blocks in MC.  In theory, implementing this new highlighting appearance should be really easy now.

**Comment by darkwing** [comment]
https://phabricator.services.mozilla.com/D45015 might come into play, but I think your highlight is ready or implementation.

**Comment by janodvarko** [comment]
I can't reproduce this issue.

Firefox Developer Tools (including Debugger tool) development is now entirely happening in Bugzilla and new issues should be reported here: https://bugzilla.mozilla.org/enter_bug.cgi?product=DevTools&component=Debugger

Please reopen this report in Bugzilla if it's still valid.

Honza
