### ISSUE TITLE
[OriginalLanguages] Create React App doesn't offer a full source map experience

### ISSUE THREAD

**Issue by digitarald** [firefox-devtools/debugger#6762]
https://firefox-debugger-example-create-react-app.glitch.me/

<img width="1002" alt="image" src="https://user-images.githubusercontent.com/8599/43696888-1a3d986a-98f5-11e8-8efa-6060e8d42bd1.png">

- [x] Callstack collapsing works
- [ ] Variables are not mapped
- [ ] JS files are not stacked in `webpack://`, just CSS files
- [ ] `App.js` is paused in `render` but callframe is folded under React's `render` collapsing (due to project name?)

Miscellaneous:

- `.css` files contain JS but are not syntax highlighted

<img width="571" alt="image" src="https://user-images.githubusercontent.com/8599/43696954-8fd237de-98f5-11e8-98e0-18c4016b2c31.png">

**Comment by jasonLaster** [comment]
here's a local github version https://github.com/jasonLaster/tic-tac-toe. Note, i also updated babel to babel 7...

**Comment by loganfsmyth** [comment]
I don't think there's anything left to do in this.
