### ISSUE TITLE
[Breakpoints] Use `loading` property

### ISSUE THREAD

**Issue by darkwing** [firefox-devtools/debugger#6771]
At present the Breakpoint object has a `loading` property but it doesn't appear we're actually using it anywhere; i.e. it default to false and never changes.

Ideally we default the value to `true` and then set to `false` when the server returns successful breakpoint syncing.

Once this is working properly, we can update `breakpointSources.js`'s `getBreakpointsForSource` function to check for `!bp.loading` to determine if the breakpoint should display.

**Comment by jaikathuria** [comment]
Maybe, I have solved the first part of the issue. Now by the default value for loading will be `true` and then `false` when the `addBreakpointPromise` promise completes i.e. the server returns successful breakpoint syncing.

<img width="508" alt="screen shot 2018-08-11 at 12 29 56 am" src="https://user-images.githubusercontent.com/13422807/43976922-0cb13710-9d00-11e8-9d85-ad7bd4057b1e.png">


@darkwing please have a look at it and let me know if I am going right!

**Comment by jasonLaster** [comment]
@jaikathuria  are you still interested in working on this?

**Comment by Art-Vanderlay** [comment]
@jasonLaster I'll look into this one if @jaikathuria isn't working on this anymore. What else needs to be done here?

**Comment by jasonLaster** [comment]
Go for it. Here's a PR with the latest attempt. 

https://github.com/devtools-html/debugger.html/pull/6857
