### ISSUE TITLE
[scopes] Improve Variable Mapping UI

### ISSUE THREAD

**Issue by jasonLaster** [firefox-devtools/debugger#6820]
Tools like CRA use line-based mappings. We should detect it and notify the user that they should change their source map mode to something else for better variables 

Looks like create react app is having some issues with the mappings:
https://github.com/devtools-html/debugger.html/issues/6762

---

This was caused by create-react-app using cheap-module-source-map, which has inline source maps. We can do 2 things:

1) detect in the sm-worker that it is 100% line mappings and not try
2) tell the user to change their source map strategy
3) see if CRA can choose a different mapping

**Comment by jasonLaster** [comment]
Here is a [gist][g] of how to implement it. I'm currently stuck on the design and copy

[g]: https://gist.github.com/jasonLaster/67fb8be47dce83cb4f5e1426194cd9cc

**Comment by jasonLaster** [comment]
we'll now track two things here:

1. the error message
2. improvements to how we show the mappings

**Comment by janodvarko** [comment]
Not on our roadmap, closing.

Firefox Developer Tools (including Debugger tool) development is now entirely happening in Bugzilla and new issues should be reported here: https://bugzilla.mozilla.org/enter_bug.cgi?product=DevTools&component=Debugger

Honza
