### ISSUE TITLE
Discussion: Coherent labeling for mapped files

### ISSUE THREAD

**Issue by digitarald** [firefox-devtools/debugger#6824]
#5663 landed labels for source mapped files, with some discussion around how to mark them. Following Chrome's decision for now, using `[sm]` doesn't seem ideal and we can do better.

The labeling needs to be used in the source pane and source tabs. It should probably be used in other source mapped interfaces (can be toggled between generated/original), like callstacks and variable view.

Proposals:

1. Subtle superscript-like `mapped` or `original`/`orig` label
2. Something-map 🗺 icon

As we tend to use too many invented-here icons, I am biased towards preferring 1st option.

Thoughts?

**Comment by digitarald** [comment]
Thanks for the quick fix, @darkwing . I re-open this to get some more input on what options we should consider for a final label copy and style.

**Comment by darkwing** [comment]
My two cents is I would love to find a representative map icon or something so that we don't need to add "(mapped)" everywhere, especially tabs where it feels like we may be short on space.

**Comment by loganfsmyth** [comment]
Moving to https://bugzilla.mozilla.org/show_bug.cgi?id=1651777
