### ISSUE TITLE
debugger shows partial code for the main page

### ISSUE THREAD

**Issue by karlcow** [firefox-devtools/debugger#6831]
Steps to reproduce

1. Open Firefox Dev Edition (62.0b17 (64-bit)) or Nightly (63.0a1 (2018-08-14) (64-bit))
2. Open responsive design mode. 
3. Select Firefox Android UA with touch and DPR2 and 320x640px (create it if you do not have it)
4. Open https://www.appmatch.com/ask
5. Start the debugger 
6. Click on the left column `www.appmatch.com` -> ask

Actual:
* Only one script element is being displayed.
* `<script> localStorage.setItem("home_open_popup", true); </script>`

Expected:
Display the content of the `/ask` URI.

Here on Nightly.
<img width="1027" alt="capture d ecran 2018-08-15 a 09 57 54" src="https://user-images.githubusercontent.com/505230/44126189-b7940954-a071-11e8-8b73-7fbf245d8493.png">

---
Trying with the WebIDE directly on the device. (Maybe a different issue)
This time the content is being displayed
<img width="1134" alt="capture d ecran 2018-08-15 a 10 06 06" src="https://user-images.githubusercontent.com/505230/44126374-e32c0912-a072-11e8-8a6c-ac482f1d8355.png">

BUT it's impossible to put a breaking point on any parts, for example, of `function placeCaretAtEnd(el)`.

**Comment by loganfsmyth** [comment]
This no longer reproduces because the site is dead. I'm gonna guess this works now though, at least on Nightly if not more broadly.
