### ISSUE TITLE
Source map issues in react-typescript-component-starter-kit

### ISSUE THREAD

**Issue by digitarald** [firefox-devtools/debugger#6840]
STR:
- Open https://react-typescript-component-starter-kit.now.sh/
- Set breakpoint in `Button.tsx`'s `Button` component

ER: Breakpoint doesn't stick.

![screenflow](https://user-images.githubusercontent.com/8599/44238807-19ba1c00-a16b-11e8-97bf-14fa61eb9ffe.gif)

Bonus ER: 2 bootstrap files, both clickable but only one opens file.

Chrome disables all lines except 4 and 64:

<img width="85" alt="image" src="https://user-images.githubusercontent.com/8599/44238939-a2d15300-a16b-11e8-9f45-8b4e44e1ab20.png">

**Comment by jasonLaster** [comment]
hmm, will look into this soon. 

The multiple bootstrap problem is an interesting one. I think it warrants its own issue

**Comment by andreicristianpetcu** [comment]
Is there some workaround for this? :cry:

**Comment by andreicristianpetcu** [comment]
Am I having the same issue here or is it something else?
![image](https://user-images.githubusercontent.com/922368/83262570-e58be000-a1c5-11ea-94a1-8161c2fb10f9.png)

Would it be hard to implement for somebody that has little expreience with the debugger?

**Comment by jasonLaster** [comment]
Hmm, i'm not sure. Could you try this on Firefox Nightly? Also, i wonder why the syntax highlighting is so busted.

**Comment by andreicristianpetcu** [comment]
That is Nightly. Also Chrome is busted the same way.

**Comment by andreicristianpetcu** [comment]
I was using an old Chrome version. It works fine in Chrome.
I'm interested in working on this if anybody has some pointers. Maybe in a week or so, once I finish up the tasks I'm working on in about:logins :smile:

**Comment by janodvarko** [comment]
The original test case is not available anymore.

Firefox Developer Tools (including Debugger tool) development is now entirely happening in Bugzilla and new issues should be reported here: https://bugzilla.mozilla.org/enter_bug.cgi?product=DevTools&component=Debugger

Please reopen this report in Bugzilla if it's still valid.

Honza
