### ISSUE TITLE
Many debugger interactions overpaint

### ISSUE THREAD

**Issue by digitarald** [firefox-devtools/debugger#6842]
Overpainting not only affects the toolbox but even the browser tabbar.

https://www.dropbox.com/s/82yokxk4i99sefd/debugger-63-paint-flashing.mp4?dl=0

Cases that paint too much:

- Opening folder in sources
- Opening file
- Focusing source pane
- Scrolling source pane
- Setting breakpoints
- Checking checkboxes

[CSS Containment](https://developer.mozilla.org/en-US/docs/Web/CSS/contain) is landing in 64 and should be used in some of those cases, probably being applied per debugger panel while testing for side effects.

**Comment by janodvarko** [comment]
Cloned into: https://bugzilla.mozilla.org/show_bug.cgi?id=1695207

Firefox Developer Tools (including Debugger tool) development is now entirely happening in Bugzilla and new issues should be reported here: https://bugzilla.mozilla.org/enter_bug.cgi?product=DevTools&component=Debugger

Honza
