### ISSUE TITLE
[intermittent] dbg-quick-open

### ISSUE THREAD

**Issue by jasonLaster** [firefox-devtools/debugger#6874]
cc: [bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1438778)

I just tried to reproduce locally and couldn't but I can see where it is happening and will investigate soon

by the way, it was introduced in 84 i believe - [log]

```diff
diff --git a/src/test/mochitest/browser_dbg-quick-open.js b/src/test/mochitest/browser_dbg-quick-open.js
index 2807c90..062aa59 100644
--- a/src/test/mochitest/browser_dbg-quick-open.js
+++ b/src/test/mochitest/browser_dbg-quick-open.js
@@ -65,6 +65,10 @@ add_task(async function() {
   await waitForSource(dbg, "switching-01");
   quickOpen(dbg, "sw");
   pressKey(dbg, "Enter");
+
+  // it fails to open this source.. i wonder if it is one of two things
+  // 1. it tries to select that source and doesnt load
+  // 2. it tries to select switching-02
   await waitForSelectedSource(dbg, "switching-01");

   info("Arrow keys and check to see if source is selected");
(END)
```
[log]:  https://treeherder.mozilla.org/intermittent-failures.html#/bugdetails?startday=2018-08-16&endday=2018-08-23&tree=trunk&bug=1438778

**Comment by darkwing** [comment]
Intermittents for this file are tracked here:  https://bugzilla.mozilla.org/show_bug.cgi?id=1632803
