### ISSUE TITLE
ObjectInspector expanded node could be more useful

### ISSUE THREAD

**Issue by nchevobbe** [firefox-devtools/debugger#6893]
In [Bug 1486381](https://bugzilla.mozilla.org/show_bug.cgi?id=1486381), @fvsch suggest that the way we represent expanded ObjectInspector nodes is not the best.

Currently, the nodes are being rendered in `TINY` mode, but we could introduce a new `expanded` prop to use in Reps.

So instead of having an object rendered as

```
▼ { … }
|   a: 1
|   b: 2
|   <prototype>
```

It could be 

```
▼ Object {
|   a: 1
|   b: 2
|   <prototype>
}
```
or at least

```
▼ Object
|   a: 1
|   b: 2
|   <prototype>
```
if we don't want to deal with opening and closing brackets.

**Comment by marcogallo566** [comment]
@nchevobbe This is a little preview (it works only with grips, I'll finish my work soon):
![dpwqvbhfo2](https://user-images.githubusercontent.com/36955296/45866239-67383300-bd80-11e8-8833-0bb6d441f7fe.gif)

Is it how you thought it?
I prefer without the brackets, it's more clean.

**Comment by nchevobbe** [comment]
looks good to me :)
We then need to make sure to not lose the type of the expanded node. For a simple object, that's fine.
But for arrays, windows, nodes, … we still need to display something IMO.

**Comment by nchevobbe** [comment]
closing as we already have bug 1486381
