### ISSUE TITLE
Pausing on exception can miss scopes

### ISSUE THREAD

**Issue by digitarald** [firefox-devtools/debugger#6895]
STR:
- Open https://partner.android.com/things/console/ (filed as https://webcompat.com/issues/18503)
- Open Debugger and Pause on Exception

ER: See callstack and scopes
AR: Callstack is shown with only one entry (probably async), but Scopes is empty until the callstack entry is clicked again.

![image](https://user-images.githubusercontent.com/8599/44736950-84415500-aaa5-11e8-9a19-c17d07a4561b.png)

Bonus bug: Pausing does not use the prettified version.

**Comment by janodvarko** [comment]
@digitarald: I can't load the original page, can you still repro this?
Worth cloning into Bugzilla?

Honza
