### ISSUE TITLE
Breaking on exception even if option is off

### ISSUE THREAD

**Issue by digitarald** [firefox-devtools/debugger#6915]
P1 as this might affect other users and makes using devtools impossible.

STR (not sure how I got there):
- Open cnn.com
- Open Debugger
- Enable `Pause on exception` & `Pause on uncaught exception`
- Reload
- Pauses on exception somewhere …
- Disable `Pause on exception`
- Reload

AR: Pauses again on exception
ER: No pausing

Worked as expected after closing/reopening toolbox.

**Comment by janodvarko** [comment]
I can't reproduce this. Anybody else can?

Honza

**Comment by AnshulMalik** [comment]
Can't reproduce it either.

**Comment by digitarald** [comment]
Tested with a fresh profile. I updated the STR with more details.

![screenflow](https://user-images.githubusercontent.com/8599/50624724-d1ac5380-0ed7-11e9-90fb-c8f95450d5b5.gif)

**Comment by darkwing** [comment]
I was able to reproduce this with the steps provided in Firefox Nightly.

**Comment by darkwing** [comment]
I took a quick look at this and it's definitely a server bug ; I can see the correct values being passed from the client upon change and each opening of the debugger.

**Comment by jasonLaster** [comment]
https://gist.github.com/9f20b62f1b7d14798d9ecda8ad72f3d7

**Comment by janodvarko** [comment]
I can reproduce this issue, cloned into Bugzilla.
https://bugzilla.mozilla.org/show_bug.cgi?id=1603423

Honza
