### ISSUE TITLE
[Pretty Print] Pretty print feature suggestions from Bug 1488654

### ISSUE THREAD

**Issue by juliandescottes** [firefox-devtools/debugger#6947]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1488654
Forwarding from bugzilla, feel free to split more.

- [ ] add feature to always pretty print
- [ ] add feature to hide original file if pretty printed version exists
 
cc @birtles

**Comment by loganfsmyth** [comment]
Closing in favor of Bugzilla
