### ISSUE TITLE
Stepping can take you from original to generated code when next step has no original mapping

### ISSUE THREAD

**Issue by yurydelendik** [firefox-devtools/debugger#6949]
STR:

* Open https://yurydelendik.github.io/old-man-sandbox/fibwjs/fib2.html
* In debugger, all source tabs are closed and breakpoints removed (if not, close/remove and refresh)
* Open "fib2.c" source
* Add breakpoint at line 3
* Refresh the debuggee page
* <ins>Hit step over several times</ins>

Actual result: debugger paused at and showed the generated source ("fib2.js")

Expected result: debugger shows the original source

**Comment by janodvarko** [comment]
Thanks for the report Yury! I can reproduce the problem using provided STR.

I am also seeing other issues reproducible with this test case:

1) When the generated source is displayed (fib2.js) after stepping - open the context menu on the current line and pick "jump to original location".  Nothing happens. The generated source is still displayed.

2) When creating a breakpoint on line 3 in (fib2.c) and switching to file fib2.js (using the Sources tree) - I still see a breakpoint on line 3

Honza

**Comment by loganfsmyth** [comment]
The core question here is, what should we do when you step, and the location you step to has no mappings? This primarily happens in 2 ways:

* The tool injected code that doesn't conceptually map anywhere (https://github.com/devtools-html/debugger.html/issues/7007#issuecomment-423697796).
* The tool generating the map did a poor job, so lots of code that _could_ map to something, doesn't (as is the case here).

Here are the mappings of this file:
![screen shot 2018-10-11 at 6 38 00 pm](https://user-images.githubusercontent.com/132260/46843150-3bf4a280-cd86-11e8-9927-7cd7e18b4c8d.png)

The black line is the one that you start at, when following Yury's steps. If you hit Step currently, you end up at `wasm2js_i32$1 = var$4;`, the next line, which does not map anywhere in the original code.

**Comment by loganfsmyth** [comment]
Ranges on the generated output file can have an explicit end, or else they automatically stop at the end of the generated line.

**Comment by yurydelendik** [comment]
FWIW chrome has no such issue, so I wonder if there is a problem how source maps behave in relation of original/generated source line break handing in the browsers

**Comment by loganfsmyth** [comment]
For the record, since I had to double-check myself, this is bailing out on https://github.com/mozilla/source-map/blob/7356bcbc56565beac748f8bddcf3bc3151f2c798/lib/source-map-consumer.js#L496. SpiderMonkey has stepped to the next line, but then when it searches, the only mapping it finds is on the previous line, so it skips it.

Looking at `source-map` this seems to be been a purposeful change introduced in https://github.com/mozilla/source-map/commit/699dff1a707e4ce8845f267668215bbf79d8eacd

So I think I'd consider this Chrome allowing unexpected behavior potentially?

**Comment by janodvarko** [comment]
@yurydelendik Firefox Developer Tools (including Debugger tool) development is now entirely happening in Bugzilla and new issues should be reported here: https://bugzilla.mozilla.org/enter_bug.cgi?product=DevTools&component=Debugger

Please reopen this report in Bugzilla if it's still valid.

Honza
