### ISSUE TITLE
Add a worker list and unregister for PWA (and other workers)

### ISSUE THREAD

**Issue by Eccenux** [firefox-devtools/debugger#6950]
Adding an easy way to clear workers would help a lot in testing PWA. I know unregisterging is available from the workers pages but it only works when the list is short. Searching throught it and checking which one applies to the page you are developing is time consuming.

So. This is a code that lets you unregister all instances of a Service worker for current site/page.
```js
navigator.serviceWorker.getRegistrations().then(function(registrations) {
        for (var index = 0; index < registrations.length; index++) {
            var registration = registrations[index];
            registration.unregister();
        }
});
```

The list and option to unregister could be added to the Data tab (were we can already clear `caches` object). On the workers list the values could be:

1. Scope (`registration.scope`) 
2. Script URL (`registration.active.scriptURL`). As `active` can be null that would have to be something like: `registration.active ? registration.active.scriptURL : ''`
3. State (`registration.active.state`). And again as `active` can be null that would have to be something like: `registration.active ? registration.active.state : 'inactive'`.

See also:
https://developer.mozilla.org/en-US/docs/Web/API/ServiceWorkerRegistration

**Comment by janodvarko** [comment]
Cloned into https://bugzilla.mozilla.org/show_bug.cgi?id=1695209

Firefox Developer Tools (including Debugger tool) development is now entirely happening in Bugzilla and new issues should be reported here: https://bugzilla.mozilla.org/enter_bug.cgi?product=DevTools&component=Debugger

Honza
