### ISSUE TITLE
"open custom element" into the debugger does not allow code formatting

### ISSUE THREAD

**Issue by staabm** [firefox-devtools/debugger#6956]
when opening a website which includes a custom element, clicking the "custom.." button in the inspector panel opens the corresponding source in the debugger panel.

this source is a javscript file which in production environments is often minified.

ER
the "Eye" button to format the minified source should be available

AR
No button appears

STR
- open https://github.com/ while beeing logged in
- inspect one of the "3 hours ago" components
- click on the "custom.." button
![grafik](https://user-images.githubusercontent.com/120441/45297940-444b8a80-b507-11e8-8a1d-fbfd898aa674.png)
- look for the "format source" button, which is missing
![grafik](https://user-images.githubusercontent.com/120441/45297968-5a594b00-b507-11e8-88c9-d68e7c5cabd3.png)

tested using FF 64.0a1 (2018-09-09) (64-Bit) on Win10x64

**Comment by ZhangYue-vhyt** [comment]
Right-click the tab, "Pretty print source" is displayed and works well. I guess this is a UI only issue.

**Comment by darkwing** [comment]
@loganfsmyth Can you weigh in on this?  I tried the STR and I agree with Kenji (we don't show the pretty button when a source map is present)...shouldn't this source be pretty because a map is present?

**Comment by staabm** [comment]
I agree that when the source would be properly formatted, I wouldnt miss the button :-)

**Comment by loganfsmyth** [comment]
This should be working now, at least on Nightly if not more.
