### ISSUE TITLE
[wasm] Callstack frame coming from WASM doesn't use function name

### ISSUE THREAD

**Issue by janodvarko** [firefox-devtools/debugger#6959]
STR:

1) Load http://janodvarko.cz/test/wasm/basic1/
2) Press `Load Module & Execute Exported Function` button
3) Go to the debugger and select test.wasm file
4) Create a breakpoint at offset 26 (`get_local $var0`)
5) Press `Execute Exported Function` button
6) The breakpoint should hit
7) Check out the Call stack side-panel. I shows `(wasmcall)` instead of `addTwo` (the function name) -> BUG

![image](https://user-images.githubusercontent.com/37785/45362832-2dc03480-b5d6-11e8-9b88-a05e8eb9780e.png)

You can also see the the "addTwo" is in the wasmt file as well as in the binary info.

![image](https://user-images.githubusercontent.com/37785/45362912-69f39500-b5d6-11e8-95bc-f7bcf84e045b.png)

Honza

**Comment by bomsy** [comment]
Investigate this a little bit ... looks like might need some server work.

**Comment by janodvarko** [comment]
Works for me now.

Honza
