### ISSUE TITLE
[Scopes] support disabling original languages

### ISSUE THREAD

**Issue by jasonLaster** [firefox-devtools/debugger#6989]
I think it would be helpful to be able to enable/disable original languages in the devtools settings pane. This is similar to being able to toggle source map support. 

1. some people might not like it
2. the feature might not work for a build tool

**Comment by janodvarko** [comment]
Firefox Developer Tools (including Debugger tool) development is now entirely happening in Bugzilla and new issues should be reported here: https://bugzilla.mozilla.org/enter_bug.cgi?product=DevTools&component=Debugger

Please reopen this report in Bugzilla if it's still valid.

Honza
