### ISSUE TITLE
Logged errors are not source mapped

### ISSUE THREAD

**Issue by digitarald** [firefox-devtools/debugger#7007]
Reporting for the Spoke team

STR

1. $ curl -L -o spoke.zip https://github.com/MozillaReality/Spoke/archive/e24728d97506f335788fcdd90f19cbf3ce9d8864.zip
2. $ unzip -d spoke spoke.zip
3. $ cd spoke/Spoke-e24728d97506f335788fcdd90f19cbf3ce9d8864/
4. $ npm ci
5. $ npm run dev:http
6. Wait for "Compiled successfully"
7. Open http://localhost:9090/ in Nightly
8. Copy this url: https://poly.google.com/view/2s0cpvWShgk
9. Click on the big blue plus button in the bottom right
10. Click on the Model button
11. Paste the URL into the text box
12. Click on Add

1st AR: Error stack isn't source mapped (main issue reported)

![image](https://user-images.githubusercontent.com/8599/45908514-d2e6c400-bdb1-11e8-9f36-0bd253243f1b.png)

vs Chrome

![image](https://user-images.githubusercontent.com/8599/45908814-4f2dd700-bdb3-11e8-95bb-211c52025f56.png)

2nd AR: Pausing on uncaught exception shows broken source mapped call stack

![screen recording firefox nightly](https://user-images.githubusercontent.com/8599/45908772-10981c80-bdb3-11e8-899b-44ab859983fa.gif)

vs Chrome

![image](https://user-images.githubusercontent.com/8599/45908841-74bae080-bdb3-11e8-9e90-7b519ae2d43f.png)

3rd AR: Switching to `app.js` takes 2+sec. Profile shows a massive reflow: https://perfht.ml/2NYF4L0

**Comment by digitarald** [comment]
@nchevobbe is the first issue already part of the callstack work and captured in existing bugs?

@loganfsmyth is there something in Spoke that makes Firefox not use the source maps as expected?

**Comment by loganfsmyth** [comment]
The issue with `step` there is that it is a utility function and doesn't really have a useful location in `Editor.js`, so it's not obvious what should show up. If you click `step` in Chrome, it takes you to an nonsensical location:
<img width="984" alt="screen shot 2018-09-21 at 4 41 34 pm" src="https://user-images.githubusercontent.com/132260/45910355-3de9c800-bdbd-11e8-9d91-4496c4eb04bc.png">

Chrome is probably taking to closest location in the original file, but it's not clear that it's a useful thing to do.

**Comment by brianpeiris** [comment]
Spoke dev here. I don't care so much about the `step` functions, but I'd expect Firefox to do as well as Chrome for the `updateComponentProperty` function and the two "(anonymous)" functions that do actually have correctly mapped line numbers.

**Comment by nchevobbe** [comment]
I can't get the error anymore, but we do sourcemap error object in console now.
