### ISSUE TITLE
[feature] Being able to step out of a loop when there are breakpoints.

### ISSUE THREAD

**Issue by karlcow** [firefox-devtools/debugger#7048]
Let's see a pseudo code example but this is happening to me often when diagnosing :)

```js
// breakpoint here on foo.
var foo = function2(something)
// foo is an array containing 100 elements.
foo.each(function(foo) {

    var blah = outside_fn(foo)

})
lol.where_I_want_to_be()


function outside_fn(bar) {
    // function with a breakpoint in there
    var breakit = bar;
}
```

There are **two** breakpoints in this code. One before `foo.each()` and one in a function nested in the loop. The code stops at the first breakpoint I continue the step by step and I enter the `each` loop.
After a couple of next step, I realize that the `foo` array is like a giant list. So I want to "step out" of the loop. 

Because there is a breakpoint in  `outside_fn()` the step out will loop to the next item and break again. 

One way to go out of this is to set a breakpoint on `lol.where_I_want_to_be()` and to remove the breakpoint on the `outside_fn()` to be able to pursue the path. It's not very user friendly and requires a bit of mental gymnastics for remembering once you need to redo a round. 

## The desire
(probably unconventional for most devs)
Having the possibility to do a "step out and ignore breakpoints in the nested context". Aka put me just after the next step (mimicking what I had to do by hand, but without unticking the breakpoints.)

 @miketaylr @digitarald list of my painful points/wishlist ;)

**Comment by nchevobbe** [comment]
Made a glitch for the example: https://leaf-flare.glitch.me/

```js
  var foo = Array.from({length: 100}, (_, i) => i);
  console.log(foo);
  foo = foo.map(function(i) {
    return mult(i, i)
  });

  console.log("DONE", foo);

  function mult(a, b) {
    const res = a * b;
    // add breakpoint here
    return res;
  }
```

I was thinking "continue to here" on the `DONE` console.log would work, but no, it stills pauses at the breakpoint in `mult`.

**Comment by jasonLaster** [comment]
I think giving "continue to here" special powers would be neat. It would be possible to disable all but one breakpoint on the server-side. 

I like the idea of a new-type of step out that is a guaranteed exit, but i'm not sure how to tell that story in the UI. 

Actually one way to do it, which might be interesting is with jump locations. Typically, jump locations are nearby function calls that you can cmd+click to jump to. It's basically "continue to here", but for column breakpoints. Another type of jump location could be the exit of a function. Maybe we show a marker at the bottom of the function and if the user clicks it they leave the function without pausing at any other breakpoints...

**Comment by janodvarko** [comment]
Cloned into https://bugzilla.mozilla.org/show_bug.cgi?id=1695217

Firefox Developer Tools (including Debugger tool) development is now entirely happening in Bugzilla and new issues should be reported here: https://bugzilla.mozilla.org/enter_bug.cgi?product=DevTools&component=Debugger

Honza
