### ISSUE TITLE
6 hang from CodeMirror when hitting breakpoint during loading

### ISSUE THREAD

**Issue by digitarald** [firefox-devtools/debugger#7134]
STR:
- Open https://perfht.ml/2SaZyPD
- Hit Pause in the debugger during loading (hits an extension script for me)

AR: 6s beachball.

Profile: https://perfht.ml/2SaZyPD
<img width="927" alt="image" src="https://user-images.githubusercontent.com/8599/47308085-7e6b7a00-d5e5-11e8-98b6-36e6936c96ea.png">
Time is spent in Codemirror `.column`.
 
Can not reproduce on DevEdition. `column` doesn't even show up: https://perfht.ml/2yUPaml .Might be either a regression or issue with extensions in my Nightly profile.

Loading just the files by clicking does not cause any hangs and feels instant. How is code mirror execution different from pausing to opening files?

**Comment by loganfsmyth** [comment]
Did you link the wrong repro URL, or is this reproducible on its own profile page?

Looks like the `z` function in this context is https://github.com/codemirror/CodeMirror/blob/ed8dfeb5e2ed25b5dd1f1eccc7b757ca6dbd118d/src/util/misc.js#L16 called from https://github.com/codemirror/CodeMirror/blob/ed8dfeb5e2ed25b5dd1f1eccc7b757ca6dbd118d/src/util/StringStream.js#L48 Nothing obviously bad about them.

**Comment by digitarald** [comment]
Looks like its pausing in LastPass. When I blackbox the lastpass script, it doesn't pause.

I uploaded the file `moz-extension://b89232ee-72dc-d946-81bc-256ca88530f7/onloadwff.js` gist as [reference](https://gist.github.com/digitarald/40e098d1edba82a0f8f51628113df725).

Here comes the kicker: codemirror-based syntax highlithing for gist.github.com shows the same hang, also 6s, when trying to preview the file: https://perfht.ml/2SaDB39

The only obvious pattern in `onloadwff.js` is a massively long minified line. Might this lead to the over-use of `.column`?

**Comment by darkwing** [comment]
I'm willing to bet this hang is due to our adding a billion column breakpoint markers.  We've since (1) pref'd off column breakpoints and (2) only present column breakpoints for items in viewport.  I'm betting this no longer occurs.

**Comment by digitarald** [comment]
First try:

```
 Error: "Connection closed, pending request to server1.conn4.child1/workerTarget164, type connect failed

Request stack:
request@resource://devtools/shared/protocol.js:1415:14
generateRequestMethods/</frontProto[name]@resource://devtools/shared/protocol.js:1539:14
attach@resource://devtools/shared/fronts/targets/worker.js:63:35
async*updateWorkerClients@resource://devtools/client/debugger/new/src/client/firefox/workers.js:31:11
async*fetchWorkers@resource://devtools/client/debugger/new/src/client/firefox/commands.js:354:28
async*updateWorkers/<@resource://devtools/client/debugger/new/src/actions/debuggee.js:16:27
async*thunk/</</<@resource://devtools/client/debugger/new/src/actions/utils/middleware/thunk.js:21:45
dispatch@resource://devtools/client/shared/vendor/redux.js:755:18
connect/<@resource://devtools/client/debugger/new/src/actions/navigation.js:71:11
async*thunk/</</<@resource://devtools/client/debugger/new/src/actions/utils/middleware/thunk.js:21:45
bindActionCreator/<@resource://devtools/client/shared/vendor/redux.js:644:12
onConnect@resource://devtools/client/debugger/new/src/client/firefox.js:64:9
async*onConnect@resource://devtools/client/debugger/new/src/client/index.js:81:9
async*bootstrap@resource://devtools/client/debugger/new/src/main.js:41:15
open@resource://devtools/client/debugger/new/panel.js:30:15
async*onLoad@resource://devtools/client/framework/toolbox.js:1804:21
"

    destroy resource://devtools/shared/protocol.js:1328 destroy resource://devtools/shared/fronts/targets/worker.js:53 emit resource://devtools/shared/event-emitter.js:186 emit resource://devtools/shared/event-emitter.js:267 onPacket resource://devtools/shared/protocol.js:1453 onPacket resource://devtools/shared/client/debugger-client.js:765 send resource://devtools/shared/transport/local-transport.js:64 makeInfallible resource://devtools/shared/ThreadSafeDevToolsUtils.js:109 makeInfallible resource://devtools/shared/ThreadSafeDevToolsUtils.js:109 
```

<img width="731" alt="image" src="https://user-images.githubusercontent.com/8599/51298675-4a340980-19da-11e9-8a07-6335161ca514.png">

**Comment by digitarald** [comment]
Same issue: https://perfht.ml/2T0tNZB

Still pauses in is lastpass' `onloadwff.js`, which is a minified super-long file (5000+ line length).

**Comment by digitarald** [comment]
Continued in https://bugzilla.mozilla.org/show_bug.cgi?id=1553291
