### ISSUE TITLE
Source maps are not offered when the generated source is open

### ISSUE THREAD

**Issue by digitarald** [firefox-devtools/debugger#7138]
STR:
- Open https://perf-html.io/noop/ with Debugger open and Pause on Uncaught Exception on
- Open generated file (`something.bundle.js`) for the file it pauses in, close original file.
- Refresh

ER: Pause in original file
AR: Pauses in generated file without any hint to jump to original file

![screenflow](https://user-images.githubusercontent.com/8599/47321674-5f331380-d60a-11e8-99df-216750251d27.gif)

**Comment by loganfsmyth** [comment]
I'm not sure I agree with this. If I've explicitly opened the generated file, I don't think I'd expect to get pushed back into the original file on refresh.

That said, it would be _great_ to have an easy way to jump to the original file associated with the current location in the generated code.

**Comment by digitarald** [comment]
> I'm not sure I agree with this. If I've explicitly opened the generated file, I don't think I'd expect to get pushed back into the original file on refresh.

True, my ER and title mismatch. Mostly the concern here is that the original file is not offered anywhere in the call stack.

**Comment by loganfsmyth** [comment]
Gotcha. Could we have a button in the bottom in the same place as the jump-to-generated button on original files, but going the other direction? Currently the right-hand panes are tied to whether you are viewing a generated or original file in the editor, so having a button to change the editor back to viewing the original file would also switch the scope and stack trace panes back, if memory serves.

**Comment by digitarald** [comment]
> Could we have a button in the bottom in the same place as the jump-to-generated button on original files, but going the other direction?

I guess the button would be based on the current position? Do we have that mapping data already?

**Comment by loganfsmyth** [comment]
Let's lump this in with https://bugzilla.mozilla.org/show_bug.cgi?id=1634721
