### ISSUE TITLE
Fix intermittent for browser_dbg-sources-querystring.js

### ISSUE THREAD

**Issue by darkwing** [firefox-devtools/debugger#7185]
Our new `browser_dbg-sources-querystring` test intermittently fails by timing out.  The timeout happens on the `waitForSources` line.  We need to find the source of this problem, fix it, and re-enable the test.

**Comment by darkwing** [comment]
The root cause, which appears to be server, can be found here:

https://bugzilla.mozilla.org/show_bug.cgi?id=1503422

**Comment by janodvarko** [comment]
Firefox Developer Tools (including Debugger tool) development is now entirely happening in Bugzilla and new issues should be reported here: https://bugzilla.mozilla.org/enter_bug.cgi?product=DevTools&component=Debugger

Honza
