### ISSUE TITLE
Slow stepping is made worse by noisy UI

### ISSUE THREAD

**Issue by digitarald** [firefox-devtools/debugger#7191]
STR:
- Set a breakpoint in `https://perf-html.io/` (like `webpack:///src/components/app/Root.js`, line 161)
- Refresh to pause
- Step forward

The panels update in ripples. The async nature that loads data in stages makes the UI unusable until its finished loading as it moves around.

Profile with screenshots: http://bit.ly/2AzBIGP

Stepping at 25% speed:
![screenflow](https://user-images.githubusercontent.com/8599/47684687-f5c67e00-db90-11e8-9447-386941b6f143.gif)

**01:04** _Call stack_ and _Scopes_ vanish
**01:14**: _Call stack_ reappears but not mapped. _Scopes_ appears again, but _unavailable_. #7145 causes the input to focus and be scrolled into view.
**02:04**: _Call stack_ gets mapped
**02:17**: _Scopes_ get filled in
**02:20**: _Scopes_ switched to _Loading…_
**03:28**: _Scopes_ is mapped

@gregtatum reported a similar issue in his debugging with a mostly similar pattern:

<img width=200 src="https://user-images.githubusercontent.com/8599/47684998-29ee6e80-db92-11e8-88a9-1fa10a6b63c2.png">

<img width=200 src="https://user-images.githubusercontent.com/8599/47685006-2eb32280-db92-11e8-9881-68889667fdca.png">

<img width=200 src="https://user-images.githubusercontent.com/8599/47685010-3246a980-db92-11e8-8dc2-75597f48a54f.png">

<img width=200 src="https://user-images.githubusercontent.com/8599/47685014-35419a00-db92-11e8-8581-56ea92a9654a.png">

<img width=200 src="https://user-images.githubusercontent.com/8599/47685016-383c8a80-db92-11e8-9c35-20261127c49a.png">

**Comment by darkwing** [comment]
@digitarald Care to weigh in on this?

**Comment by digitarald** [comment]
Looks a lot better, with less noise. Lets close for now.
