### ISSUE TITLE
Remove stack trace related action out of FrameMenu

### ISSUE THREAD

**Issue by nchevobbe** [firefox-devtools/debugger#7208]
When the debugger is paused, we show the `Call stack` panel.
On this panel we have a list of all the frames of the stack.
On each frame, the user can right-click to get a context menu offering frame related actions: 

<img width="301" alt="image" src="https://user-images.githubusercontent.com/578107/47779178-c763b280-dcf8-11e8-8fe3-147767709726.png">

Except some actions are not really strictly-related frame action: 
- `Copy stack trace` is about the whole component
- `Disable framework grouping` is also about the stacktrace. What's even more confusing is that "group frames" don't have the `onContextMenu` handler, so you can't disable framework grouping by right-clicking on a group.

I think it would be nice to only have in this menu the Frame related actions.
Copy stacktrace and toggle framework grouping could be moved into the call stack header: 

```
+---------------------------------+
| ▼ Call stack                  ⚙︎ |
+---------------------------------+
| render                App.js:22 |
| finishClassComponent      React |
+---------------------------------+

```

Clicking on the gear icon would open a new menu with the 2 actions.

Or, we could have 2 different icons for those actions directly in the header

```
+---------------------------------+
| ▼ Call stack              🖋 🔗 |
+---------------------------------+
| render                App.js:22 |
| finishClassComponent      React |
+---------------------------------+
```

(even though those icons could be tricky to get right)

**Comment by janodvarko** [comment]
Cloned into https://bugzilla.mozilla.org/show_bug.cgi?id=1695210

Firefox Developer Tools (including Debugger tool) development is now entirely happening in Bugzilla and new issues should be reported here: https://bugzilla.mozilla.org/enter_bug.cgi?product=DevTools&component=Debugger

Honza
