### ISSUE TITLE
rename TabTarget to Target

### ISSUE THREAD

**Issue by codehag** [firefox-devtools/debugger#7239]
As part of the fission work, we have migrated TabTarget to being named just "Target" -- it would be great if the debugger had the same naming scheme

Files affected:
https://github.com/devtools-html/debugger.html/search?q=tabtarget&unscoped_q=tabtarget

Original issue:
https://bugzilla.mozilla.org/show_bug.cgi?id=1503628

**Comment by jasonLaster** [comment]
@codehag these changes look like they will either land in devtools-core/launchpad or could land in m-c and be backported.

**Comment by baronKilljoy** [comment]
I would like to try addressing this.

**Comment by jasonLaster** [comment]
I think that this change requires renaming TabTarget in devtools-core/devtools-connection.

https://github.com/devtools-html/devtools-core/blob/master/packages/devtools-connection/src/target.js

I'm worried about the challenges of keeping devtools-core/devtools-connection in sync. My guess is that there are now other changes we will need to do as well. Maybe we should step back and re-evaluate in january?

**Comment by jasonLaster** [comment]
@baronKilljoy if you want to experiment with different approaches you're more than welcome, but be for warned this can be quite challenging and there are plenty of issues out there :)

**Comment by baronKilljoy** [comment]
I saw this as a quick turn around, and am fine patching on multiple projects. However, I agree a comprehensive list will be useful. Plus I already found one issue in commands.js  there is a tabTarget object called TabTarget. The change is simple but will need to know your variable naming rules. Ill back out changes I made and kept an eye on this thread to see what decision is made.

**Comment by twisted-sres** [comment]
Is anybody working on this, or can Itake this up?

**Comment by jasonLaster** [comment]
@twisted-sres i think is a tough bug to work on.
