### ISSUE TITLE
Breakpoint doesn't survive any attempts at reloading the page.

### ISSUE THREAD

**Issue by karlcow** [firefox-devtools/debugger#7260]
Steps to reproduce:
1. with Firefox RDM + Firefox Android UA.
2. Open devtools.
3. Go to https://www.2gud.com/
4. Notice in the console "TypeError: e.jsBundles is undefined; can't access its "checkout" property[Learn More]"
5. Open the script and format the code.
6. Set a breakpoint on  `var t = l.default.get();` for example in https://img1a.flixcart.com/www/linchpin/emerald/app.60f138.bundle.js

```js
key: 'getBundlesToPrefetch',
value: function (e) {
var t = l.default.get();
if (!t) return null;
var n = (0, s.default) (t, function (e) {
    return e.jsBundles.checkout.js
}) || [
// etc …
```

7. reload the page to trigger the breakpoint.

Actual:
The page reloads the breakpoint is lost.

Expected:
The debugger kicks in at the right place.

**Comment by jasonLaster** [comment]
<img width="1190" alt="screen shot 2018-11-14 at 8 59 19 am" src="https://user-images.githubusercontent.com/254562/48487240-a072a980-e7eb-11e8-9020-b3c56b502663.png">

**Comment by karlcow** [comment]
@jasonLaster the Firefox Android UA is not this ;)

Here the right string.
```
Mozilla/5.0 (Android 9.0.0; Mobile; rv:64.0) Gecko/64.0 Firefox/64.0
```

<img width="845" alt="capture d ecran 2018-11-15 a 07 01 19" src="https://user-images.githubusercontent.com/505230/48515523-47b31780-e8a4-11e8-93de-5fe6842c54b2.png">

**Comment by loganfsmyth** [comment]
@digitarald That seems likely, I'll have to dig into it more when doing the pretty-print work.

**Comment by janodvarko** [comment]
@karlcow: I can't reproduce the bug, BP is there and works after reload.

But the page source code changes and I couldn't set BP exactly on `Set a breakpoint on var t = l.default.get();`

Can you still see the issue?

Honza

**Comment by karlcow** [comment]
ok let's see. @janodvarko this doesn't reproduce anymore. Thanks for checking.
