### ISSUE TITLE
[WebAssembly] Assume Debugger.allowWasmBinarySource is always `true`

### ISSUE THREAD

**Issue by yurydelendik** [firefox-devtools/debugger#7312]
Continuation of https://bugzilla.mozilla.org/show_bug.cgi?id=1492301:

If there is a configuration of allowWasmBinarySource, we need to remove that. The allowWasmBinarySource=false logic can be removed as well

**Comment by SeanPrashad** [comment]
Hey @yurydelendik - I was wondering if there would be anyone available to mentor on this issue? [@kartik-budhiraja](https://github.com/kartik-budhiraja) and I wanted to pair up to help fix this!

**Comment by jasonLaster** [comment]
Feel free to stop by our slack wasm channel

**Comment by Utkarsh1308** [comment]
Is this issue still open? Can I work on this

**Comment by jasonLaster** [comment]
here's a good reference for where to find it
https://github.com/devtools-html/debugger.html/blob/master/src/client/firefox.js#L27-L30

**Comment by Utkarsh1308** [comment]
Do we have to remove all instances of wasmBinary Source from the file you mentioned?

**Comment by jasonLaster** [comment]
i think so...

**Comment by rjairath** [comment]
Hey @jasonLaster, can I work on this issue?

**Comment by janodvarko** [comment]
@yurydelendik Firefox Developer Tools (including Debugger tool) development is now entirely happening in Bugzilla and new issues should be reported here: https://bugzilla.mozilla.org/enter_bug.cgi?product=DevTools&component=Debugger

Please reopen this report in Bugzilla if it's still valid.

Honza
