### ISSUE TITLE
Implement new column breakpoints UI

### ISSUE THREAD

**Issue by mcroud** [firefox-devtools/debugger#7332]
The latest mockup of column breakpoint UI was approved on 21st Nov.
The UI can now be implemented.

**Image as reference:**
![column breakpoints 7_2x](https://user-images.githubusercontent.com/42435754/48896218-fd4f0f00-ee3e-11e8-81ef-da5f424d46b7.png)

[Mockup](https://mozilla.invisionapp.com/share/9KOC5HST4DP#/332638924_Column_Breakpoints_7) (Invision)

Past decisions have been captured in the [Feedback document](https://docs.google.com/document/d/1dhPsoZgYKy3nAu6Sqb5Xm30f4KXZjyoJ1j6mlgtwZKk/edit?usp=sharing)

**Comment by darkwing** [comment]
The mockup shows 2 states, "regular" and disabled, but I believe there are three total states:

1. column breakpoint shown (i.e. not activated)
2. column breakpoint enabled/clicked
3. column breakpoint enabled/clicked but disabled

I propose we try to:

1.  Use the same colors for light and dark as we do for the gutter breakpoint
2.  Use the first cited colors in the mockup for activated column breakpoints
3.  Use the second ("disabled) colors for disabled column breakpoints

**Comment by digitarald** [comment]
@darkwing I remember that we talked about the states in the planning meetings; looks like we missed it to capture it in the final mockup.

Let's go with your proposal and tweak as necessary.
