### ISSUE TITLE
[l10n] Modifier keys shown in shortcuts in menu should be localizable

### ISSUE THREAD

**Issue by Archaeopteryx** [firefox-devtools/debugger#7340]
The modifier keys are shown for the shortcuts in the line context menu (right click a line number to get the menu to add a breakpoint or a conditional breakpoint).

German localizes shortcuts: "Ctrl" is "Strg", "Shift" is "Umschalt".

At the moment "CtrlB" and "CtrlShiftB" are shown with both Firefox 64.0b12 and 65.0a1 latest Nightly on Windows 8.1

**Comment by janodvarko** [comment]
Firefox Developer Tools (including Debugger tool) development is now entirely happening in Bugzilla and new issues should be reported here: https://bugzilla.mozilla.org/enter_bug.cgi?product=DevTools&component=Debugger

Please reopen this report in Bugzilla if it's still valid.

Honza
