### ISSUE TITLE
Debugger pauses on thrown exception in blackboxed source

### ISSUE THREAD

**Issue by nchevobbe** [firefox-devtools/debugger#7344]
Someone on IRC ran into an issue where: 
- they had a webextension script blackboxed
- the `Pause on exception` checkbox turned on

An exception thrown by the blackboxed webextension script was pausing the debugger, which can be a bit annoying (even more for a webextension, because it's likely to not be *your* code)

**Comment by nicofrand** [comment]
If that can be of any help: I noticed it when using Firefox 64.0b11 (64 bits) with the LastPass extension.
I am indeed interested by exceptions in my code, not the web extensions.

**Comment by janodvarko** [comment]
Cloned into https://bugzilla.mozilla.org/show_bug.cgi?id=1695218

Firefox Developer Tools (including Debugger tool) development is now entirely happening in Bugzilla and new issues should be reported here: https://bugzilla.mozilla.org/enter_bug.cgi?product=DevTools&component=Debugger

Please reopen this report in Bugzilla if it's still valid.

Honza
