### ISSUE TITLE
Merge all 'Getting Started' content into one file.

### ISSUE THREAD

**Issue by emmairwin** [firefox-devtools/debugger#7353]
We keep running into a loop of documents that invite contributors to 'get started' and have observed the a set of files provide similar instruction OR loop between each other.   Also to consider localization of 'getting started' steps in future, this would be a dependency .   

### Files with 'getting started'  content, or first-steps content:

* README
  * [Quick Setup](https://github.com/devtools-html/debugger.html/blob/master/README.md#quick-setup)
*  [Getting Setup](https://github.com/devtools-html/debugger.html/blob/master/docs/getting-setup.md)
* Debugging the Debugger
  * [ Debugging the Debugger](https://firefox-dev.tools/debugger.html/docs/debugging-the-debugger.html) (Jekyll version)
  * [Debugging the Debugger ](https://github.com/devtools-html/debugger.html/blob/master/docs/debugging-the-debugger.md)(Markdown version)

It seems like merging and updating content into Getting Setup might be a good direction.  At the same time gives opportunity to remove Node, and Chrome. 
 
Also one page for 'common issues' might be good to break out into it's own file.   As we heard from some contributors testing , that a type of 'lookup file' for errors would be helpful.

**Comment by jasonLaster** [comment]
Thanks!

So, we don't promote the jekyll version. It is literally the same thing, maybe we just don't promote it or we find another way to describe it...

**Comment by soniasingla** [comment]
@emmairwin is this issue available? I would like to work upon it :smile:

**Comment by janodvarko** [comment]
The main DevTools (including Debuguger) doc is here:
https://firefox-source-docs.mozilla.org/devtools/index.html

We also moved our bug tracking system entirely to Bugzilla. So, please file new Debugger bugs here:
https://bugzilla.mozilla.org/enter_bug.cgi?product=DevTools&component=Debugger

Honza
