### ISSUE TITLE
ObjectInspector "store" isn't handled properly

### ISSUE THREAD

**Issue by nchevobbe** [firefox-devtools/debugger#7369]
Since https://github.com/devtools-html/debugger.html/commit/eed51191ceaa85f90f4881c9ff04b0375f5169f1#diff-a52d809c971862e9fb04ea8dff213281 the `ObjectInspector` does not manage its own store, but provides a reducer for other store to consume.

Given how this is done, this means that some app stores (Console, Debugger), hold the state of **multiple** `ObjectInspector` instances in their store.

This is fine, but that also mean that we don't handle clearing OI state properties when we don't need them anymore.

Since some app don't want to clear things on OI unmount (the debugger needs to persist data across re-render when stepping for example), it would be nice to provide: 
1. an action to fully clear the OI state
2. an action to remove the data related to a given `roots` prop
3. an `ObjectInspector` prop (e.g. `clearStateOnUmount`) that would call the action from 2. , which would be set to false for app that don't want it (e.g., the debugger).

**Comment by janodvarko** [comment]
@nchevobbe is this still valid?

Honza

**Comment by nchevobbe** [comment]
I think we're fine now
