### ISSUE TITLE
Allow to reevaluate getters

### ISSUE THREAD

**Issue by Loirooriol** [firefox-devtools/debugger#7395]
Consider `({get a() {return Math.random()}})`

I can only run the getter once. I would like to be able to run it again in order to see the updated value.

**Comment by nchevobbe** [comment]
the idea would be to display a "refresh" button before or after the result of the getter invoke.
We could even have a timestamp on this button which could look like: "Refresh evaluation - Last evaluation at 12:09:23".

**Comment by nchevobbe** [comment]
Yes, it should be something like: 

```
▼ {…}
|  a: >>
```

user clicks on `>>`
```
▼ {…}
|  a: 🔄 0.343434
```

with a `title` on the `🔄` to indicate "evaluated at 12:42 - click to evaluate again" (or something similar)

**Comment by janodvarko** [comment]
Cloned into: https://bugzilla.mozilla.org/show_bug.cgi?id=1695225

Firefox Developer Tools (including Debugger tool) development is now entirely happening in Bugzilla and new issues should be reported here: https://bugzilla.mozilla.org/enter_bug.cgi?product=DevTools&component=Debugger

Honza
