### ISSUE TITLE
Add a way to evaluate setter properties

### ISSUE THREAD

**Issue by Loirooriol** [firefox-devtools/debugger#7396]
#6140 added a way to evaluate getters, but not setters.

I think setters should have an "invoke setter" button which shows some kind of input box when clicked. Then I should be able to enter some code there, which will be evaluated and the result will be passed to the setter.

**Comment by janodvarko** [comment]
Cloned into:
https://bugzilla.mozilla.org/show_bug.cgi?id=1661701

We are using bugzilla as our bug tracking system now, so please report new bugs here:
https://bugzilla.mozilla.org/enter_bug.cgi?product=DevTools&component=Debugger

Thanks
Honza
