### ISSUE TITLE
Cannot follow link to failing code

### ISSUE THREAD

**Issue by armenzg** [firefox-devtools/debugger#7445]
[Edit] I've removed some info from the bottom of this issue and added some screenshots.

I have a private React app where I cannot get to the the code that's failing (see [1])
I can give you access to clone it.
I have to apologize as I should have filed this issue ages ago as I find it to happen quite often.

STR:
* Checkout code
* yarn && yarn start
* Load http://localhost:5000/?ldapEmail=someone@mozilla.com
* Look at the console and follow the link

This is the output I get in Firefox:
<img width="674" alt="image" src="https://user-images.githubusercontent.com/44410/49678185-aeb18f80-fa50-11e8-8741-f87ddf5a3545.png">

This is the output I get in Chrome:
<img width="790" alt="image" src="https://user-images.githubusercontent.com/44410/49678154-8de93a00-fa50-11e8-9c85-26490ba61a9e.png">

[1]
---------------------------------------------------------
I see this in the console:
> TypeError: can't convert undefined to object 1.js line 35 > eval:12:47

The last part of a text is a hyperlink which I follow to:
> view-source:http://localhost:5000/assets/1.js%20line%2035%20%3E%20eval

Instead of seeing the code I see this output:
```html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Cannot GET /assets/1.js%20line%2035%20%3E%20eval</pre>
</body>
</html>
```

**Comment by armenzg** [comment]
@darkwing I believe this new information should help.

I have created a public repo with a smaller testcase.
In this case I have more messages [1] in the console, however, you can still see a case where the link is not usable (TypeError: can't convert undefined to object [index.js line 44 > eval:22:47](http://localhost:5000/assets/index.js%20line%2044%20%3E%20eval) --> view-source:http://localhost:5000/assets/index.js%20line%2044%20%3E%20eval)

Now, I have also noticed that if I expand the dropdown message I will see usable hyperlinks (e.g. 	advancedSearchToRestApi App.jsx:8 ):
<img width="608" alt="image" src="https://user-images.githubusercontent.com/44410/49742041-b72ee380-fc65-11e8-8fd2-c161041b8fb4.png">
**Screenshot from public testcase**

Being able to expand the message is *not* available on my original repo. I wonder if the code is quite nested within React components or something else.
Chrome's devtools handles this properly by making the first line's hyperlink correct *and* the message is expanded:
<img width="786" alt="image" src="https://user-images.githubusercontent.com/44410/49742585-d4b07d00-fc66-11e8-9399-56b4fe3ae8da.png">
**Screenshot from private app**

The repo and code is in this branch:
https://github.com/armenzg/devtools-testcases/tree/master/issue7445

**[NEW]** STR:
```
git clone git@github.com:armenzg/devtools-testcases.git
cd devtools-testcases && git checkout issue7445 
yarn && yarn start
// It will open http://localhost:5000
// Check the output of the console and focus on the:
// 'TypeError: can't convert undefined to object'
//  line at the end
```
*    Checkout code
*    yarn && yarn start
*    Load http://localhost:5000/?ldapEmail=someone@mozilla.com
*    Look at the console and follow the link


[1]
<img width="881" alt="image" src="https://user-images.githubusercontent.com/44410/49741870-59020080-fc65-11e8-9d48-71694798fa81.png">

**Comment by nchevobbe** [comment]
I'll have a look tomorrow, as it looks like it can be a console issue.

Le lun. 10 déc. 2018 à 16:33, Armen Zambrano <notifications@github.com> a
écrit :

**Comment by nchevobbe** [comment]
so, simpler STR:

1. Go to `data:text/html,<meta charset=utf8><script>eval('console.log("hello")')</script>`
2. Open the console
3. Click on the location for the "hello" message

-> the following page opens `view-source:data:text/html,<meta charset=utf8<script>eval('console.log("hello")')</script> line 1 > eval`, instead of the debugger.

So here, the original issue is probably because of hot reload using eval, and eval source not being fetched by the debugger as valid source (I guess, I'm really not sure about this).

I think we do already have bugs for this in bugzilla (or here), I'll try to find them.

@loganfsmyth it would be great if you could have a look at the underlying issue here.

**Comment by darkwing** [comment]
Pinging @loganfsmyth when you get a chance.

**Comment by thefearlesscoder** [comment]
I have the same issue as @armenzg. Pulled my hair out until I found this thread.

**Comment by loganfsmyth** [comment]
This should behave much more consistently now on Nightly. There may still be cases, so I'm going to close this and if people come across new cases, please file in Bugzilla.
