### ISSUE TITLE
Shortcut `Ctrl /` not working on German keyboard

### ISSUE THREAD

**Issue by gerdneuman** [firefox-devtools/debugger#7491]
On a German keyboard the shortcut `Ctrl + /` is not working. 

I guess because the `/` is `Shift + 7` on a German keyboard layout. Pressing `Ctrl + Shift + 7` does nothing.

See https://en.wikipedia.org/wiki/German_keyboard_layout#General_information Notice, that `/` is on top of `7` and needs `Shift`

**Comment by jasonLaster** [comment]
CC @codehag could you provide some more context?

**Comment by codehag** [comment]
We chatted offline -- unfortunately I won't be much help here since I don't use a german keyboard. It looks like it might be a bug with our keybindings, as the german keybinding has three keys involved. Thaaats just a guess though... I haven't looked into how we do our key bindings in a while

**Comment by jasonLaster** [comment]
Here is our logic for stepping shortcuts
https://github.com/devtools-html/debugger.html/blob/master/src/components/SecondaryPanes/CommandBar.js#L34-L53

and keyboard shortcuts

https://github.com/devtools-html/devtools-core/blob/master/packages/devtools-modules/src/key-shortcuts.js#L152

Would you be open to getting the project setup locally and debugging it a bit?
https://github.com/devtools-html/debugger.html/#quick-setup

I think you would be able to see what is going on under the hood pretty quickly... I'd be happy to help in slack too

**Comment by fvsch** [comment]
Not working on French (AZERTY) keyboards either, at least on Linux.

Main issue is that the `"/"` character is not directly accessible with a single Key, on my current keyboard you need <kbd>Shift :</kbd> to make a `"/"` character (or also <kbd>Shift Fn à</kbd> on this specific computer, but that's less common).

A lot of Web apps have this issue, e.g. half of Figma's shortcuts use punctuation signs so they're unusable on AZERTY keyboards.

**Comment by fvsch** [comment]
Not working on French (AZERTY) keyboards either, at least on Linux.

Main issue is that the `"/"` character is not directly accessible with a single Key, on my current keyboard you need <kbd>Shift :</kbd> to make a `"/"` character (or also <kbd>Shift Fn à</kbd> on this specific computer, but that's less common).

What seems to happen in my case is that I need to hit <kbd>Ctrl Shift :</kbd> to make a <kbd>Ctrl /</kbd> shortcut. This works well in native apps, where the <kbd>Shift :</kbd> part does register as a <kbd>/</kbd> key, but not in Debugger. Why?

Looking at the keydown event, when hitting <kbd>Ctrl Shift :</kbd> the event has the following keys (selecting the relevant bits):

```
{
  keyCode: 58,
  altKey: false,
  ctrlKey: true,
  shiftKey: true,
  metaKey: false,
  key: "/"
}
```

So it seems the shortcut matching implementation is turning that into `"Ctrl+Shift+/"`, which doesn't match the expected `"Ctrl+/"`.

It looks like some code is trying to handle that, but maybe that's a related but different problem that is addressed there, or maybe that code has a bug, I'm not sure. Here it is:
https://github.com/devtools-html/devtools-core/blob/master/packages/devtools-modules/src/key-shortcuts.js#L192-L197

**Comment by fvsch** [comment]
I guess that's related to why I can never "Resume" on mac too, the expected shortcut is `"Cmd+\\"` but in order to produce the <kbd>\</kbd> key I need modifiers, so I'm getting `"Cmd+Alt+Shift+\\"` or something.

**Comment by janodvarko** [comment]
Firefox Developer Tools (including Debugger tool) development is now entirely happening in Bugzilla and new issues should be reported here: https://bugzilla.mozilla.org/enter_bug.cgi?product=DevTools&component=Debugger

Please reopen this report in Bugzilla if it's still valid.

Honza
