### ISSUE TITLE
Restructure Context Menus

### ISSUE THREAD

**Issue by darkwing** [firefox-devtools/debugger#7497]
We have some really awesome context menus that make using the DevTools debugger easier and more effective.  Each context menu was custom created at the time of need which was great when they were implemented but, a few years in, I think we can take a step back and broaden both their code structure and visual structure.

We should create context menu "sections", which would include:

- Breakpoint (enable, disable, remove, add condition, remove condition, etc.)
- Breakpoints (enable all, disable all, remove all, remove all on line, etc.)
- Source (copy to clipboard, copy url, reveal in tree, pretty print, etc.)
- Tab (close, close other, close all, close all to the right, etc.)

The advantage here would be using multiple sections in a single context menu.  For example, the context menu that displays when you right-click a tab could contain: Tab, Source, and possibly even Breakpoint (i.e. to let someone disable all breakpoints in a source).

**Comment by fvsch** [comment]
Can we improve the "Copy..." options in the source editor? They're rather confusing!

For example, in the editor, if I don't select text:

1. "Copy to clipboard" is enabled, it copies the whole file's text
2. "Copy source text" is shown but disabled

If I select some text:

1. "Copy to clipboard" is enabled, it copies the whole file's text
2. "Copy source text" is enabled, it copies the selected text only

Maybe that's just a matter of making those labels more explicit?

It would also improve usability a bit to have "Copy to clipboard" say _what_ gets copied, when right-clicking a tab or a filename in the Sources view. In those contexts, I expected this feature to copy the file name or a file path, not, say, 100kb of text.

So a sufficiently-clear label should work in all relevant contexts.

Maybe:
- "Copy source code to clipboard" (Sources view, tab, editor)
- "Copy selected text" (editor only)

**Comment by janodvarko** [comment]
Firefox Developer Tools (including Debugger tool) development is now entirely happening in Bugzilla and new issues should be reported here: https://bugzilla.mozilla.org/enter_bug.cgi?product=DevTools&component=Debugger

Please reopen this report in Bugzilla if it's still valid.

Honza
