### ISSUE TITLE
Chrome support

### ISSUE THREAD

**Issue by bomsy** [firefox-devtools/debugger#7560]
After back support for the chrome client, as next steps we need to fix a couple of things.

- [x] show debug line
- [ ] support preview
- [ ] show scopes (reps is out of scope (pun not intended))
- [ ] support watch expressions

**Comment by janodvarko** [comment]
Firefox Developer Tools (including Debugger tool) development is entirely happening in Bugzilla and new issues should be reported here: https://bugzilla.mozilla.org/enter_bug.cgi?product=DevTools&component=Debugger

@bomsy if this is still valid, please create new report in Bugzilla, thank you.

Honza
