### ISSUE TITLE
Show interface before source maps load/parse

### ISSUE THREAD

**Issue by digitarald** [firefox-devtools/debugger#7570]
STR:
- Open this github page
- Open Devtools with Console
- Switch to Debugger

Profile: https://perfht.ml/2PQyfYM

For the user it takes 1+ sec for the Debugger to load, most of the time just showing an empty panel.

Code-wise the UI blocks on loading `.map` files and parsing them; which depending on Network can take even longer. Throttling macOS to bad 3G shows how the Debugger load time is too network bound (blue bars in the network track), bringing the delay to 2+s:

<img width="1511" alt="image" src="https://user-images.githubusercontent.com/8599/50310348-98470300-0456-11e9-95d8-02561d101ffd.png">

**Comment by jasonLaster** [comment]
this should help

https://github.com/devtools-html/debugger.html/pull/7302

**Comment by janodvarko** [comment]
Firefox Developer Tools (including Debugger tool) development is entirely happening in Bugzilla and new issues should be reported here: https://bugzilla.mozilla.org/enter_bug.cgi?product=DevTools&component=Debugger

If Issue #7302 doesn't help the bug should be reported in Bugzilla.

Honza
