### ISSUE TITLE
[sources] Set directory root does not work for debugger.html

### ISSUE THREAD

**Issue by jasonLaster** [firefox-devtools/debugger#7571]
STR:

1. go to http://localhost:8000/
2. open the debugger
3. right click on the debugger.html dir

ER: see the files below webpack
AR: see no sources

NOTE other dirs work

**Comment by jasonLaster** [comment]
@jainsneha23 i think that was  a typo...


<img width="546" alt="screen shot 2018-12-24 at 4 52 40 pm" src="https://user-images.githubusercontent.com/254562/50406973-67d7cf80-079c-11e9-9d70-a702bd008302.png">


<img width="333" alt="screen shot 2018-12-24 at 4 52 48 pm" src="https://user-images.githubusercontent.com/254562/50406972-67d7cf80-079c-11e9-8f64-ebe1db782eac.png">

**Comment by jainsneha23** [comment]
@jasonLaster The problem is with the directory being system absolute path. I am raising a WIP PR. This solves the bug. But the code needs refactoring.

**Comment by jasonLaster** [comment]
Thanks. How should we refactor it?

**Comment by jainsneha23** [comment]
Yeah. My initial thought was to simplify the bundling. But then I found other examples where the same issue existed. Like the angular todomvc  in debugger examples. So we have to handle absolute paths anyways.

**Comment by janodvarko** [comment]
Is the following STRs related to this report?

1) Load https://firefox-dev.tools/debugger-examples/examples/my-app/build/
2) Open DevTools, select the Debugger panel
3) Right click on `Webpack` dir in the Sources panel an pick `Set directory root`

ER:
Content of Webpack dir is displayed
AR:
Content of `~` is displayed

Honza

**Comment by jasonLaster** [comment]
I hope to work on this this week. @janodvarko i'll look into that then.

**Comment by darkwing** [comment]
Jason fixed this in MC.
