### ISSUE TITLE
[Docs] Add a FAQ section to the docs

### ISSUE THREAD

**Issue by princiya** [firefox-devtools/debugger#7595]
As per this PR - https://github.com/devtools-html/debugger.html/pull/7589, there is a need to document few configurations which might help us troubleshoot and better serve the community.

Following points came out of the above PR:
- turn off column breakpoints `dbg.features.columnBreakpoints = false`
- disable `privacy.resistFingerprinting` in `about:config`

The proposal is to create a `docs/faq.md` page and document the above points.

**Comment by janodvarko** [comment]
Firefox Developer Tools (including Debugger tool) development is entirely happening in Bugzilla and new issues should be reported here: https://bugzilla.mozilla.org/enter_bug.cgi?product=DevTools&component=Debugger

Please file a new bug for this in Bugzilla, if this report is still valid, thank you.

Honza
