### ISSUE TITLE
[SourceTree] Use native HTML features to create tree instead of aria-level

### ISSUE THREAD

**Issue by ash-tamraz** [firefox-devtools/debugger#7604]
**Steps to Reproduce:**
Examine HTML for SourceTree of Debugger

**System Details:**
Browser: Firefox Nightly 66.0a1
OS: Ubuntu 16.04

Currently SourceTree uses `<div>` elements with `aria-level` attributes to create the hierarchy of the source tree. Child and parent nodes are at the same level, with the level only being set by `aria-level` attributes. [In light of best practice for using WAI-ARIA suggesting only using when necessary, and using native HTML features when possible](https://developer.mozilla.org/en-US/docs/Learn/Accessibility/WAI-ARIA_basics#When_should_you_use_WAI-ARIA), it would seem to make more sense to create SourceTree with `<ul>` unordered lists, [as in this example](https://www.w3.org/TR/wai-aria-practices/examples/treeview/treeview-2/treeview-2a.html).

![sourcetree-example](https://user-images.githubusercontent.com/13565043/50497369-afa06600-09eb-11e9-853f-64b3361aa19e.jpeg)
![sourcetree-example-html](https://user-images.githubusercontent.com/13565043/50497370-afa06600-09eb-11e9-9d91-f650dc56621f.jpeg)

**Comment by jasonLaster** [comment]
I believe there is a reason for not using hierarchical elements.

CC @AnshulMalik do you remember?

**Comment by princiya** [comment]
@jasonLaster @AnshulMalik once we figure out about this decision, i will add this point too in `docs/faq.md` #7595 to avoid confusions going forward :)

**Comment by janodvarko** [comment]
Firefox Developer Tools (including Debugger tool) development is now entirely happening in Bugzilla and new issues should be reported here: https://bugzilla.mozilla.org/enter_bug.cgi?product=DevTools&component=Debugger

Please reopen this report in Bugzilla if it's still valid.

Honza
