### ISSUE TITLE
Deprecate getGeneratedLocation, expose getGeneratedLocations

### ISSUE THREAD

**Issue by yurydelendik** [firefox-devtools/debugger#7612]
The `generatedPositionFor` of the SourceMapConsumer returns one found position in the generated code. However there might be cases when multiple such locations can be used. There is [allGeneratedPositionsFor](https://github.com/mozilla/source-map#sourcemapconsumerprototypeallgeneratedpositionsfororiginalposition) we can use to return all found positions for the original source. Notice, per spec, that if the column is not provided all generated positions for this line are returned.

**Comment by loganfsmyth** [comment]
This exists now.
