### ISSUE TITLE
[SourceMap] Typescript source map issue

### ISSUE THREAD

**Issue by jasonLaster** [firefox-devtools/debugger#7615]
@jgonis initially filed: https://github.com/devtools-html/debugger.html/issues/2500

Pretty much what the title says.  I have made this project public in order to offer a test case, https://gitlab.com/jgonis/nature-of-code, but when I compile my typescript files and go to, say, the Random Walker page and bring up the debugger it displays the generated Javascript file, not the typescript files that were compiled to create it.  I tested Edge and Chrome to make sure that they work correctly with the sourcemaps generated and they both do.

**Comment by loganfsmyth** [comment]
We've fixed many many issues since this was filed, and I don't know the exact repro steps, so closing.
