### ISSUE TITLE
[Source Tree] File names should be unescaped while display

### ISSUE THREAD

**Issue by jainsneha23** [firefox-devtools/debugger#7635]
If the urls are encoded, the source tree shows the encoded filename. Instead, the filenames in source tree should be unescaped and be human readable

STR:
[x] Open https://w2x2oypmqk.codesandbox.io/ to debug
[x] Look at webpack files

AR: external%20%22file%22 is displayed in source tree
ER: external "file" should be displayed in source tree

<img width="800" alt="screenshot 2019-01-02 at 12 23 22 pm" src="https://user-images.githubusercontent.com/8366397/50582526-37bdba00-0e89-11e9-9960-3d7426bd865a.png">

**Comment by darkwing** [comment]
Have you had a chance to look at this @soniasingla ?  Can I help with anything?

**Comment by soniasingla** [comment]
Thanks @darkwing , I looked upon the issue. On the local host, the files under "webpack" folder could not be obtained. I am getting issue here, can you please help me with this?

**Comment by darkwing** [comment]
Hello Sonia!  When I go to the address cited, I see the Webpack directory with the items cited by @jainsneha23.  This is how I think we can fix the issue:

https://gist.github.com/darkwing/8c99abc57c3585d7e5df9141a95c32b2

**Comment by darkwing** [comment]
This has been fixed :)
