### ISSUE TITLE
[breakpoints] shift+click should add a disabled breakpoint

### ISSUE THREAD

**Issue by jasonLaster** [firefox-devtools/debugger#7671]
When the user shift+clicks in the gutter, the debugger should create a disabled breakpoint. Currently it creates an enabled breakpoint.

This is a good starting off spot

```diff
diff --git a/src/actions/breakpoints/index.js b/src/actions/breakpoints/index.js
index 830b39a64..4aa386967 100644
--- a/src/actions/breakpoints/index.js
+++ b/src/actions/breakpoints/index.js
@@ -385,7 +385,11 @@ export function toggleBreakpointsAtLine(line: number, column?: number) {
   };
 }

-export function addOrToggleDisabledBreakpoint(line: number, column?: number) {
+export function addOrToggleDisabledBreakpoint(
+  line: number,
+  column?: number,
+  shouldDisable
+) {
   return ({ dispatch, getState, client, sourceMaps }: ThunkArgs) => {
     const selectedSource = getSelectedSource(getState());

@@ -411,7 +415,8 @@ export function addOrToggleDisabledBreakpoint(line: number, column?: number) {
         sourceId: selectedSource.id,
         sourceUrl: selectedSource.url,
         line: line,
-        column: column
+        column: column,
+        enabled: !shouldDisable
       })
     );
   };
diff --git a/src/components/Editor/index.js b/src/components/Editor/index.js
index 7227c11d3..e0cf932a4 100644
--- a/src/components/Editor/index.js
+++ b/src/components/Editor/index.js
@@ -404,7 +404,7 @@ class Editor extends PureComponent<Props, State> {
     }

     if (ev.shiftKey) {
-      return addOrToggleDisabledBreakpoint(sourceLine);
+      return addOrToggleDisabledBreakpoint(sourceLine, ev.shiftKey);
     }
:
```

**Comment by baronKilljoy** [comment]
I would like to work on this. should I alter the existing function or override?

**Comment by AnshulMalik** [comment]
@baronKilljoy altering the existing function should do :)

**Comment by baronKilljoy** [comment]
My idea is to use the preexisting disabled property. However, it kepts being set to false. Am I doing something obviously wrong.
![change1](https://user-images.githubusercontent.com/36493475/50823867-028aef00-1303-11e9-8fb5-38093f747b74.png)
![change2](https://user-images.githubusercontent.com/36493475/50823875-06b70c80-1303-11e9-81e8-9c6fe287e3a2.png)

**Comment by baronKilljoy** [comment]
@AnshulMalik @jasonLaster  the shouldDisable wasn't working (since you would have to shift+click to get to this function it was either nothing or undefined). This approach worked but its different than your recommendation.
![change1](https://user-images.githubusercontent.com/36493475/50858108-870a5b80-135d-11e9-9e5c-9243e57ebf91.png)
![change2](https://user-images.githubusercontent.com/36493475/50858119-8a054c00-135d-11e9-8ffa-51b61dd4d9bb.png)

**Comment by baronKilljoy** [comment]
@AnshulMalik @jasonLaster  it looks like the breakpoint will have to be fully initialized then disabled.

**Comment by darkwing** [comment]
@baronKilljoy I was talking to @jasonLaster and he suggested sort of a fusion between your original PR and mine:

```js
export function createDisabledBreakpoint(location: SourceLocation) {
  return async ({ dispatch, getState, sourceMaps, client }: ThunkArgs) => {
    const generatedLocation = await getGeneratedLocation(
      state,
      source,
      location,
      sourceMaps
    );
    const symbols = getSymbols(getState(), source);
    const astLocation = await getASTLocation(source, symbols, newLocation);

    const originalText = getTextAtPosition(source, location);
    const text = getTextAtPosition(generatedSource, newGeneratedLocation);

    const breakpoint = createBreakpoint(breakpointPosition, {
      ...options,
      disabled: true,
      astLocation,
      originalText,
      text
    });
  };
}
```

Care to give it a try? :)

**Comment by darkwing** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1543999
