### ISSUE TITLE
Pausing in evaled URL-less mapped file does not show original source

### ISSUE THREAD

**Issue by loganfsmyth** [firefox-devtools/debugger#7682]
Noticed as part of https://github.com/devtools-html/debugger.html/issues/7614.

Steps:
1. Visit https://babeljs.io/en/repl#?babili=true&browsers=&build=&builtIns=false&spec=false&loose=false&code_lz=FAMwrgdgxgLglgewgAgEYEMBOAKdBKZAb2GWWAF9hgATAU1TAHNHbMBuMjHARjw-SA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=true&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=es2015%2Creact%2Cstage-2%2Cbabili&prettier=true&targets=&version=6.26.0&envVersion=
2. Open the debugger
3. Add a space to the file to trigger an eval

ER:
See original file while paused

AR:
Shows generated file.

(I think) adding `//# sourceURL=http://example.com/foo.js` to the evaled code to give it a base URL would make the original content show up, but that would ideally not be needed. If we can come up with placeholder names for the generated file, we can do the same for original files.

**Comment by bhackett1024** [comment]
I think there are a couple issues going on here:

1. The source containing the map has a null url and introductionUrl, so we don't set a url for the source mapping worker and it errors out.

2. If I fix that so it proceeds (set urlInfo.url to "http://unknown" in loadSourceMap) then we aren't able to compute a mapping for the 'debugger' statement.  The source map JSON and generated location both look right (though I don't know how to read the source map encoding format), but the source map code (originalPositionFor in source-map/worker.js) still fails to find a mapping.  The heavy lifting here is done by a wasm module which I have no clue how to debug, so I gave up.

**Comment by jasonLaster** [comment]
@bhackett1024 was this the change you made?

```diff
diff --git a/src/actions/sources/newSources.js b/src/actions/sources/newSources.js
index 2f4581e5e..2b75d98b1 100644
--- a/src/actions/sources/newSources.js
+++ b/src/actions/sources/newSources.js
@@ -88,7 +88,10 @@ function loadSourceMap(sourceId: SourceId) {

     let urls = null;
     try {
-      urls = await sourceMaps.getOriginalURLs(source);
+      urls = await sourceMaps.getOriginalURLs({
+        ...source,
+        url: source.url || "http://unknown"
+      });
     } catch (e) {
       console.error(e);
     }
```

@loganfsmyth i'm curious how why the mappings were not generated, when we looked into this you were able to unpack the base64 gobbledygook...

**Comment by jasonLaster** [comment]
We now show the generated eval'd source, which is similar to chrome, but it would be nice to show the original source if we can. 

<img width="769" alt="screen shot 2019-01-11 at 9 40 40 am" src="https://user-images.githubusercontent.com/254562/51041355-be5c5080-1587-11e9-840b-1eb537587a3c.png">

**Comment by bhackett1024** [comment]
> @bhackett1024 was this the change you made?

Yeah, this should work, though it looks a little different on m-c.

**Comment by loganfsmyth** [comment]
This works now.
