### ISSUE TITLE
DOM/Event/etc Breakpoints should be persisted per domain

### ISSUE THREAD

**Issue by digitarald** [firefox-devtools/debugger#7709]
(Follow up from DOM Breakpoint discussion, cc @darkwing )

**User Story**: When debugging different projects, I want to have a site-specific set of breakpoints active, so that don't need to enable/disable/remove them when switching sites.

Edge and Chrome both have origin-specific persistence for DOM and Event breakpoints. but not for XHR.

**Comment by janodvarko** [comment]
Cloned into https://bugzilla.mozilla.org/show_bug.cgi?id=1695214

Firefox Developer Tools (including Debugger tool) development is now entirely happening in Bugzilla and new issues should be reported here: https://bugzilla.mozilla.org/enter_bug.cgi?product=DevTools&component=Debugger

Honza
