### ISSUE TITLE
Consolidate Source Name Display Logic

### ISSUE THREAD

**Issue by darkwing** [firefox-devtools/debugger#7712]
At present we have different places where we calculate the name of a source.  While we have a few useful utility functions for getting a source's file name, we are currently loose with our "(index)" logic.  Example:

<img width="1288" alt="indexmadness" src="https://user-images.githubusercontent.com/46655/51011632-e8c5f380-151e-11e9-92e5-73ec7878dfb3.png">

In an ideal world, I'd love if `Source` objects had a `displayName` or likewise property so we didn't have a need for different logic.

**Comment by ravefalcon92** [comment]
@darkwing: I'm not seeing the issue in my build of Firefox. Can you confirm if this is the case on your end? I'm wondering if it's possible a recent commit fixed the issue.

<img width="1007" alt="screen shot 2019-02-26 at 5 23 00 pm" src="https://user-images.githubusercontent.com/21224637/53458549-76847200-39eb-11e9-9e2b-182ec5d8bfcd.png">

**Comment by darkwing** [comment]
Ooops, sorry @ravefalcon92, I fixed it a week back: https://github.com/firefox-devtools/debugger/commit/f65d249c89f8b118188b9367c66d0f6bfee3bcbe 

Sorry for not closing this!
