### ISSUE TITLE
[testing] test project directory root

### ISSUE THREAD

**Issue by jasonLaster** [firefox-devtools/debugger#7724]
We should write a mochitest for project directory root that tests

1. adding a root
2. refining the root
3. clearing the root

**Comment by pradeepgangwar** [comment]
@jasonLaster can i try this one?

**Comment by janodvarko** [comment]
Firefox Developer Tools (including Debugger tool) development is now entirely happening in Bugzilla and new issues should be reported here: https://bugzilla.mozilla.org/enter_bug.cgi?product=DevTools&component=Debugger

Please reopen this report in Bugzilla if it's still valid.

Honza
