### ISSUE TITLE
General debugger slowness on a large(ish) project

### ISSUE THREAD

**Issue by salomvary** [firefox-devtools/debugger#7734]
I have a large(ish) web application (The App) that is nearly impossible to debug using the Debugger shipped with the Firefox Developer Tools. Examples of slow experience: stopping on breakpoint, stepping in the debugger, inspecting variables. I have no performance issues when debugging using the debugger of the Chrome Developer tools.

As recommended in the DevTools Slack I collected performance profiles using https://perf-html.io/.

Here is my detailed setup for collecting the performance profiles:

- Clone debugger.html master (e8a729f7a9d025367d3b40c01774fe5dc1a6c2ff) and run locally using `yarn start`
- Use Firefox 64.0.2 (64-bit)
- Start Firefox with a new profile `/Applications/Firefox.app/Contents/MacOS/firefox-bin -P profiler`
- Install the https://perf-html.io/ addon
- Open the debugger in Firefox at http://localhost:8000/
- Launch a Firefox window from the Debugger (click on "Launch Firefox" button) 
- Load The App to debug in the new Firefox tab

Using this setup I collected two performance profiles:

First one is "stepping between breakpoints":

- Load The App
- Set two breakpoints in the app on two subsequent lines that are executed at the first load
- Reload The App and wait until stopped on the first breakpoint
- Start the profiler addon
- Click continue in the debugger
- Wait until stopped on the second breakpoint
- Stop profiling

Result: https://perfht.ml/2QTUxsW

The second one is "reload and stop on the first breakpoint":

- Get to the second breakpoint as discussed above
- Start the profiler
- Reload The App
- Wait until stopped on the first breakpoint
- Stop profiling

Result: https://perfht.ml/2QRba8T

I hope this is useful. Happy to provide more information or performance traces.

**Comment by jasonLaster** [comment]
Thanks for the detailed write-up. I'll take a look

**Comment by nchevobbe** [comment]
@salomvary thanks for the report! I see that you're using Firefox 64, and I think some improvements landed lately. Would you be able to test with Firefox Nightly and tell us if you experience the same slowness?

**Comment by jasonLaster** [comment]
Hi @salomvary could you try recording the profiles in firefox nightly:

1. open firefox nightly
2. install perf.thml addon
3. go to page, open native devtools, start recording

that will be help us record what firefox is doing in the browser for stepping/reloading

**Comment by salomvary** [comment]
@jasonLaster I created some more preformance and recordings recordings from Firefox 64 and Firefox Nightly, native devtools in both. Also added a screen recording from Chrome Dev Tools which seems to be way faster.

Nightly:
- Reload to the first breakpoint: https://perfht.ml/2HoLDnO
- Step from first breakpoint to second breakpoint: https://perfht.ml/2HmRbiQ
- Screen recording: https://www.youtube.com/watch?v=ge7YGsCGBZA&feature=youtu.be

Stable (64):
- Reload to the first breakpoint: https://perfht.ml/2HnbEUG
- Step from first breakpoint to second breakpoint: https://perfht.ml/2HjqITa
- Screen recording: https://www.youtube.com/watch?v=J_tdxAgwxBs&feature=youtu.be

Chrome screen recording: https://www.youtube.com/watch?v=qNlAE5vS2aM&feature=youtu.be

Might be useful to know that the most of the application's JS is served by Webpack as a large bundle (main.js, about 14MB uncompressed).

**Comment by jasonLaster** [comment]
One area we can definitely fix is the 1s we take in onFrames getting the sourceMapURL. Each frame takes about 40ms because the engine has to search the bundle, If we memoize the field we would only have to do that once.

<img width="1680" alt="screen shot 2019-01-20 at 9 43 04 am" src="https://user-images.githubusercontent.com/254562/51440730-18e86180-1c98-11e9-9f92-4b93ac141c8c.png">


```diff
diff --git a/devtools/server/actors/source.js b/devtools/server/actors/source.js
index 02fa3f38f1e7..13d4f13b908a 100644
--- a/devtools/server/actors/source.js
+++ b/devtools/server/actors/source.js
@@ -187,6 +187,15 @@ const SourceActor = ActorClassWithSpec(sourceSpec, {
     return this._addonPath;
   },

+  get sourceMapURL() {
+    if (this._sourceMapURL) {
+      return this._sourceMapURL;
+    }
+
+    this._sourceMapURL = source ? source.sourceMapURL : null
+    return this._sourceMapURL;
+  },
+
   get isCacheEnabled() {
     if (this.threadActor._parent._getCacheDisabled) {
       return !this.threadActor._parent._getCacheDisabled();
@@ -209,7 +218,7 @@ const SourceActor = ActorClassWithSpec(sourceSpec, {
       addonID: this._addonID,
       addonPath: this._addonPath,
       isBlackBoxed: this.threadActor.sources.isBlackBoxed(this.url),
-      sourceMapURL: source ? source.sourceMapURL : null,
+      sourceMapURL: this.sourceMapURL,
       introductionUrl: introductionUrl ? introductionUrl.split(" -> ").pop() : null,
       introductionType: source ? source.introductionType : null,
     };
```

**Comment by jasonLaster** [comment]
`setBreakpointAtGeneratedLocation` takes 431ms  [url]. I'm curious if we can save time on the engine side?

[url]:https://perf-html.io/public/194ac99987a128144f2c7fc240ef768c9e7d22be/stack-chart/?globalTrackOrder=5-6-7-8-0-1-2-3-4&hiddenGlobalTracks=1-2-3-5-6-8&localTrackOrderByPid=36465-1-0~36469-0~&range=3.2209_4.2703~3.2209_3.9746&thread=5&v=3

**Comment by jasonLaster** [comment]
One additional idea is to tighten the getUrl cache map:

this way we don't re-compute the URL every time the source reference changes.

The profile is especially interesting because the parse call is cross compartment [perf](https://perf-html.io/public/b2ce14d34bd3f6badc2bdddab2a771e090927272/stack-chart/?globalTrackOrder=4-5-6-0-1-2-3&hiddenGlobalTracks=1-2-4-6&implementation=js&localTrackOrderByPid=37776-1-2-0~37781-0~37779-0~37778-0-1~&range=9.6058_10.8461~9.6934_10.2713&thread=0&v=3)

```diff
diff --git a/src/utils/sources-tree/getURL.js b/src/utils/sources-tree/getURL.js
index 42e1f5227..a3a9fda18 100644
--- a/src/utils/sources-tree/getURL.js
+++ b/src/utils/sources-tree/getURL.js
@@ -118,11 +118,11 @@ function _getURL(source: Source, defaultDomain: string): ParsedURL {
 }

 export function getURL(source: Source, debuggeeUrl: ?string) {
-  if (urlMap.has(source)) {
-    return urlMap.get(source) || def;
+  if (urlMap.has(source.id)) {
+    return urlMap.get(source.id) || def;
   }

-  const url = _getURL(source, debuggeeUrl || "");
-  urlMap.set(source, url);
+  const url = _getURL(source.id, debuggeeUrl || "");
+  urlMap.set(source.id, url);
   return url;
 }
```

**Comment by jasonLaster** [comment]
it also looks like `addToTree` does a lot of parsing, which should not happen because we've already computed the URLs when we added them to the tree...

[profile](https://perf-html.io/public/b2ce14d34bd3f6badc2bdddab2a771e090927272/stack-chart/?globalTrackOrder=4-5-6-0-1-2-3&hiddenGlobalTracks=1-2-4-6&implementation=js&localTrackOrderByPid=37776-1-2-0~37781-0~37779-0~37778-0-1~&range=9.6058_10.8461~9.6934_10.2713~9.8215_9.9106&thread=0&v=3)

**Comment by salomvary** [comment]
@jasonLaster 

>    it looks like nightly is slower (15s vs 19s) is that correct or did i get the profiles mixed up?

When in doubt, perf-html shows the browser version... But I would not draw too much conclusion on precise time values from two profiles and where human factor is also involved (I have to click both in the debugger and the profiler several times to produce these).

>    could you re-record the profiles with workers enabled? DOM-Workers need to be enabled

Re-recorded on Nightly:

- Reload to the first breakpoint: https://perfht.ml/2sEWlwp
- Step from first breakpoint to second breakpoint: https://perfht.ml/2sCj5gp

(The latter recorded no DOM Worker activity, double checked and it was turned on).

**Comment by jasonLaster** [comment]
I wonder if it is possible to improve the performance of `mapScopes` there are two areas we could look for wins:

1. on the main thread [here](https://perfht.ml/2sBEXZk)
2. on the worker in getScopes [here][h]

[h]: https://perf-html.io/public/85f89fa178aaa297f839a0296f0128e6c3c10ca0/stack-chart/?globalTrackOrder=5-6-7-8-0-1-2-3-4&hiddenGlobalTracks=1-2-3-5-6-8&hiddenLocalTracksByPid=39255-1-2-3-5-7~39260-0&implementation=js&localTrackOrderByPid=39255-8-9-0-1-2-3-4-5-6-7~39261-0~39256-0~39258-0~39260-1-2-0~&range=13.8486_17.5865&thread=7&v=3

**Comment by jasonLaster** [comment]
- [ ] memoize getURL by ID #7771
- [ ] memoize highlightText #7772

**Comment by salomvary** [comment]
@jasonLaster so I repeated the performance tests in the latest Nightly.

Full reload to the first breakpoint: https://perfht.ml/2SfXtVL

- Stopping on the first breakpoint (highlighting the line) might be faster now (happens at around 1s)
- Notice how showing the blue breakpoint markers only follow a few seconds later
- Scopes (right panel bottom) take almost 10 seconds to load

Step from the first breakpoint to the next one: https://perfht.ml/2SjjB1d

- Seeems faster than before, scopes load with little delay (max 1s)

**Comment by jasonLaster** [comment]
@salomvary could you re-test again on Nightly. We landed a new checkbox in the scopes pane for "Map Scopes". My guess is the debugger should be faster for you with that off.

**Comment by salomvary** [comment]
@jasonLaster I repeated the test on the same web application with the latest Nightly but I do not perceive any difference in speed compared to my last comment:

Full reload to first breakpoint (unfortunately the profiler no longer captures screenshots in the first few seconds): http://bit.ly/2YzaQk5

- Stopping on the first breakpoint with full reload takes 1-2 seconds
- Breakpoint markers follow a bit later
- Scopes take almost 10 seconds to load (Map Scopes checkbox OFF)

Step from the first breakpoint to the next one: http://bit.ly/2YAKnm4

**Comment by jasonLaster** [comment]
Hey @salomvary sorry for the delay. Would you mind re-testing and measuring with firefox nightly? We've landed another fix that should turn off all the computations when "map scopes" is disabled.

**Comment by jasonLaster** [comment]
I'll pre-emptively close, happy to re-open if this is not fixed
