### ISSUE TITLE
[DebugLine] occassionally the debug line is not cleared

### ISSUE THREAD

**Issue by jasonLaster** [firefox-devtools/debugger#7755]
I've found a couple times that the debug line does not go away when you resume. Some of my theories are 

1. it is no longer the selected location
2. you were currently selecting another frame, that was not the top frame
3. you resumed while viewing another document/another source...

<img width="629" alt="screen shot 2019-01-14 at 1 22 11 pm" src="https://user-images.githubusercontent.com/254562/51410172-d0169880-1b31-11e9-8dfb-4ad0bd2626e2.png">
<img width="690" alt="screen shot 2019-01-18 at 2 59 55 pm" src="https://user-images.githubusercontent.com/254562/51410177-d3118900-1b31-11e9-830f-22838295c561.png">

**Comment by jasonLaster** [comment]
Re-opening because I saw this issue yesterday. I cannot reproduce it now though, although it is some combination of stepping and viewing a different location.



<img width="1031" alt="screen shot 2019-02-11 at 3 18 07 pm" src="https://user-images.githubusercontent.com/254562/52726230-ca6d7080-2f80-11e9-804a-e3f1a7981216.png">


One thing i found this morning is that the component updates everytime a location is selected, it might be better to only change when the frame changes...


```diff
diff --git a/src/components/Editor/DebugLine.js b/src/components/Editor/DebugLine.js
index babf89fdb..84e8be6e6 100644
--- a/src/components/Editor/DebugLine.js
+++ b/src/components/Editor/DebugLine.js
@@ -41,6 +41,16 @@ function isDocumentReady(source, frame) {
 export class DebugLine extends Component<Props> {
   debugExpression: null;

+  shouldComponentUpdate(nextProps) {
+    const { frame } = this.props;
+    const { frame: nextFrame } = nextProps;
+    return (
+      (nextFrame && !frame) ||
+      (!nextFrame && frame) ||
+      (nextFrame && nextFrame.id != frame.id)
+    );
+  }
+
   componentDidUpdate(prevProps: Props) {
     const { why, frame, source } = this.props;

@@ -50,6 +60,11 @@ export class DebugLine extends Component<Props> {
     endOperation();
   }

+  componentWillUnmount() {
+    const { why, frame, source } = this.props;
+    this.setDebugLine(why, frame, source);
+  }
+
   componentDidMount() {
     const { why, frame, source } = this.props;
     this.setDebugLine(why, frame, source);
```

**Comment by jasonLaster** [comment]
After thinking about this a bit more, my hunch is that we're missing `componentWillUnmount()` in the current version so sometimes the component unmounts without clearing state.

```js  
componentWillUnmount() {
    const { why, frame, source } = this.props;
    this.clearDebugLine(why, frame, source);
  }
```

**Comment by jasonLaster** [comment]
I added a `p1` label as this is happening pretty frequently for me, which is disconcerting.

**Comment by jasonLaster** [comment]
Pinning the issue because i'd love some help trying to investigate the cause

**Comment by darkwing** [comment]
Steps to repeat:

```
1.  Add two breakpoints:

  - https://firefox-dev.tools/debugger-examples/examples/todomvc/js/views/app-view.js , line 53
  - https://firefox-dev.tools/debugger-examples/examples/todomvc/js/routers/router.js, line 25

2.  Close all sources

3.  Refresh

4.  router.js should be paused at line 16

5.  In call stack, click the second "Backbone" heading, click "start"

6.  backbone.js should open

7.  Hit resume button

8.  Continue resuming until not paused anymore

9.  Go to router.js, see line 16 still has the debug line
```
