### ISSUE TITLE
Main Thread hangs w/ glitch+debugger open in background

### ISSUE THREAD

**Issue by digitarald** [firefox-devtools/debugger#7780]
STR:
- Start a new `html-webpage` based glitch project
- Open the *Show Live* page in a new tab and open the Debugger on it
- Switch back to tab with Glitch editor
- Open the `script.js` file
- Type away and edit the file (adding a `console.log`, etc)

ER: Blissful editing with usual performance behaviour
AR: Glitch updating the JS file in the background causes 1s+ hangs (on a high end MBP) from `getSourcesByUrlInSources`

<img width="956" alt="image" src="https://user-images.githubusercontent.com/8599/51564347-debbc300-1e43-11e9-9cc1-3f9f43caff1a.png">

https://perfht.ml/2R6Cn7i

**Comment by jasonLaster** [comment]
It looks like there are two big issues:
- checkPendingBreakpoints which uses an expensive check -- [perf][p1]
- newSources which calls `updateSource` -- [perf][p2]

[p1]: https://perf-html.io/public/4d88b1d30ac40d2a2764f88ab66945f9d887b78a/calltree/?globalTrackOrder=0-1-2-3-4-5-6-7-8-9-10&hiddenGlobalTracks=1-2-3-4-5-6-7-8-9&hiddenLocalTracksByPid=6440-0-2-1~8826-0-1&implementation=js&localTrackOrderByPid=6440-1-2-0~8807-0~8479-0~8126-0-1~6442-0~8778-0-1~10623-0~8612-0~6444-0~12950-0~8826-0-1~&range=4.9218_9.9685~5.5144_6.9295&thread=0&v=3

[p2]: https://perf-html.io/public/4d88b1d30ac40d2a2764f88ab66945f9d887b78a/calltree/?globalTrackOrder=0-1-2-3-4-5-6-7-8-9-10&hiddenGlobalTracks=1-2-3-4-5-6-7-8-9&hiddenLocalTracksByPid=6440-0-2-1~8826-0-1&implementation=js&localTrackOrderByPid=6440-1-2-0~8807-0~8479-0~8126-0-1~6442-0~8778-0-1~10623-0~8612-0~6444-0~12950-0~8826-0-1~&range=4.9218_9.9685~4.9584_5.1884&thread=0&v=3

**Comment by jasonLaster** [comment]
@digitarald i could not reproduce with this example https://glitch.com/edit/#!/workable-worm

Also the profile has a lot of `checkPendingBreakpoints` did you have any breakpoints set?

**Comment by digitarald** [comment]
Just tried again in Nightly: http://bit.ly/2Wiw58G

I am using https://glitch.com/edit/#!/seed-swamp?path=script.js:8:27 with some async functions and `console.trace` statements.

**Comment by jasonLaster** [comment]
@digitarald the perf link isn't opening for me...

**Comment by digitarald** [comment]
> @digitarald the perf link isn't opening for me...

Try a hard refresh, this fixed it for me.

**Comment by julienw** [comment]
Hard refresh should never be necessary, especially now that we have this nifty reload notification. Moreover we (should) reload automatically if we see this error and there's an update.

Basically a hard refresh avoids the service worker, so it may seem to work when the service worker hasn't downloaded an update yet, but this is never a good fix for perf-html :)

I believe this happened because @digitarald doesn't use perf-html.io to capture, but maybe another URL (like master.perf-html.io?)

**Comment by julienw** [comment]
_Or_ the update wasn't finished yet :)

**Comment by digitarald** [comment]
Updated link that works for me: http://bit.ly/2Wiw58G

**Comment by jasonLaster** [comment]
thanks. I'm still not reproducing the slowdown, which makes sense given i don't see `checkPendingBreakpoints` in my profile either. http://bit.ly/2TlZHjs

**Comment by digitarald** [comment]
Closing for now as we don't have a working STR; will re-open if I see this again.
