### ISSUE TITLE
Top level getters of Objects can not be invoked in source panel

### ISSUE THREAD

**Issue by Fubuchi** [firefox-devtools/debugger#7783]
Top level getters of Objects (I don't know if it is what we call them) can not be invoked in sources panel regardless of their scopes. But they can be invoked in watch expression and scopes panel.

Here is an example, I include the script from a simple index.html and load the html file in firefox then set break point for it:

```
//file script.js
var global = {
  get parentGetter() {
    return "Parents"; // invoke doesn't work
  },
  child: {
    get childGetter() {
      return "Child"; // work here
    }
  }
};
```

![image](https://user-images.githubusercontent.com/42483897/51611175-32680280-1f51-11e9-9e30-8c7d41953b5b.png)

I try to put the object into a function, the `parentGetter` still can not be invoked.
In chrome, all of getters can be invoked in source panel.

I'm sorry If there is any grammar mistake.

**Comment by nchevobbe** [comment]
mhh, my guess is that we don't update the node with the result. It may be because here `parentGetter` is a root node, which is handled differently than the other nodes.

**Comment by Fubuchi** [comment]
@nchevobbe  confirmed, I add a console log to `parentGetter` and it log to console when I invoke it.

**Comment by nchevobbe** [comment]
fixed in https://bugzilla.mozilla.org/show_bug.cgi?id=1562724
