### ISSUE TITLE
[Tracking] Event Listener Breakpoints

### ISSUE THREAD

**Issue by darkwing** [firefox-devtools/debugger#7785]
Tracking issue for the new Event Listener Breakpoints panel.

Server-side work: [Bug 1526082](https://bugzilla.mozilla.org/show_bug.cgi?id=1526082).
[Product Requirements](https://docs.google.com/document/d/1HPTnwnYydsRBRZw3XqGoiOSaMSIeHBvKRQENm4RegPI/edit#) (maintained by @digitarald).

**Comment by janodvarko** [comment]
Firefox Developer Tools (including Debugger tool) development is entirely happening in Bugzilla and new issues should be reported here: https://bugzilla.mozilla.org/enter_bug.cgi?product=DevTools&component=Debugger

Honza
