### ISSUE TITLE
[Tracking] DOM Mutation Breakpoints

### ISSUE THREAD

**Issue by darkwing** [firefox-devtools/debugger#7786]
Sub-issues for the new DOM mutation breakpoints panel will be tracked here.

**Comment by janodvarko** [comment]
Firefox Developer Tools (including Debugger tool) development is entirely happening in Bugzilla and new issues should be reported here: https://bugzilla.mozilla.org/enter_bug.cgi?product=DevTools&component=Debugger

Honza
