### ISSUE TITLE
Unable to restore .scss from webpack file

### ISSUE THREAD

**Issue by voordev** [firefox-devtools/debugger#7792]
For learning purposes! 
Im trying to look how components are build on a gatsby react based site named clubhouse.io
The webpack is available but im unable to restore the scss files they are not populated with CSS but with code like in below example. There are multiple scss files also.
The 2nd one has the following content:

```
// classnames-loader: automatically bind css-modules to classnames
        var classNames = require("!../../../node_modules/classnames/bind.js");
        var locals = require("!!../../../node_modules/mini-css-extract-plugin/dist/loader.js??ref--13-1!../../../node_modules/css-loader/index.js??ref--13-2!../../../node_modules/postcss-loader/lib/index.js??postcss-3!../../../node_modules/sass-loader/lib/loader.js??ref--13-4!./Row.scss");
        var css = classNames.bind(locals);
        for (var style in locals) css[style] = locals[style];
        module.exports = css;
```

Would it be possible to somehow get the css sources of a component to see how things are build upon. This would help me a lot understanding how to do styling.

<img width="1136" alt="screenshot 2019-01-24 at 10 22 38" src="https://user-images.githubusercontent.com/34578028/51668425-7ba46a80-1fc2-11e9-92b7-c6ac65bc59fe.png">

**Comment by loganfsmyth** [comment]
I'm not totally following what the issue is here, but most likely this will behave differently in more recent version of the debugger. If you're still having issues, please file a new issue in Bugzilla.
