### ISSUE TITLE
Syntax highlighting option disabled prevents workaround

### ISSUE THREAD

**Issue by digitarald** [firefox-devtools/debugger#7799]
STR:
- Open Debugger on Github
- Open the `frameworks-*` file
- Right-click tab

ER: Pretty print option available
AR: Pretty print disabled

The file should have a toolbar to pretty print (#2782 or some of the others where we tried fixing that), but since that is gone, disabling the option closes the last avenue to force pretty print.

<img width="565" alt="image" src="https://user-images.githubusercontent.com/8599/51727376-ac1af180-2020-11e9-9101-6e4bd676da21.png">

**Comment by digitarald** [comment]
@loganfsmyth did anything change here recently that would disable the option?

**Comment by jasonLaster** [comment]
The reason we don't let you pretty print is that the file has a source map

<img width="985" alt="screen shot 2019-01-25 at 9 02 12 am" src="https://user-images.githubusercontent.com/254562/51750408-fe3f2f80-207f-11e9-8e06-e34e332dcd82.png">

Here are the original sources for the file

<img width="626" alt="screen shot 2019-01-25 at 9 06 01 am" src="https://user-images.githubusercontent.com/254562/51750588-7f96c200-2080-11e9-930d-6f96a4d7a9f4.png">
<img width="636" alt="screen shot 2019-01-25 at 9 05 47 am" src="https://user-images.githubusercontent.com/254562/51750589-7f96c200-2080-11e9-86ed-4805c2ef7b15.png">


- The reason we dont let you pretty print a generated source is that then a location in the generated source would point to two original locations (pretty file, original file)
- It would be nice if we gave users the option to filter the source tree and see the original sources... It is kind of a niche feature, but could be helpful in some contexts.

**Comment by digitarald** [comment]
This seems arbitrary, as all the sources 404; so the source map is just used for error mapping and disabling pretty print in this case doesn't make sense.

Maybe I am simplifying, but force pretty printing should still be available and discard the source map.

**Comment by jasonLaster** [comment]
@digitarald i think that makes sense. We already have logic the strips the sourceMapURL if that 404s... 

this is a thorny problem

**Comment by darkwing** [comment]
What's our decision here?  Always, always showing the pretty print button regardless of sourcemap?

**Comment by digitarald** [comment]
The pretty print _button_ has its own issues atm. For this issue we should at least show the Pretty Print _menu_.

**Comment by digitarald** [comment]
ping @darkwing . Could we maybe make this available?
