### ISSUE TITLE
Improve the regexp for React library

### ISSUE THREAD

**Issue by julienw** [firefox-devtools/debugger#7807]
Currently the regexp to detect the React library is very simple:
https://github.com/devtools-html/debugger.html/blob/192cbd161a136bb42ff8bd9116a052465fa917a2/src/utils/pause/frames/getLibraryFromUrl.js#L24-L25

This means it matches lots of 3rd-party libraries too, especially `react-contextmenu` `react-transition-group` `react-splitter-layout`. I believe React is only `react` and `react-dom` so maybe a good regexp could be:
```
 pattern: /(node_modules\/(?:react|react-dom)/)|(react(\.[a-z]+)*\.js$)/
```
(in case this isn't very visible, there's an added `/` for the `node_modules` part)

**Comment by julienw** [comment]
This is what happens in the console:
![console screenshot](https://user-images.githubusercontent.com/454175/51753346-cce35580-20b9-11e9-9733-5c8d7a00c4d9.png)
All the seemingly React stack is actually in `react-contextmenu`.

**Comment by amanriquez** [comment]
Hello, newbie here looking for first issues (just made my first pull request at common voice/sentence collector, changed two labels..). Wondering if this was just as easy, I don't think I can make a better regex than yours, so if I just go in and plug in the one you made that'd work? it doesn't need a ^ at the beginning?

**Comment by jasonLaster** [comment]
Go for it. There are some nice tests too so that would help

**Comment by amanriquez** [comment]
Hey, I tried the suggested regex but got this error:

      /home/arnulfo/debugger/debugger.html/src/utils/pause/frames/getLibraryFromUrl.js: Unexpected token, expected , (25:49)

        23 |   {
        24 |     label: "React",
      > 25 |     pattern: /(node_modules\/(?:react|react-dom)/)|(react(\.[a-z]+)*\.js$)/
           |                                                  
        26 |   },
        27 |   {
        28 |     label: "Immutable",

There is an  ^ pointing at the ) after dom)/ and the two last '\' are highlighted as well. Also sorry, should I be commenting on slack instead of here?

**Comment by darkwing** [comment]
How is this going @amanriquez ?  Still working on it?

**Comment by amanriquez** [comment]
I am sorry I had a personal situation and couldn't get to this for the past weeks, I think I better /unclaim this for now, I apologize for the inconvenience and will come help when I have more time and knowledge.
