### ISSUE TITLE
[Footer] Compressing the editor pane causes text to leave the footer 

### ISSUE THREAD

**Issue by derek-li** [firefox-devtools/debugger#7840]
Steps to reproduce:
1. Black box the source
2. Shorten the editor pane

Problem is more noticeable in Chrome than Mozilla 

Demo:
https://gyazo.com/5d568df7fc3134366f76256cb58b1580

**Comment by yulireyji** [comment]
Hello! I would like to help with this issue

**Comment by darkwing** [comment]
How's this going @yulireyji ?  Anything I can help with?

**Comment by darkwing** [comment]
@yulireyji We can remove that text from the footer 👍

**Comment by darkwing** [comment]
How is this going @yulireyji ?  Can I help with anything?

**Comment by yulireyji** [comment]
Hi, it´s ok, today i upload the changes sorry for delay

**Comment by darkwing** [comment]
Awesome!  Please submit a pull request so I can have a look.  Thank you!
