### ISSUE TITLE
Switch delete button for watch expressions to show on hover

### ISSUE THREAD

**Issue by digitarald** [firefox-devtools/debugger#7868]
Same behavior as breakpoints. Impact of not doing it is loosing 48 pixels (close button + margins).

Possibly a good first bug, @darkwing ?

**Comment by darkwing** [comment]
I think we should consider accessibility here; using hover for a task as important as removing a breakpoint or expressions isn't friendly to keyboard users.

**Comment by digitarald** [comment]
As this is already used for breakpoints, how is the a11y question solved there @darkwing ?

**Comment by digitarald** [comment]
Looks like it doesn't.

This could be solved by making the close button element appear when the main element or a part of it is focused (using `:focus-within`); so tapping through the element shows all options.

**Comment by keerthanak17** [comment]
I'd like to claim this issue if no one else is working on it!

/claim

**Comment by keerthanak17** [comment]
Hi @digitarald , could you tell how I can find the file/ where in the application this issue is? I'm having trouble finding this issue to analyse/ fix it. Thanks!

**Comment by darkwing** [comment]
Hello @keerthanak17 !  The file most important will be `src/components/SecondaryPanes/Expressions.js`, where the JavaScript/HTML is.  There's a `Expressions.css` file where you'll need to add the CSS to show and hide the close button.  A good file to look at will be `src/components/SecondaryPanes/Breakpoints/Breakpoint.js`, where we already implement this functionality. 👍

**Comment by keerthanak17** [comment]
Awesome! Let me do that and get back to you. Thank you @darkwing

**Comment by keerthanak17** [comment]
I think I got this. Do I just give a PR for adding it into the code or is there something else I'm missing?

**Comment by darkwing** [comment]
You can submit a pull request and we'll have a look! :)

**Comment by fvsch** [comment]
For the record I'm generally against hiding UI and revealing it on hover. I've argued against it for breakpoints in #8042.

Not sure freeing up space is such a big concern. Also, if we do end up using the freed up space to display text, that means that on hover we overlay the remove button on top of that text, which is messy.

> Using hover for a task as important as removing a breakpoint or expressions isn't friendly to keyboard users.

This can be worked around by not hiding the button with `display: none`, and using both :focus (or :focus-within) and :hover to reveal it.

```css
.the-row-container {
  position: relative;
  overflow: hidden;
}
.the-close-button {
  /* visually hide by default */
  top: -100px;
}
.the-row-container:hover .the-close-button,
.the-close-button:focus {
  top: 0;
}
```

(Using `opacity: 0` might be an option too, but I'd check that the button doesn't disappear from the accessibility tree and that keyboard navigation does work in Firefox and Chrome.)

**Comment by darkwing** [comment]
@chujunlu This would be great for you now that you have completed the breakpoints behavior! 👍

**Comment by chujunlu** [comment]
@darkwing Hi David, I think I have a solution. But I saw Florens' PR #8083 added changes to a CSS class I plan to edit. It's better to wait until the PR gets merged before I submit a new PR, right?
