### ISSUE TITLE
Improve UI implementation of EventListeners list

### ISSUE THREAD

**Issue by fvsch** [firefox-devtools/debugger#7879]
The UI spec: https://mozilla.invisionapp.com/share/H3PYO9EMC9D#/screens/340771972_Event_Breakpoints_1

A few issues:
- we have strange alignment of icons, checkboxes, etc.
- we don't respect the metrics outlined in the spec (horizontal rhythm, 20px-tall rows)
- the arrow icon should be a button so that it can be focusable; we probably need to come up with an accessible label for those buttons too
- finally, the arrow icon is currently inside the checkbox's label, so when we click the arrow it triggers the checkbox (which we prevent in JS but it still shows some visual feedback in the UI); the button should be outside the label

I'll probably take this bug. :)

**Comment by harshlele** [comment]
hey, can i take this bug?

**Comment by fvsch** [comment]
Works for me. :)

Some things to note:
- The UI spec has a second page with metrics: https://mozilla.invisionapp.com/share/H3PYO9EMC9D#/screens/341208048
- It's best not to use fixed heights for content rows (`height: 20px`). Instead, a combination of line-height and padding may work.
- Checkboxes use their platform-specific styles. This means we can't always follow the UI spec in a pixel-perfect way because checkboxes could be 12px, 14px or 16px wide.
- The triangle icon (disclosure arrow)'s style may change when #7890 lands. But we can always rebase or adapt to those styles later on.

**Comment by harshlele** [comment]
Hey, @fvsch , about this:

> Checkboxes use their platform-specific styles. This means we can't always follow the UI spec in a pixel-perfect way because checkboxes could be 12px, 14px or 16px wide.

I think the row height not being 20px is because of the inconsistent checkbox size on different platforms. Couldn't we just set a fixed size for the checkbox on all platforms?

**Comment by fvsch** [comment]
> Couldn't we just set a fixed size for the checkbox on all platforms?

Nope. Changing the checkbox size doesn't work on all platforms. It seems to work alright on macOS, not sure on Windows, and doesn't work on Linux.

Making rows 20px should be possible nonetheless. For example, using flexbox, you could have a `display:flex; align-items:center;` container for each row, then the different elements as flex items, and the main size could come from the text label with styles like:

```
padding: 3px 0;
line-height: 14px;
```

**Comment by harshlele** [comment]
Hmm ok i made that change
