### ISSUE TITLE
[QuickOpen] syncBreakpoint.js is missing

### ISSUE THREAD

**Issue by jasonLaster** [firefox-devtools/debugger#7888]
STR: 

1. start launchpad
2. cmd+p type sync

ER: see syncBreakpoint.js
AR: it is not there

<img width="677" alt="screen shot 2019-02-05 at 5 21 27 pm" src="https://user-images.githubusercontent.com/254562/52315122-7f44d380-296a-11e9-9ec7-376009adb8de.png">

**Comment by soniasingla** [comment]
Thanks @jasonLaster for this issue, will raise PR soon :)

**Comment by soniasingla** [comment]
Hello @jasonLaster  !! Can you please guide me regarding this issue?

**Comment by soniasingla** [comment]
@jasonLaster @bomsy this issue has been fixed :smile: 
We can close this issue, thanks !!

**Comment by jasonLaster** [comment]
@soniasingla I saw the issue in Firefox nightly last night. Could you try testing there? It is somewhat flakey so sometimes works and sometimes fails.

**Comment by darkwing** [comment]
Tried this morning and I couldn't reproduce it.
