### ISSUE TITLE
`willNavigate` and `navigate`'s clearing of registered sources is not atomic with `newSource`

### ISSUE THREAD

**Issue by jswalden** [firefox-devtools/debugger#7889]
While working on a JS engine patch (specifically, to change JS column numbers from being counts of code _units_ to being counts of code _points_, a mostly necessary prerequisite to allowing us to directly compile UTF-8 source text), I made a bunch of devtools tests start failing.

One of the first tests I picked (there are a bunch; some might be me, some definitely aren't other than by just making races happen more) was `devtools/client/debugger/new/test/mochitest/browser_dbg-sourcemaps-reload.js`.  That test begins

```js
  const dbg = await initDebugger("doc-minified.html");

  await navigate(dbg, "sourcemaps-reload/doc-sourcemaps-reload.html", "v1.js");

  await selectSource(dbg, "v1.js");

  await addBreakpoint(dbg, "v1.js", 6);

  let breakpoint = getBreakpoints(dbg)[0];
  is(breakpoint.location.line, 6);
```

and the failure I was observing was that `breakpoint` in that final line was `undefined`.  _That_ problem, was because `addBreakpoint` apparently was not adding the breakpoint.  From log output (copied from an `rr` run, hence some ignorable junk-prefixing):

```
 3:51.81 INFO Console message: [JavaScript Error: "TypeError: sourceThreadClient is undefined" {file: "resource://devtools/client/debugger/new/src/client/firefox/commands.js" line: 163}]
 4:01.55 GECKO(3186) [rr 3200 340306]
 4:01.54 INFO Removing tab.
 4:01.55 GECKO(3186) [rr 3200 340310]
 4:01.55 INFO Waiting for event: 'TabClose' on [object XULElement].
 4:01.93 GECKO(3186) [rr 3200 340736]
 4:01.93 INFO Got event: 'TabClose' on [object XULElement].
 4:02.20 GECKO(3186) [rr 3200 341109]
 4:02.19 INFO Tab removed and finished closing
 4:03.18 GECKO(3186) [rr 3200 342739]
 4:03.17 FAIL A promise chain failed to handle a rejection: sourceThreadClient is undefined - stack: setBreakpoint@resource://devtools/client/debugger/new/src/client/firefox/commands.js:163:9
addBreakpointPromise@resource://devtools/client/debugger/new/src/actions/breakpoints/addBreakpoint.js:60:40
async*addBreakpoint/<@resource://devtools/client/debugger/new/src/actions/breakpoints/addBreakpoint.js:159:27
thunk/</</<@resource://devtools/client/debugger/new/src/actions/utils/middleware/thunk.js:21:45
bindActionCreator/<@resource://devtools/client/shared/vendor/redux.js:644:12
addBreakpoint@chrome://mochitests/content/browser/devtools/client/debugger/new/test/mochitest/helpers.js:761:3
@chrome://mochitests/content/browser/devtools/client/debugger/new/test/mochitest/browser_dbg-sourcemaps-reload.js:34:9
Async*Tester_execTest/<@chrome://mochikit/content/browser-test.js:1108:34
async*Tester_execTest@chrome://mochikit/content/browser-test.js:1099:16
nextTest/<@chrome://mochikit/content/browser-test.js:997:9
SimpleTest.waitForFocus/waitForFocusInner/focusedOrLoaded/<@chrome://mochikit/content/tests/SimpleTest/SimpleTest.js:803:59
Rejection date: Mon Feb 04 2019 13:35:32 GMT-0800 (Pacific Standard Time) - false == true - JS frame :: resource://testing-common/PromiseTestUtils.jsm :: assertNoUncaughtRejections :: line 257
Stack trace:
resource://testing-common/PromiseTestUtils.jsm:assertNoUncaughtRejections:257
chrome://mochikit/content/browser-test.js:nextTest:747
chrome://mochikit/content/browser-test.js:testScope/test_finish/<:1410
chrome://mochikit/content/browser-test.js:run:1347
```

So `sourceThreadClient` was `undefined`.  Initially I assumed the fault was in my patch, and I did some running under `rr`.  Then at some point I tried doing a run under `rr` _without_ my patch, to compare -- and I found the test still failed!  At this point some sort of race seemed likely.

I did some source inspection and a good deal of Searchfoxing through callers (not the easiest task given it's JS and not C++ or Rust 🙁 and also because the module lookup path goo doesn't clearly map onto the mozilla-central directory structure) and concluded that `addBreakpoint.js:addBreakpointPromise` was where the breakpoint-setting didn't work.  So that would be the first place to inspect.  I started adding calls to `Math.sin` passing a constant string as first argument, then subsequent arguments being values I wished to inspect.  (And in the test itself, so I could easily start looking at stuff very early on.)  `Math.sin` called without one nice number argument isn't JITted, so breaking on `js::math_sin` would let me examine values and state at compile-time-identified locations.  (And with the right SpiderMonkey incantations, _in principle_ I could get more data if really necessary.  Or just edit, rebuild, record, replay again.)  They'd also be reasonable places to continue forward/backward from/to, to dig into things.

I did an `rr` recording run like so:

```
./mach mochitest \
  --debugger /home/jwalden/moz/rr/obj/bin/rr \
  --debugger-args '--mark-stdio record' \
  devtools/client/debugger/new/test/mochitest/browser_dbg-sourcemaps-reload.js
```

(`--mark-stdio` causes `rr` to print out process id/event numbers, for easier replaying.)

Then to replay/debug stuff, I did

```
~/moz/rr/obj/bin/rr replay --onprocess=6085 --goto=276940
```

where `6085` and `276940` correspond to numbers from output of recording:

```
...
 2:39.55 INFO Toolbox opened and focused
 2:39.58 GECKO(6071) [rr 6085 276940]
 2:39.57 INFO Navigating to sourcemaps-reload/doc-sourcemaps-reload.html
...
```

that location being one definitely before any test-relevant stuff could execute, when I could install my `js::math_sin` breakpoint then continue.

Upon breaking on `js::math_sin`, these are a few of the sorts of commands I used to inspect stuff.

```
(rr) # print first argument (skipping Math.sin and this)
(rr) p vp[2]
$3 = $JS::Value("before navigated")

(rr) # print an object argument
(rr) p vp[4]
$69 = $JS::Value((JSObject *) 0x3fb5d0589af8 [object Object])

(rr) # dump object structure incl. properties/their values
(rr) # can also slot in ((JSObject*) 0x3fb5d05899e8)->dump()
(rr) # to print out objects by pointer from other spew
(rr) p vp[4].toObject().dump()
object 3fb5d05899e8
  global 1bf7d7a8b420 [Sandbox]
  class 7f5aacbbf708 Object
  group 96ae025fac0
  flags:
  proto <Object at 1bf7d7afb780>
  properties:
    "server1.conn0.child1/source27/originalSource-c5b88a9c040b2492cea4e832033debf0": <Object at 2b36a4d4d460> (shape 22546e1c52b8 enumerate slot 0)
    "server1.conn0.child1/source27/originalSource-f7390b5e476d7d47c072d475853f9c80": <Object at 3fb5d0589af8> (shape 22546e1c5330 enumerate slot 1)

(rr) # dump an object that the above displays as proxy/wrapper
(rr) p ((js::ProxyObject*)&vp[3].toObject())->target()->dump()
object 2b36a4d4d780
  global 1bf7d7a8b420 [Sandbox]
  class 7f5aacbbf708 Object
  group 96ae025fb20
  flags: hasShapeTable
  proto <Object at 1bf7d7afb780>
  properties:
    "id": JSString* (2eb82d6ed60) = Latin1Char * (7f5a81fa2980) = "server1.conn0.child1/source27/originalSource-f7390b5e476d7d47c072d475853f9c80" (shape 3caebf917740 enumerate slot 0)
    ...

(rr) # dump stack trace in a nice format
(rr) p DumpJSStack()
...trace omitted...

(rr) # dump stack trace in a less-nice format
(rr) p js::DumpBacktrace(cx)
...trace omitted...

(rr) # learn about the currently-executing bytecode in interpreted code
(rr) p js::DumpPC(cx)
...bytecode info (often including searchable names) omitted...
```

Looking at the `setBreakpoint` code already identified, the error seemed to be that a `sourceId` that putatively exists, actually *didn't*.  Prior logging indicated the given id once existed, just by *this* lookup time it didn't.  (I verified this using `Math.sin` calls inside `newSources.js:newSources`, as the place where sources were added.)

How to explain how the given id *disappeared*?  In normal code that does things mutably (note carefully that I am throwing shade here), a data watchpoint and `reverse-continue` would do the trick.

But React is immutable state and all.  So I set a data watchpoint on the first word of the `state.sources.sources` object (the literal spelling of `getSources(state)`) using `p (uintptr_t*) &vp[3].toObject()` then `watch *$n` for whatever dollar-variable was used for it.  Then I `reverse-continue`d to its setting.  I had to do this through moving GCs, sometimes, to get to the original allocation site -- deleting the old watchpoint, adding a new one on the original source location of the object pre-move.

Eventually I reached something like a call to `js::NewObjectOperation` -- an ultimate creation site.  This function corresponded to a call from the interpreter, so `js::DumpPC(cx)` after going up a few frames would point out pertinent source (with bits of self-hosted code inlined into it, mostly for object-spread code).  Generally that pointed at `sources.js:updateSources`, and more `Math.sin` could be used to point out a prior `sources` object whose creation could be reverse-breakpointed.  (Or SpiderMonkey arcana like `p activation.regs().fp()->unaliasedFormal(<N>, js::DONT_CHECK_ALIASING)` or `p activation.regs().fp()->envChain_->dump()` could be used, if I could go up frames to a `js::Interpret` frame.)

Repeat that a couple times, and eventually I get back to the creator of the `sources` object with the missing id as `sources.js:initialSourcesState`.  (Which only makes sense, really.)  And from there, a backtrace with middleware garbage and self-hostingy bits omitted

```
(rr) p DumpJSStack()
0 initialSourcesState() ["resource://devtools/client/debugger/new/src/reducers/sources.js":56:4]
    this = [object Object]
1 update(state = [object Object], action = [object Object]) ["resource://devtools/client/debugger/new/src/reducers/sources.js":160:23]
...gobs of middleware...
9 navigate/<() ["resource://devtools/client/debugger/new/src/actions/navigation.js":62:4]
13 willNavigate/<() ["resource://devtools/client/debugger/new/src/actions/navigation.js":51:4]
14 next(val = undefined) ["self-hosted":1210:8]
    this = [object Generator]
 ```

indicates that a `willNavigate` calls `navigate` which blows stuff away.  So I added more `Math.sin` calls inside those functions.

At this point @jasonLaster indicated over IRL that the right thing to look at/`Math.sin`-breakpoint on, would be `events.js:newSource`.  We did that and discovered that for a `willNavigate` looking like this:

```js
export function willNavigate(event: Object) {
  Math.sin("willNavigate called", event);
  return async function({ dispatch, getState, client, sourceMaps }: ThunkArgs) {
    Math.sin("willNavigate thunk enter", getState(), getState().sources.sources);
    await sourceMaps.clearSourceMaps();
    Math.sin("willNavigate thunk maps cleared", getState(), getState().sources.sources);
    clearWasmStates();
    clearDocuments();
    clearSymbols();
    clearASTs();
    clearScopes();
    clearSources();
    Math.sin("willNavigate thunk", event, navigate.toSource());
    dispatch(navigate(event.url)); // this calls initialSourcesState()
  };
}
```

we would hit `willNavigate thunk enter`, start `await`ing on source maps clearing (introducing a sequence point where we're halfway in one state and half in another), _then hit `events.js:newSource` to do_

```
[ACTION] ADD_SOURCES  - {"type":"ADD_SOURCES","sources":[{"id":"server1.conn0.child1/source27","thread":"server1.conn0.child1/context22","url":"http://example.com/browser/devtools/client/debugger/new/test/mochitest/examples/sourcemaps-reload/v1.bundle.js","relativeUrl":"http://example.com/browser/devtools/client/debugger/new/test/mochitest/examples/sourcemaps-reload/v1.bundle.js","isPrettyPrinted":false,"isWasm":false,"sourceMapURL":"v1.bundle.js.map","introductionUrl":null,"isBlackBoxed":false,"loadedState":"unloaded"}]}
```

and then proceed to run through all of `newSources.js:newSource` and _then_ return to `willNavigate thunk maps cleared` having just blown away the added source.  Then later, when the source for "v1.js" (an original source) gets looked up, an attempt is made to get the corresponding generated source that was added then blown away, it doesn't exist in the store, and then you get the `sourceThreadClient` error and no breakpoint and the thrown `breakpoint is undefined` exception.

(Oh, and also `source-maps.js:getGeneratedLocation` if the `!generatedSource` condition ends up being true will return an original location which obviously makes things very dumb.  The same is true of `source-map.js:getGeneratedLocation` if the `!map` condition ends up true.  These are separate problems, that once we go off the rails _here_ we will run into.)

The ultimate solution appears to be to change `await sourceMaps.clearSourceMaps();` to simply `sourceMaps.clearSourceMaps();`.  Don't `await` that, just clear synchronously and continue on.

#7883 has been filed as a PR for this, but it was requested that I write down the steps and logic and reasoning and in-`rr` debugging operations that got me to this point -- because someone else is probably going to want to do something along these lines again at a later time, and it might be helpful to have some chicken scratch written down somewhere to use again.

**Comment by janodvarko** [comment]
"will-navigate" and "navigate" will be replaced by different events (due to Fission related refactoring)
See more here: https://bugzilla.mozilla.org/show_bug.cgi?id=1632141

Closing this report.

Also, Firefox Developer Tools (including Debugger tool) development is entirely happening in Bugzilla and new issues should be reported here: https://bugzilla.mozilla.org/enter_bug.cgi?product=DevTools&component=Debugger

Honza
