### ISSUE TITLE
[Log Point] messages should be prefixed and nested

### ISSUE THREAD

**Issue by jasonLaster** [firefox-devtools/debugger#7917]
It would be really nice if we added some context to the typical message that  documents the control flow. These are things i think most engineers do already when logging, but we could simplify. In the example below `// LOG` refers to a log point 

```js
function foo(a) {
  // LOG "starting", { a }
  bar(a);
  bar(a);
  // LOG "ending", { a }
}

function bar(a) {
  const name = `yo ${a}`
  // LOG name
}
```

#### Console Output

> `foo(2);`
> **foo** starting, `{ a: 2}`
>  ..   **bar** yo 2
>  ..   **bar** yo 2
> **foo** ending, `{ a: 2}`

**Comment by jasonLaster** [comment]
@soniasingla i think this feature requires server-side changes

here's where log points are implemented on the server
https://searchfox.org/mozilla-central/source/devtools/server/actors/breakpoint.js#214

here are some [docs](https://developer.mozilla.org/en-US/docs/Mozilla/Developer_guide) on getting started.

**Comment by janodvarko** [comment]
Firefox Developer Tools (including Debugger tool) development is now entirely happening in Bugzilla and new issues should be reported here: https://bugzilla.mozilla.org/enter_bug.cgi?product=DevTools&component=Debugger

Please reopen this report in Bugzilla if it's still valid.

Honza
