### ISSUE TITLE
Always render the source editor footer (even if empty)

### ISSUE THREAD

**Issue by fvsch** [firefox-devtools/debugger#7920]
I'm noticing that the source editor footer appears with a delay in some situations. This creates a layout change that is not very pleasing visually and may also incur a perf cost (browser has to do more layout work, perhaps impacting CodeMirror with a high cost for long sources?).

Steps to reproduce with Launchpad:

1. Debug example http://aws-sensorweb-static-site.s3-website-us-west-2.amazonaws.com/
2. Open the `/vendor.js` source
3. Reload the Debugger page

Result:
- The Debugger's main layout appears first, with the `vendor.js` tab selected
- Source of `vendor.js` appears early, with syntax coloring
- The editor's footer appears several seconds later, with three elements: Pretty print button, Blackbox button (both off), and (line, column) text.

It seems to me we could show the footer and the line+column info almost immediately.
I don't know if there is a good reason to wait for the Pretty print and Blackbox buttons, maybe there's some work we're waiting on?

I think we could render the editor footer systematically in Debugger, even when it's empty.
I wouldn't mind having an empty footer in the WelcomeBox view, too. We could avoid having a floating button at the bottom when in vertical mode, too.

So I guess we have two issues:

1. Technical: why do we have this delay? And can we improve it?
2. UX/Layout: consider always showing the editor footer to keep the UI consistent in different situations, and avoid doing more layout work.

**Comment by jasonLaster** [comment]
> Technical: why do we have this delay? And can we improve it?

@darkwing do you know why?

> UX/Layout: consider always showing the editor footer to keep the UI consistent in different situations, and avoid doing more layout work.

I'd be open to this.

**Comment by darkwing** [comment]
I like the idea of the footer always being present, even if empty -- it makes the UI feel less quirky.

As for why, the footer returns `null` in render due to a check to see if it should render, and those checks include: `shouldShowFooter` -> 

- Is there a source?
- Is the source original?
- Is the source pretty?
- Is the source JavaScript?
- `prefs.clientSourceMapsEnabled && source.sourceMapURL`

Those look mostly innocent but they require the text source to be loaded, so that could cause delay.   `Footer` is also a connected component but it isn't connected to much

**Comment by fvsch** [comment]
Let's focus on keeping the footer visible, even if empty.

Some things to do:

1. Always render the footer's main element (`div.source-footer`)
2. In vertical mode, always render the pane expand/collapse button
3. And remove the pane expand/collapse button from WelcomeBox (which is meant to replace the one from the footer when the footer is not rendered).

**Comment by fvsch** [comment]
Thanks a bunch @derek-li :tada:
