### ISSUE TITLE
[Sources] List webextensions after web origins

### ISSUE THREAD

**Issue by fvsch** [firefox-devtools/debugger#7921]
When webextension scripts are listed (I think that's only when "Enable browser chrome and addon debugging toolboxes" is checked in DevTools preferences, maybe?), they can appear in-between web origins.

It seems we're currently sorting like this:

- Page origin first
- All other origins, sorted alphabetically (Extensions origins start with "moz-extension")

Which looks like:

![screen shot 2019-02-09 at 13 05 37](https://user-images.githubusercontent.com/243601/52520700-c7b30880-2c6c-11e9-8296-4254ae17016e.png)

Could we show the extension origins at the end of the list instead?
So that we have 3 buckets:

1. Page origin
2. Other web origins
3. Webextensions

(We may have more to fit between 1 and 2, for webpack and Angular I believe?)

**Comment by jasonLaster** [comment]
Good idea @fvsch

**Comment by nagpalm7** [comment]
@fvsch Can i give a try on this issue, Can you help me with how sources are being fetched and stored.

**Comment by fvsch** [comment]
@nagpalm7 Sure. :)
I'm not sure about how Sources work, since I mostly contribute on the UI side (CSS, SVG, bits of JS/React).

There are some guidelines in the docs:
https://github.com/devtools-html/debugger.html#next-steps
This overview might help:
https://github.com/devtools-html/debugger.html/blob/master/docs/debugger-html-react-redux-overview.md

**Comment by jasonLaster** [comment]
@nagpalm7 go for it

**Comment by nagpalm7** [comment]
Thanks /claim

**Comment by fvsch** [comment]
I can also confirm that Webpack sources are listed alphabetically.
Probably the same for Angular ones.

(Please ignore the colors in the next screenshot, I was just running some tests.)
<img alt="screenshot" width="233" src="https://user-images.githubusercontent.com/243601/52594735-80836e00-2e4c-11e9-809f-8d476aff9d4e.png">

@jasonLaster Do you know how we should order groups, if we try to group by:

- main origin
- other origins
- webextensions
- webpack/angular/other bundler

**Comment by jasonLaster** [comment]
I'd do 

* main origin
* webpack/angular/other bundler
* other origins
* webextensions

**Comment by nagpalm7** [comment]
@jasonLaster can you please mention the `type` value for all the respective sources or any unique identifier wwhich can be used to sort

**Comment by jasonLaster** [comment]
hmm, i'm not sure @nagpalm7

**Comment by nagpalm7** [comment]
@jasonLaster i am not able to figure out how to identify main origins  and other origins from path can you help me with that and also let me know all the possible bundler which I can include while reordering the tree.

**Comment by charanjit-singh** [comment]
You need to create a pipeline. before adding urlList to datastore, which sorts the list while adding.

**Comment by janodvarko** [comment]
Cloned into Bugzilla https://bugzilla.mozilla.org/show_bug.cgi?id=1695638

Firefox Developer Tools (including Debugger tool) development is now entirely happening in Bugzilla and new issues should be reported here: https://bugzilla.mozilla.org/enter_bug.cgi?product=DevTools&component=Debugger

Honza
