### ISSUE TITLE
[flow] migrate ast reducer off of immutable

### ISSUE THREAD

**Issue by jasonLaster** [firefox-devtools/debugger#7931]
There are a couple of reasons to stop using immutable in our reducers

1. it can be slower
2. it is harder to flow type. 

I started migrating our ast reducer [here] and would love some help finishing it up. I think the main thing is making sure we fix up the flow types and get all of the tests passing.

[here]: https://github.com/devtools-html/debugger.html/compare/master...jasonLaster:flow-ast?expand=1

**Comment by errietta** [comment]
I can help but may need some pointers @jasonLaster

**Comment by jasonLaster** [comment]
sounds good @errietta
