### ISSUE TITLE
[sourcemaps] webpack + uglify

### ISSUE THREAD

**Issue by jasonLaster** [firefox-devtools/debugger#7932]
There's been a long standing webpack [issue](https://github.com/webpack/webpack/issues/1194) that we should make sure we address

---

I've put together a quick repo to demonstrate the problem: https://github.com/Stuk/webpack-sourcemaps-firefox

And here's a gif of the issue in action:

![screencap](https://cloud.githubusercontent.com/assets/48019/8346824/1b3e9ada-1ab7-11e5-8848-271aa7933b2c.gif)

I've checked Uglify, and Firefox has no issues there. I've tried the different config options for `devtool`:

* `eval` - works
* `cheap-eval-source-map` - works
* `cheap-source-map` - does not work
* `cheap-module-eval-source-map` - works
* `cheap-module-source-map` - does not work
* `eval-source-map` -  works
* `source-map` - does not work

So seems like eval is file, but an external sourcemap for multiple files does not.

Any thoughts about what's going on?

I've also filed an issue on Bugzilla, in case this is a FF devtools issue: https://bugzilla.mozilla.org/show_bug.cgi?id=1177329

**Comment by loganfsmyth** [comment]
This looks to work now.
