### ISSUE TITLE
UI Quality II

### ISSUE THREAD

**Issue by darkwing** [firefox-devtools/debugger#7945]
Welcome to the Firefox DevTools Debugger quality sprint 2! 

We've prioritized the following issues to improve quality within the DevTools debugger UI.  Please grab an issue and help us make the debugger even better!

https://github.com/firefox-devtools/debugger/issues?q=is%3Aopen+is%3Aissue+label%3A%22%3Awave%3A+quality%22

**Comment by janodvarko** [comment]
Not relevant anymore, closing.

Honza
