### ISSUE TITLE
[Tabs] selecting a tab should return to the prior location

### ISSUE THREAD

**Issue by jasonLaster** [firefox-devtools/debugger#7951]
One of the nice features of editor tabs is that clicking them returns to the prior saved location. This is also a feature of codemirror documents.

This used to work too, but i believe a year or so ago, we made clicking a tab synonmous with going to line 1 column 0. We should fix this so that when we do not specify a location we return to the prior location.

This will also fix another nit, where clicking a tab flashes the first line

![](http://g.recordit.co/F4vadb4ehn.gif)

**Comment by jasonLaster** [comment]
CC https://bugzilla.mozilla.org/show_bug.cgi?id=1552061

**Comment by janodvarko** [comment]
There is Bugzilla report and it seems to be resolved.

Closing this report.
Honza
