### ISSUE TITLE
[Preview] hovering on the debug line does not leave token

### ISSUE THREAD

**Issue by jasonLaster** [firefox-devtools/debugger#7952]
One of the important features of inline preview is that mousing into a token we can preview starts the preview, and mousing out stops the preview. This logic is handled [here][h]

It looks like the debug line does not respect this behavior though.

![](http://g.recordit.co/yvMja7SXdB.gif)

[h]: https://github.com/devtools-html/debugger.html/blob/master/src/utils/editor/token-events.js#L56

**Comment by jasonLaster** [comment]
How's it going @miriambudayr. Do you have any questions?

**Comment by miriambudayr** [comment]
@jasonLaster 

I think I have found a solution. Thanks for asking!

I spent some time trying to run Mochitests but have run into some problems with the setup. Another developer reproduced the issue on his machine too so I have asked the Slack thread for some guidance. Below is the screenshot of the error. It looks like I am not able to fully download mozilla-central, so files are missing.

![screen shot 2019-02-24 at 5 19 53 pm 1](https://user-images.githubusercontent.com/35577323/53759720-9d78f300-3e86-11e9-961b-9c0fa1ebb673.png)

I would prefer to add a test before submitting, but I can also go ahead and submit what I have until I get the tests installed and working.

**Comment by AnshulMalik** [comment]
Nice @miriambudayr . Would love to see what you have come up with, please submit a PR :)

**Comment by darkwing** [comment]
This is a fun game; it's as though preview doesn't disappear unless you hit another token, but if you're sly like me, you can escape and hover all over the place without it disappearing:

![wander](https://user-images.githubusercontent.com/46655/53761177-8cca7c00-3e8a-11e9-8913-57e720217141.gif)

**Comment by darkwing** [comment]
After some playing around, the following fixes the issue:

```diff
diff --git a/devtools/client/debugger/new/src/components/Editor/Preview/index.js b/devtools/client/debugger/new/src/components/Editor/Preview/index.js
--- a/devtools/client/debugger/new/src/components/Editor/Preview/index.js
+++ b/devtools/client/debugger/new/src/components/Editor/Preview/index.js
@@ -42,8 +42,7 @@ function inPopup(e) {
 
   const pop =
     relatedTarget.closest(".tooltip") ||
-    relatedTarget.closest(".popover") ||
-    relatedTarget.classList.contains("debug-expression");
+    relatedTarget.closest(".popover");
 
   return pop;
 }

Since `debug-expression` is the entire line width, and nothing to do with the actual highlighted token, I don't believe it should play a part in `inPopup`.  I looked at the blame (https://github.com/firefox-devtools/debugger/pull/6263) and I don't see any reason why `debug-expression` should come into play.
```

**Comment by miriambudayr** [comment]
@darkwing @jasonLaster 

Yeah, this is exactly what I found too. I can go ahead and submit a PR.

**Comment by darkwing** [comment]
Great minds, @miriambudayr 👍 I can't wait to see your PR :)
