### ISSUE TITLE
[Source Tree] "External Files" doesn't appear under "Webpack" folder

### ISSUE THREAD

**Issue by soniasingla** [firefox-devtools/debugger#7955]
In reference to #7635 , the Webpack folder and items under the folder doesn't appear under the source tree.  
![screenshot_2019-02-14 debugger 1](https://user-images.githubusercontent.com/33036742/52740794-dcd7c080-2ff9-11e9-96a5-009619948e6e.png)

**Comment by darkwing** [comment]
Unfortunately I cannot reproduce
