### ISSUE TITLE
[Preview] should show "false" in the tooltip

### ISSUE THREAD

**Issue by jasonLaster** [firefox-devtools/debugger#7956]
we currently do not show a tooltip wheh you  hover on a token that evaluates to false. I think we should show one because it is confusing when you do not see it.

![](http://g.recordit.co/dQbn9fh9qH.gif)

**Comment by darkwing** [comment]
I played around with this a bit:

<img width="1378" alt="falsewtf" src="https://user-images.githubusercontent.com/46655/52873807-819af080-3115-11e9-8cb2-a9ca04d8f036.png">

Case 1 is mousing over a `false` value, Case 2 is mousing over a 'true' value.

It appears that `getPreview` from `ast.js` is receiving a `null` value for false.

**Comment by darkwing** [comment]
Reopening due to revert
