### ISSUE TITLE
firefox-dev.tools/debugger.html doesn't exist

### ISSUE THREAD

**Issue by th7nder** [firefox-devtools/debugger#7962]
After renaming to firefox-devtools link https://firefox-dev.tools/debugger.html/ stopped working.

**Comment by dhyey35** [comment]
Also the first link of README.md file links to http://firefox-dev.tools/debugger.html/

`# [debugger.html][website] [website]: http://firefox-dev.tools/debugger.html/`

**Comment by nagpalm7** [comment]
> @dhyey35 
Also the first link of README.md file links to http://firefox-dev.tools/debugger.html/

It must be redirected to [https://firefox-dev.tools/debugger/](https://firefox-dev.tools/debugger/).
Since the repo name has been changed from `debugger.html` to `debugger` this needs to be renamed as well.

**Comment by bomsy** [comment]
No longer needed after move to MC.
