### ISSUE TITLE
Search for text with braces in pattern.

### ISSUE THREAD

**Issue by starsolaris** [firefox-devtools/debugger#7967]
When i try to search in source (ctrl+shift+f) wth braces in pattern i find nothing 
ex: `parameters = Object.assign({node: null}, parameters);`
Then i must escape all braces, which is very annoying, to find what i need.
ex: `parameters = Object.assign\({node: null}, parameters\);`

I propose to search with text pattern by default (like in old versions). Regex search pattern should be an option.

**Comment by jasonLaster** [comment]
Thanks @starsolaris I agree.

I think we should show the search options like we do for file search, but by default regex search should be off.

<img width="446" alt="screen shot 2019-02-20 at 12 41 33 pm" src="https://user-images.githubusercontent.com/254562/53112319-f3f04400-350c-11e9-8328-4c38dde908a4.png">

**Comment by charanjit-singh** [comment]
@jasonLaster I'm new to this community,
Can I take this issue?

**Comment by jasonLaster** [comment]
Sure @charanjit-singh

**Comment by charanjit-singh** [comment]
@jasonLaster There are 2 more problems in search toolbar:

1. There is no option of changing search modifiers in frontend.
2. There is no option to highlight backward or forward search result.

**Comment by charanjit-singh** [comment]
Thanks @jasonLaster 
Is this fine?
The alignment of modifiers after the search results count and after NEXT and PREV buttons.

![screenshot from 2019-02-26 15-37-56](https://user-images.githubusercontent.com/23359602/53404984-e63f3080-39dc-11e9-8c53-119838ba2e25.png)
---
![screenshot from 2019-02-26 15-38-03](https://user-images.githubusercontent.com/23359602/53404975-c9a2f880-39dc-11e9-8663-4ee326f8cd3b.png)
---

**Comment by janodvarko** [comment]
It looks like this is fixed, I was able to search for `Object.assign({node: null}, parameters);` without a problem.

The UI looks different now so, if there are any follows ups they should be reported in Bugzilla:
https://bugzilla.mozilla.org/enter_bug.cgi?product=DevTools&component=Netmonitor

Honza
