### ISSUE TITLE
[Frames] call stack shows <anonymous> frame

### ISSUE THREAD

**Issue by jasonLaster** [firefox-devtools/debugger#7968]
It looks like when we removed the callee field we might have started showing a lot more anonymous frames.

![image](https://user-images.githubusercontent.com/254562/52826146-aba8d000-308d-11e9-8a62-bb677181e132.png)

**Comment by jasonLaster** [comment]
@nagpalm7 it would be great to start by identifying cases where Firefox works and Firefox Nightly fails

**Comment by nagpalm7** [comment]
@jasonLaster I am unable to run firefox and nightly at same time with gecko drivers enabled.

**Comment by darkwing** [comment]
I don't see STR but I tried pausing in roughly the same place that you had and didn't see anything anonymous:

<img width="1275" alt="noanon1" src="https://user-images.githubusercontent.com/46655/53750946-c1313e80-3e70-11e9-9e6b-306e9a10ec70.png">

<img width="314" alt="noanon2" src="https://user-images.githubusercontent.com/46655/53750950-c3939880-3e70-11e9-9bc6-facb044b7247.png">

Tested inside MC.

**Comment by nagpalm7** [comment]
@darkwing same with me with the latest pull! Should we close this issue?

**Comment by jasonLaster** [comment]
@nagpalm7 i'll check too

**Comment by darkwing** [comment]
I still can't reproduce this in MC so I'm closing but please reopen if you see it again!
