### ISSUE TITLE
[sources] relative sources are cleared when workers are detected

### ISSUE THREAD

**Issue by jasonLaster** [firefox-devtools/debugger#7972]
Str:
1. Go to localhost 8000 and debug a page with the launchpad
2. Reloaf the launchpad 
3. Press cmd+P 

Notice that quick open only has debugger.js.
The reason for this is that updateWorkers will accidentally clear the relative sources.

**Comment by janodvarko** [comment]
The launchpad isn't supported anymore, closing.

Honza
