### ISSUE TITLE
[Extensions] listen for `chrome.enabled` changes

### ISSUE THREAD

**Issue by jasonLaster** [firefox-devtools/debugger#7981]
When the debugger starts we currently check the status of `"chrome.enabled"` to see if we should show chrome and extension sources in the sources tree.

After that, we do not observe changes to the pref. We should listen for the change and adapt. This is somewhat of a new pattern:

1. in client/index.js we should listen to the pref 
2. we should dispatch a new action for updating the store value

```diff
diff --git a/src/actions/ui.js b/src/actions/ui.js
index a1aea0a57..9ecf0996a 100644
--- a/src/actions/ui.js
+++ b/src/actions/ui.js
@@ -210,3 +210,7 @@ export function updateViewport() {
 export function setOrientation(orientation: OrientationType) {
   return { type: "SET_ORIENTATION", orientation };
 }
+
+export function setChromeAndExtensions(value) {
+  // ...
+}
diff --git a/src/client/index.js b/src/client/index.js
index 743d28a3d..4c8b9f4d4 100644
--- a/src/client/index.js
+++ b/src/client/index.js
@@ -17,7 +17,8 @@ import {
 } from "../utils/bootstrap";
 import { initialBreakpointsState } from "../reducers/breakpoints";

 function loadFromPrefs(actions: Object) {
   const { pauseOnExceptions, pauseOnCaughtExceptions } = prefs;
@@ -29,6 +30,10 @@ function loadFromPrefs(actions: Object) {
   }
 }

+function listenToPrefs(actions: Actions) {
+  prefs.on("chromeAndExtenstionsEnabled", value => actions.setChromeAndExtensions(value))
+}
+
```

**Comment by janodvarko** [comment]
Cloned into Bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1695631

Firefox Developer Tools (including Debugger tool) development is now entirely happening in Bugzilla and new issues should be reported here: https://bugzilla.mozilla.org/enter_bug.cgi?product=DevTools&component=Debugger

Honza
