### ISSUE TITLE
[sources] React todomvc jsx files are in the wrong directory

### ISSUE THREAD

**Issue by jasonLaster** [firefox-devtools/debugger#7986]
We fixed the issue with jsx files appearing in #4373. Now they're relative to the transformer and not the HTML file they were created in [link](https://github.com/firefox-devtools/debugger.html/blob/master/src/actions/sources/newSources.js#L92-L103).

---
<img width="533" alt="image" src="https://user-images.githubusercontent.com/254562/52981230-4bc36980-33ac-11e9-8ffc-1cd40a24bb67.png">

<img width="240" alt="image" src="https://user-images.githubusercontent.com/254562/52981235-54b43b00-33ac-11e9-9e7a-bf55b02a8970.png">

**Comment by darkwing** [comment]
@jasonLaster Do you this a tree bug or a server bug?

**Comment by jasonLaster** [comment]
i think this is a client bug.

that comes from -- https://searchfox.org/mozilla-central/source/devtools/client/debugger/src/actions/sources/newSources.js#120

CC @bhackett1024

**Comment by janodvarko** [comment]
Reported in Bugzilla:
https://bugzilla.mozilla.org/show_bug.cgi?id=1550492

Honza

**Comment by digitarald** [comment]
Continuing in bugzilla.
