### ISSUE TITLE
[SourceTree] File depth

### ISSUE THREAD

**Issue by jasonLaster** [firefox-devtools/debugger#7987]
It looks like we might have an indentation issue for files:

The width for "no source" is now 10px
<img width="1382" alt="screen shot 2019-02-19 at 12 07 28 pm" src="https://user-images.githubusercontent.com/254562/53033488-22075280-343f-11e9-80bb-27f7db5eb66f.png">

I think it should be 0

<img width="1384" alt="screen shot 2019-02-19 at 12 07 37 pm" src="https://user-images.githubusercontent.com/254562/53033474-19af1780-343f-11e9-914c-1d8bcecb8de9.png">

**Comment by nagpalm7** [comment]
Can I take up this issue ?

**Comment by fvsch** [comment]
> The width for "no source" is now 10px

It used to be 10px, and I changed it to be 10px + 4px of margin = 14px of white space, to match the white space taken by the arrow icon + its margin.

This is meant to align the icons and text of siblings when siblings are a mixture of files and folders.

Schematically:

```
 ▼ Item 1
    ¶ Item 1.1
    ▶ Item 1.2
       ▼ Item 1.3
       ☼ Item 1.3.1
       ¶ Item 1.3.3
       ♣ Item 1.3.3
    ♠ Item 1.2
```

The proposed change would result in mis-alignments:

```
 ▼ Item 1
   ¶ Item 1.1
    ▶ Item 1.2
       ▼ Item 1.3
      ☼ Item 1.3.1
      ¶ Item 1.3.3
      ♣ Item 1.3.3
   ♠ Item 1.2
```

**Comment by fvsch** [comment]
Current alignment, in trees where we have sibling files + folders:

<img alt="screen shot" width="374" src="https://user-images.githubusercontent.com/243601/53670742-0f312100-3c7c-11e9-9234-960863d7b730.png">

With the proposed change, the alignment is visibly broken:

<img alt="screen shot" width="374" src="https://user-images.githubusercontent.com/243601/53670759-1f490080-3c7c-11e9-965b-524baf15e869.png">

(`src/ApolloClient/State`, `src/ApolloClient/Client.tsx` and `src/Components` appear to be on 3 different depths, when the paths show that we have 2 different depths.)

So poor `.img.no-arrow` should be left alone. :)

If the concern is that we are taking too much horizontal space for nesting, then the class to work with is `.tree-indent`. Each row has N `<span class="tree-indent"></span>` elements (0 at first level, 3 at fourth level, etc.), regardless of if it's a file or folder, so when we change the tree-indent things stay consistent.

Currently our indent width is 17px (12px width + 5px margin... we should probably remove the margin and just use width here).

Our theoretical "perfect" indent is 20px (3px more than the current indent), and looks like this:

<img alt="screen shot" width="334" src="https://user-images.githubusercontent.com/243601/53671585-608edf80-3c7f-11e9-9c5b-d66b8f3deac0.png">

If we want to preserve space more agressively, we could go with half-value indents, or 10px (7px less than the current indent; a win of 35px for depth=6):

<img alt="screen shot" width="334" src="https://user-images.githubusercontent.com/243601/53671647-a9df2f00-3c7f-11e9-9413-c6aed4600c56.png">

It's compact, but IMO it gets harder to read. Tweaking the indent width (after removing its margin), it looks like indents starting at 14px are more readable.
