### ISSUE TITLE
[Breakpoints] occassionally the debugger pauses without showing a breakpoint

### ISSUE THREAD

**Issue by jasonLaster** [firefox-devtools/debugger#7989]
STR:

1. go to localhost:8000 with the launchpad
2. add a breakpoint in `components/editor/index.js#125`
3. refresh a couple of times

- Notice that we're paused on 125, but there is no breakpoint
- The issue is that in `syncBreakpoint` `client.setBreakpoint` now sends the message to all threads and some the worker threads occasionally hang. 

<img width="1025" alt="screen shot 2019-02-19 at 1 52 12 pm" src="https://user-images.githubusercontent.com/254562/53039634-95b05c00-344d-11e9-8c96-70d1e2343620.png">

**Comment by jasonLaster** [comment]
This fixes it, but perhaps might be bad

```diff
diff --git a/devtools/client/debugger/new/src/client/firefox/commands.js b/devtools/client/debugger/new/src/client/firefox/commands.js
index adfb5a5593a2..a4b882919caf 100644
--- a/devtools/client/debugger/new/src/client/firefox/commands.js
+++ b/devtools/client/debugger/new/src/client/firefox/commands.js
@@ -179,14 +179,14 @@ async function setBreakpoint(
 ) {
   breakpoints[locationKey(location)] = { location, options };
   for (const thread of getAllThreadClients()) {
-    await thread.setBreakpoint(location, options);
+    thread.setBreakpoint(location, options);
   }
 }

 async function removeBreakpoint(location: BreakpointLocation) {
   delete breakpoints[locationKey(location)];
   for (const thread of getAllThreadClients()) {
-    await thread.removeBreakpoint(location);
+    thread.removeBreakpoint(location);
   }
 }

```

**Comment by janodvarko** [comment]
The test case is based on the Launchpad that is not supported anymore.

Firefox Developer Tools (including Debugger tool) development is now entirely happening in Bugzilla and new issues should be reported here: https://bugzilla.mozilla.org/enter_bug.cgi?product=DevTools&component=Debugger

Please reopen this report in Bugzilla if it's still valid.

Honza
