### ISSUE TITLE
Tree-node for Watch Expressions being highlighted on click

### ISSUE THREAD

**Issue by jaril** [firefox-devtools/debugger#8019]
Noticed this while reviewing #8013 and is unrelated to their changes. 

This seems strange so I don't think this is intended, can just close this otherwise.

GIF:
![feb-22-2019 10-46-57](https://user-images.githubusercontent.com/15959269/53254335-29259f00-3691-11e9-848a-945e02f52ee7.gif)

**Comment by nchevobbe** [comment]
cc @yzen

**Comment by nchevobbe** [comment]
so, it might not make sense when you have only one watch expression which isn't expandable, but if:
1. the expression result can be expanded
1. you have multiple expressions

that's what allows to navigate with the keyboard.
One thing we could do is to have a way to not focus a node when using the mouse in some cases?
What's your take on this @darkwing ?

**Comment by yzen** [comment]
Having no "focused" styling for when tree node is a single tree node is reasonable. Though, it still messes with tracking focus visually since in this case there is no way for the user to know what current active element/widget is.

**Comment by janodvarko** [comment]
Seems to be fixed. I can't reproduce this on my machine (Win10)

Firefox Developer Tools (including Debugger tool) development is now entirely happening in Bugzilla and new issues should be reported here: https://bugzilla.mozilla.org/enter_bug.cgi?product=DevTools&component=Debugger

Honza
