### ISSUE TITLE
Link for project site goes to 404

### ISSUE THREAD

**Issue by nmicht** [firefox-devtools/debugger#8028]
After renaming the project from debugger.html to debugger #7997, the link in the github main page got not updated.

![image](https://user-images.githubusercontent.com/1750293/53381173-e9cfaa80-393d-11e9-936c-91008d218e39.png)

Right now is pointing to https://firefox-devtools.github.io/debugger.html/ and it should link to https://firefox-devtools.github.io/debugger/

**Comment by nmicht** [comment]
@jasonLaster I think will be also good to make a list of external sites in Mozilla community linking to the old URL instead of http://firefox-dev.tools/debugger/ to fix them.
If you have an idea on how can I help with that, let me know.

**Comment by jasonLaster** [comment]
good catch - i'm not sure how to find external sites
