### ISSUE TITLE
[Docs] Infomation for labels needs to be updated

### ISSUE THREAD

**Issue by nmicht** [firefox-devtools/debugger#8031]
The information on the labels used on the project needs to be updated.
The [documentation for labels](https://github.com/firefox-devtools/debugger/blob/master/docs/issues.md#labels) display labels that we currently do not use, others that were renamed to use emoticons, and many others that we use but are not listed.

Example of labels listed but we are not using:
- needs-investigation
- needs-str
- needs-description

We need to talk about if we are going to start using those labels.

Some steps to work on this are:
1. Add a clear description for each label on https://github.com/firefox-devtools/debugger/labels
2. Include all the labels on the [documentation for labels](https://github.com/firefox-devtools/debugger/blob/master/docs/issues.md#labels) to make easier for contributors to understand the classification my modules, but also, for difficulty, etc.

**Comment by janodvarko** [comment]
This issue list is deprecated in favor of: https://mzl.la/2N5JVYZ (Bugzilla)

I am closing this report since we don't want to invest into this.

Honza
