### ISSUE TITLE
Show element highlighter when hovering an element in Scopes/Watch Expression/Popup

### ISSUE THREAD

**Issue by nchevobbe** [firefox-devtools/debugger#8032]
#7455 added the node selection which is good, but we're still missing highlighting, which is done by passing `onDOMNodeMouseOver` and `onDOMNodeMouseOut` prop to Reps/ObjectInspector

**Comment by darkwing** [comment]
@nchevobbe I don't understand what the contents of those functions would be, or the resulting effect.  Could you provide more detail?

**Comment by nchevobbe** [comment]
Sure!
So, in the console when we display an element, if you hover it, it will display the highlighter in the content page: 

<img width="816" alt="image" src="https://user-images.githubusercontent.com/578107/53472408-c4d75680-3a67-11e9-90d8-72c1ec3a9b28.png">

In the console, those 2 methods are defined in [devtools/client/webconsole/utils/object-inspector.js#34-37](https://searchfox.org/mozilla-central/rev/dbddac86aadf1d4871fb350bbe66db43728a9f81/devtools/client/webconsole/utils/object-inspector.js#34-37), and they call [devtools/client/webconsole/webconsole-wrapper.js#275-287](https://searchfox.org/mozilla-central/rev/dbddac86aadf1d4871fb350bbe66db43728a9f81/devtools/client/webconsole/webconsole-wrapper.js#275-287).

Hope it's clearer now :)

**Comment by dimitardanailov** [comment]
@nchevobbe / @darkwing 

I'd like to try make a patch / PR for this issue but I need more information. 
Could someone help me ? 

How to reproduce the issue and which example should use ?

**Comment by darkwing** [comment]
Heh, I just submitted a patch for this problem this morning :)

https://phabricator.services.mozilla.com/D25635

Feel free to check out the code there, @dimitardanailov, to understand what's happening :)

**Comment by dimitardanailov** [comment]
@darkwing 

Thank you very much for quick response 🙇 
Unfortunately I don't have knowledge and experience to understand the patch. 
Whatever: The patch looks good and solid.
