### ISSUE TITLE
Can't select node from the Popup

### ISSUE THREAD

**Issue by nchevobbe** [firefox-devtools/debugger#8033]
**Steps to reproduce**
1. Go to https://nchevobbe.github.io/demo/console-test-app.html
1. Open the debugger
1. Open `console-test-event-listeners.js`, and add a breakpoint on line 6 (inside the click event handler)
1. In the page, click on a button
1. The debugger should pause, now hover `e`
1. There should be a `target` property, with an icon next to it, click the icon

**Expected results**

The target element is selected in the inspector, like the title claim it will.

**Actual results**

Nothing is happening.

**Comment by darkwing** [comment]
Just checked and this works for Expressions and Scopes, but can confirm the issue reported by nchevobbe, despite a grip being provided by the Popover.js ObjectInspector instance.

**Comment by nchevobbe** [comment]
Thanks David!
