### ISSUE TITLE
Find and replace functionality.

### ISSUE THREAD

**Issue by charanjit-singh** [firefox-devtools/debugger#8041]
Hi, 
We can search for query in sources, but we cannot replace the content.

**Comment by charanjit-singh** [comment]
In chrome:
![image](https://user-images.githubusercontent.com/23359602/53486441-b95b4e00-3aae-11e9-8554-a946d5f03671.png)

**Comment by jasonLaster** [comment]
I don't think we want to replace text because there currently is no way to edit the text either :)
