### ISSUE TITLE
[ ProjectSearch ] Collapse results output in multiple lines even for same line of same file .

### ISSUE THREAD

**Issue by charanjit-singh** [firefox-devtools/debugger#8043]
I think search results for same line should come in same line.
But currently It is showing every match case in different line.
And Also, The Highlighted text is shown with some additional internal padding, which'll confuse users because It'll look like a space. For eg:
Currently: For match 'a' in  "yaahoo"
Results are:
1.  y[ a ]ahoo
2. ya[ a ]hoo
But expected results are:
1. y[a][a]hoo  // without padding.

Highlighter needs to be updated as the results,( if we fix the separate line bug ), will be:
1. y[ a ][ a ]hoo
      ^.     ^..........|` Spaces around |
        `````````````|. search result       . |

Current Scenario:
![image](https://user-images.githubusercontent.com/23359602/53518698-96a15780-3af7-11e9-9e3e-d6453afe8db1.png)
---
### Expected Results:
![image](https://user-images.githubusercontent.com/23359602/53518782-c4869c00-3af7-11e9-9110-ba7ccadfb8a8.png)

**Comment by charanjit-singh** [comment]
I read the whole code and ohh my gawdd...., 
Current Searching Algorithm ( Both for In-File Search and Project Search ) :
`Step 1: Get Input from SearchInput Component.`
`Step 2: Search query in sources.`
Step 2 returns: `Results`s which includes `Array<Match>` 
Now, `Match` contains `MatchIndex` **<---- Problem**
It should be `MatchIndexes` , As Query is being searched line by line and instead of pushing a new `MatchIndex` to `MatchIndexes`, **We are Creating a new `Match` which is quite inefficient.**

We should Use `MatchIndexes: Array<number>` instead of `MatchIndex: number>` in a particular `Match`.

Now, Step 3 is worse (currently):
`Step 3: Then From Search Results, In-File Search is rendering line by line by ` **finding** ` in whole array of Matches, Line by line`. 

May I proceed with modifying the code? 
@jasonLaster

**Comment by fvsch** [comment]
Hi @charanjit-singh, can you edit this issue's title to make it clearer what specific UX issue you're trying to improve? Maybe something like "[ProjectSearch] Collapse results when they occur on the same line of same file"?

Two things to keep in mind:

1. There have been a few issues with project search performance and memory usage. It might be a good idea to look up past issues (open and closed) and see if some of the code problems you're seeing were made on purpose to avoid perf issues. (Some of your code exploration seems to hint at performance problems and possible ways to solve them, which is great.)

2. Lines can be longer than the result display. For instance if you have a narrow Debugger viewport (DevTools docked to the right), the result display can be narrow too. If you have a 80 character line, with a match at column 4 and a match at column 70, it might be impossible to show both as a single result. And source files can have very long lines, especially when minified. You can get 50 matches in a single line, at columns 100, 500, 3087, 32499, 54002, etc.

Displaying each match as a single result works around that second issue. It seems to be what VS Code search does, too.

**Comment by charanjit-singh** [comment]
I got it

**Comment by fvsch** [comment]
> We can provide a toggle button to users to choose modes, either single line results or multiple results.

I would rather avoid creating new preferences.

**Comment by fvsch** [comment]
Some examples with a bunch of results on the same line.

![screen shot 2019-03-02 at 00 41 22](https://user-images.githubusercontent.com/243601/53672739-2247ef00-3c84-11e9-80ce-2bb9b4ce2d29.png)

![screen shot 2019-03-02 at 00 42 22](https://user-images.githubusercontent.com/243601/53672743-283dd000-3c84-11e9-9004-d0a4b254f667.png)

**Comment by charanjit-singh** [comment]
Yeah!
What we can do is:

If search result on same line are close to each other, then show them on same line,
Otherwise After a certain length, Create New Line.

**Comment by janodvarko** [comment]
Cloned into Bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1695630

Firefox Developer Tools (including Debugger tool) development is now entirely happening in Bugzilla and new issues should be reported here: https://bugzilla.mozilla.org/enter_bug.cgi?product=DevTools&component=Debugger

Honza
