### ISSUE TITLE
Google Summer of Code 2019 - Debugger Inline Variable Preview

### ISSUE THREAD

**Issue by darkwing** [firefox-devtools/debugger#8047]
Welcome!

Mozilla is participating in the [2019 Google Summer of Code](https://summerofcode.withgoogle.com/organizations/5899373068681216/) and one interesting and fun project will be implementing **Inline Variable Preview** in for the debugger!

*When the Firefox DevTools debugger is paused, users can hover over variables to get a useful tooltip that details the variable's value at that time. While this popup is very informative, one valuable enhancement would be displaying relevant contextual variables values alongside the variable inline, alleviating the need for tooltips and allowing the user to more quickly get the information they need. The applicant will work alongside the Debugger's team to implement this feature based on UX mockups and be given space to share and implement ideas of their own.*

Use this issue as a place to ask questions about the inline variable preview project and GSOC at Mozilla.

**Comment by acnair** [comment]
So we start by trying out open issues and try solving them and then come up with a way to design it?

**Comment by FadySamirSadek** [comment]
What makes a variable a relevant contextual variable?!
Is it being in the same scope or something else?

**Comment by digitarald** [comment]
Implementation work will continue in bugzilla under meta [bug 1547385](https://bugzilla.mozilla.org/show_bug.cgi?id=1547385).
