### ISSUE TITLE
[UX] WhyPaused component is displayed at an awkward place, and has low contrast

### ISSUE THREAD

**Issue by fvsch** [firefox-devtools/debugger#8049]
![whypaused_screenshot](https://user-images.githubusercontent.com/243601/53644415-d91d7e00-3c36-11e9-9561-4f83c3a21eb2.png)

Let's look at the contrast issue first, since it's more straightforward. On the light theme:

- the main label has `3.10:1` contrast;
- the error text has `1.91:1` contrast.

(We're aiming for a minimum of `4.5:1` contrast for both.)

Things would be better if we removed the `opacity: 0.6` on that component.

Now, for the placement part. I would argue that:

- Having this information in the Call Stack panel is a bit unexpected, in practice I wonder if it's not just ignored by most users?
- The placement between the paged call stack and its "Expand rows" button is awkward, it creates a semantic break in the usual "limited content + 'show more' button" pattern.

It seems this component was moved here in #3111 to avoid another issue (vertical jump when that component is displayed or not). But I wonder if, with this change, we haven't lost a visible indicator of the "Paused on breakpoint|exception" state? In my experience nowadays the paused state can mostly be detected by looking at the Play/Pause icon, which is a weak signal. @jasonLaster, I think you've got similar feedback from other users?

So maybe we should revisit having a "Paused on..." information higher up, perhaps always visible even when the SecondaryPanes are closed (like the play/pause/skip buttons), and try to move WhyPaused there?

**Comment by digitarald** [comment]
Came up in #8068 as well and I found this issue. Given how hard debugging already is to get into and be good at; we can do much better at clearly communicating state.

**Requirements** for a good warning

1. High contrast, possibly building on the [photon warnings](https://design.firefox.com/photon/patterns/warnings.html) style
2. Primary element in the UI, above the fold and not in an accordion.
3. Should not cause unnecessary visual noise when stepping (only when the why changes).
4. Lean on existing paused state warnings from other debuggers which users are trained on

**Existing work**

_Safari_, also shows the function and file as reference and link:
<img width="387" alt="image" src="https://user-images.githubusercontent.com/8599/53772278-ae336400-3e9a-11e9-9acf-f187e348e2a0.png">

_Chrome_, also shows meta data for the reason (which could be linked better):
![image](https://user-images.githubusercontent.com/8599/53772297-c4412480-3e9a-11e9-88c0-e21d09f8a3f5.png)
![image](https://user-images.githubusercontent.com/8599/53772310-d02ce680-3e9a-11e9-8b58-c2f53a0de74e.png)
![image](https://user-images.githubusercontent.com/8599/53772317-d58a3100-3e9a-11e9-96f1-737232327a0a.png)

VSCode shows paused state by having a conditional _Debug toolbar_ on top.

![image](https://user-images.githubusercontent.com/8599/53772421-2e59c980-3e9b-11e9-8c37-735d4becdc03.png)

**Comment by fvsch** [comment]
> Chrome, also shows meta data for the reason (which could be linked better)

Yep, and their "Debugger paused" label is pretty bad IMHO, it suggests that JS execution is currently paused but actually means the opposite (it means that breakpoints/pausing is disabled, so JS runs without interference).

**Comment by derek-li** [comment]
What's your guys opinion on moving the WhyPaused component back to it's original location before the #3111 change? @jasonLaster 

I feel this way we could add the requirements for a more visible warning and even have the information available when the secondary pane is collapsed. It also conforms to the Chrome WhyPaused.

**Comment by digitarald** [comment]
That seems like the best approach, @derek-li. Apart from the warning styling, another consideration is to keep an eye on the visual noise while stepping, which #3111 was mainly about.

**Comment by fvsch** [comment]
At the very least it's worth experimenting with moving it back up, and trying to address the issues seen in #3111 in a different way. For example, while stepping the WhyPaused component should not disappear (even just briefly); that would mitigate most vertical jumpiness.
