### ISSUE TITLE
Failing source maps should fall back to generated source

### ISSUE THREAD

**Issue by digitarald** [firefox-devtools/debugger#8058]
STR:
- Open github.com
- Enable _Pause on any URL_ in _XHR Breakpoints_
- Click around until Debugger pauses

ER: Source maps fail, but it should just use the generated sources
AR: All files fail to load:

<img width="878" alt="image" src="https://user-images.githubusercontent.com/8599/53674289-c65c7680-3c41-11e9-8536-5375d37bf193.png">

Chrome isn't much better (or worse, because it doesn't show an error?):

<img width="570" alt="image" src="https://user-images.githubusercontent.com/8599/53674332-120f2000-3c42-11e9-9029-64c6f15754af.png">

For Reddit it shows at least source map errors:

<img width="787" alt="image" src="https://user-images.githubusercontent.com/8599/53674400-8f3a9500-3c42-11e9-8482-19d71cdfb6f1.png">

**Comment by jasonLaster** [comment]
Hey @bomsy didn't we fix some of these cases?

**Comment by janodvarko** [comment]
I can still reproduce the problem, cloned into bugzilla.

Honza
