### ISSUE TITLE
Make errors during file-loading prettier

### ISSUE THREAD

**Issue by digitarald** [firefox-devtools/debugger#8059]
Errors are dropped into the files right now:

<img width="655" alt="image" src="https://user-images.githubusercontent.com/8599/53674433-c7da6e80-3c42-11e9-978e-cf68cf0ada2f.png">

and behave like files, even allowing breakpoints 😈:

<img width="797" alt="image" src="https://user-images.githubusercontent.com/8599/53674446-dc1e6b80-3c42-11e9-988c-6274638cf961.png">

_User Story: When hitting an issue with opening a file, I want to see a friendly error message with diagnostic information, so that I can fix or work around the issue._

Not using the file as output for the error, but having a basic error design might just be enough.

**⚠️ This issue still needs requirements. Please discuss and propose ideas in the comments to help define the requirements before claiming this issue.**

**Comment by darkwing** [comment]
At present source contents are loaded asyncronously so there may be a perf hit on simply showing a message; maybe an alternate solution would be to not allow breakpoints until the source is loaded, and then disallow breakpoints if the source errored out.  Maybe even make the tab background a very subtle shared of red or yellow as well.

**Comment by fvsch** [comment]
> Maybe even make the tab background a very subtle shared of red or yellow as well.

I would add a :warning: warning icon to the tab, rather than change its colors.

**Comment by jasonLaster** [comment]
I could see some benefits avoiding the editor component entirely and showing the error message in an error panel. 

![image](https://user-images.githubusercontent.com/254562/53689665-90de8880-3d28-11e9-87a3-6db9899e3ad6.png)


This looks pretty bad, but there's probably a photon pattern for it...

**Comment by digitarald** [comment]
> I could see some benefits avoiding the editor component entirely and showing the error message in an error panel.

This was what I was looking for, sorry for not providing a mockup with the issue. There is no need for a source panel, so the error should not overlay an empty file.

[Warnings](https://design.firefox.com/photon/patterns/warnings.html) and [errors](https://design.firefox.com/photon/patterns/errors.html) have some good guidelines, like the simple yellow box: 
![image](https://user-images.githubusercontent.com/8599/53713511-fcdff000-3dff-11e9-8b8b-b26bdd514eeb.png) or red text: 
![image](https://user-images.githubusercontent.com/8599/53713543-141edd80-3e00-11e9-8406-038344f5ccdd.png)

**Comment by digitarald** [comment]
Another component to re-use would be Console's notification box: https://searchfox.org/mozilla-central/rev/8ff2cd0a27e3764d9540abdc5a66b2fb1e4e9644/devtools/client/webconsole/components/App.js#236-239

**Comment by janodvarko** [comment]
Cloned into Bugzilla https://bugzilla.mozilla.org/show_bug.cgi?id=1695625

Firefox Developer Tools (including Debugger tool) development is now entirely happening in Bugzilla and new issues should be reported here: https://bugzilla.mozilla.org/enter_bug.cgi?product=DevTools&component=Debugger

Honza
