### ISSUE TITLE
[Sources] List bundled sources (webpack:///... et al.) under the relevant host

### ISSUE THREAD

**Issue by fvsch** [firefox-devtools/debugger#8060]
Opening this for discussion. My apologies if this was decided against already.

Could we perhaps nest the `Webpack` folder (or `Angular` or other bundler-specific folders) under the relevant host? As far as I know, when we have `webpack:///...` sources they were identified in the source map for a JS or CSS file hosted on a specific origin. It would be better to reflect this association in the sources tree, for the following reasons:

1. The same-origin policy has a lot of impact in JavaScript, so it would be better to reflect that origin to users.
2. Related: we should avoid creating the illusion that "Webpack" or "Angular" are some magical web origins. I'm working with a lot of developers, juniors devs, including some from a other backgrounds, and the basic concepts of URLs and HTTP are not always known (people know the structure of their git repository and run a magical command that spawns a web server on `localhost:3000` for them); it would help if Debugger reflected origins and URLS a bit better.
3. How do we manage it if we have `webpack:///...` sources from 2+ different domains? We may end up creating a "Webpack" tree that is nonsensical and merges different projects together.

Nesting the Webpack/Angular/etc. "folders" under their host could be a good compromise between reflecting URLs and still giving quick access to the original sources bundled by those tools.

Current result & expected result:

![selection_044](https://user-images.githubusercontent.com/243601/53686060-f760a800-3d22-11e9-947f-b773da2b6057.png)   ![selection_045](https://user-images.githubusercontent.com/243601/53686063-fcbdf280-3d22-11e9-9bca-25e459de255d.png)

This would solve part of #7921 too.

**Comment by nagpalm7** [comment]
@fvsch Webpack or other bundlers, are always part of main origin or they could also belong to sources other than main origin ?

**Comment by fvsch** [comment]
Good question. I tried loading two React apps bundled with Webpack on two different origins but in that case I'm not getting the "Webpack" group to show up. Not sure if sourcemaps work cross-origin.

**Comment by nagpalm7** [comment]
@fvsch It is also possible that two webpacks from different sources merge in one. As source tree is not configured as we are expecting it to show a group of two webpacks, Correct me if I am wrong. @jasonLaster what you say?

**Comment by arosenfeld2003** [comment]
@fvsch I'm investigating this to get a deeper understanding of the source tree.  Would you mind sharing the url you used for the above screenshot?

**Comment by fvsch** [comment]
@arosenfeld2003 That was on https://arstechnica.com/

**Comment by janodvarko** [comment]
Cloned into Bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1695640

Firefox Developer Tools (including Debugger tool) development is now entirely happening in Bugzilla and new issues should be reported here: https://bugzilla.mozilla.org/enter_bug.cgi?product=DevTools&component=Debugger

Honza
