### ISSUE TITLE
[UX] Sources tree icon update?

### ISSUE THREAD

**Issue by fvsch** [firefox-devtools/debugger#8061]
As we're moving towards using more Photon icons in Debugger, I'm wondering what we should do for the Sources icons, and if we should try to use the thicker Photon icons there.

Last Fall I updated the Storage panel's tree to use Photon icons, so that can be an interesting comparison point:

![tree-icon-comparison](https://user-images.githubusercontent.com/243601/53686762-9b4e5180-3d2b-11e9-9054-887ca68cf0c8.png)

__Sources Tree:__

- Row height: 22px
- Text size: 11px
- Icons: 16px, but most are drawn using only 12px (globe) or at most 14px (folder width)
- Indent width: 17px

__Storage Tree:__

- Row height: 24px
- Text size: 11px
- Icons: 16px canvas, with the visuals filling the canvas on at least one dimension (width or height)
- Indent width: 14px

Once we update other icons in Debugger to use a Photon style, I think we should probably update the Sources icons too. I'm just wondering what other people think.

Pinging: @mcroud @digitarald @jasonLaster @darkwing.

**Comment by charanjit-singh** [comment]
Why don't we use Adobe XD for prototyping and UX designing??

CC @fvsch @jasonLaster

**Comment by fvsch** [comment]
> Why don't we use Adobe XD for prototyping and UX designing?

There isn't a unified workflow. It would be difficult to specify a single tool because most are commercial and available only on some operating systems; both the OS restrictions and the money requirements can restrict access for contributors.

Current practices: the UX staff is mostly using Sketch, and InVision for sharing mock-ups. I tend to use Figma because it's available on Linux and it's pretty good with SVG. Many staffers and contributors also use devtools to tweak devtools/debugger CSS, and make screenshots of the result, when we are discussing small visual changes.

**Comment by jasonLaster** [comment]
@fvsch i really like this!

**Comment by digitarald** [comment]
@fvsch +1 , this really closes the gap of different icon stylings a bit more. I especially like that we can clean up the organically grown set of file icons, as the inconsistent shapes make the tree visually noisy.

**Comment by janodvarko** [comment]
Cloned into Bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1695627

Firefox Developer Tools (including Debugger tool) development is now entirely happening in Bugzilla and new issues should be reported here: https://bugzilla.mozilla.org/enter_bug.cgi?product=DevTools&component=Debugger

Honza
