### ISSUE TITLE
Footer content can be centered instead of aligned-right

### ISSUE THREAD

**Issue by fvsch** [firefox-devtools/debugger#8064]
Footer layout:

```jsx
<div className="source-footer">
  {this.renderCommands()}
  {this.renderSourceSummary()}
  {this.renderCursorPosition()}
  {this.renderToggleButton()}
</div>
```

The commands are rendered in their own wrapping <div>, but other content are single items which all have `margin-inline-start: auto`. When we end up rendering more than one (summary + position, position + toggle button...), those elements end up spaced evenly and look centered in the footer.

We should probably have:

```jsx
<div className="source-footer">
  <div className="source-footer-start">
    {this.renderCommands()}
  </div>
  <div className="source-footer-end">
    {this.renderSourceSummary()}
    {this.renderCursorPosition()}
    {this.renderToggleButton()}
  </div>
</div>
```

**Comment by derek-li** [comment]
Just a suggestion, but I think we should keep `renderSourceSummary()` separate from `source-footer-start` and `source-footer-end`

In my opinion it would look strange if this text was pushed to the left:
![issue8064 1](https://user-images.githubusercontent.com/33161837/53848880-dee2ce80-3f6a-11e9-8b86-7420081323d3.png)

**Comment by fvsch** [comment]
@derek-li I would rather avoid having this appear somewhat randomly in the middle. What's more, with Flexbox if we want to center some content but have arbitrary amounts of content in the left and right columns... things get a bit icky.

I think we should decide if we want it to appear on the left or on the right.
Since this information appears after you click "Pretty print source", maybe we should put it on the left?

**Comment by errietta** [comment]
Sorry it took that long ^_^' (Stuff ™️  going on)
I think it looks good with what @derek-li said about putting the source information on the right
![image](https://user-images.githubusercontent.com/134585/54887130-44015400-4e87-11e9-8063-593b903cc637.png)

but i'm happy to be convinced otherwise

**Comment by fvsch** [comment]
>  I think it looks good with what @derek-li said about putting the source information on the right

Agreed. Thanks everyone.
