### ISSUE TITLE
[Preview] it can take time to show a popup when initially pausing

### ISSUE THREAD

**Issue by jasonLaster** [firefox-devtools/debugger#8067]
this is difficult to provide an STR, but i've noticed that previewing can be slow when initially pausing

I think this is because we end up waiting on the parser worker to  map the expression

**Comment by janodvarko** [comment]
Since no STR, it doesn't feel much actionable.

@jasonLaster: I am closing this, but please clone this into Bugzilla if you feel we should have that report, thanks!

Honza
