### ISSUE TITLE
Notify about enabled breakpoints/pause-on state in panel

### ISSUE THREAD

**Issue by digitarald** [firefox-devtools/debugger#8068]
**Overview:** Opening the Debugger and pausing unexpectedly can be frustrating – as the Debugger offers many options to pause and some can be hidden depending on the UI state. The Debugger should be pro-active in informing the user about

**User Stories:**
1. When having `Pause on` checkbox or breakpoint enabled in the Debugger, I want to see it in the Debugger without opening the right accordion, so that I know which pausing options are currently switched on.
2. When having a pausing options (pause on or breakpoint) in the Debugger, I want the Debugger panel tab to show some special state, so that I am aware that the Debugger could pause at some point.

2nd is a stretch goal, but could inform how the 1st story is addressed.

**Brainstorming**

We probably need some UX to provide an _active_ state for the accordion panel headers; using color, font styling, count (enabled breakpoints) and/or an icon.

Chrome shows *active* state for
Enabling throttling: <img width="118" alt="image" src="https://user-images.githubusercontent.com/8599/53764248-98657500-3e81-11e9-9a98-612b32753966.png">
Enabled filters  <img width="273" alt="image" src="https://user-images.githubusercontent.com/8599/53764281-b29f5300-3e81-11e9-9c83-77d5e83c3aae.png"> <img width="233" alt="image" src="https://user-images.githubusercontent.com/8599/53764291-b7640700-3e81-11e9-9bee-6c5ef6c40100.png">

Collected ideas

1. Colored active icon in the panel header.
    - Info ℹ️ is already taken for MDN
    - ⚡️ for powered on?

**⚠️ This issue still needs requirements. Please discuss and propose ideas in the comments to help define the requirements before claiming this issue.**

**Comment by darkwing** [comment]
A few thoughts:

1.  We'd greatly benefit from having the "why paused" block much higher in the right sidebar accordion

2.  The red debug line of an error somewhat communicates why paused

3.  I'd love UX's idea for how to represent those options outside of the sidebar

**Comment by digitarald** [comment]
Added some more ideas to the description.

**Comment by fvsch** [comment]
> The red debug line of an error somewhat communicates why paused

How often do we expect that users may not be on that particular file and line, though?
(As a side note, this only works for users without sight impairments. Not sure that the complementary solutions we're brainstorming would improve that, though.)

**Comment by fvsch** [comment]
Some "Debugger" icon variants I did the other day, which could reflect the Debugger's current state in the toolbox tab. We could also use the state information in the tab's title attribute. Currently it says "JavaScript Debugger", and it could say "JavaScript Debugger (paused on breakpoint)" for instance.

<img width="220" alt="debugger-toolbox-icons" src="https://user-images.githubusercontent.com/243601/53793381-0cf5ed80-3f2e-11e9-8c92-a52fe5d6a4d5.png">

**Comment by jasonLaster** [comment]
@fvsch that looks great

**Comment by digitarald** [comment]
This is great and maybe can inform both the 1st and 2nd point. How would an icon look like for "has breakpoints active"; maybe that could be re-used in both the toolbox panel header and the accordion headers.

If not an icon, another idea would be a simple counter badge on the panels, showing how many pausing options are enabled. Without context, it might still need some icon or label to explain what it means.

**Comment by janodvarko** [comment]
Cloned into Bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1695635

Firefox Developer Tools (including Debugger tool) development is now entirely happening in Bugzilla and new issues should be reported here: https://bugzilla.mozilla.org/enter_bug.cgi?product=DevTools&component=Debugger

Honza
