### ISSUE TITLE
loadSourceText should probably be responsible for pretty-printing files

### ISSUE THREAD

**Issue by loganfsmyth** [firefox-devtools/debugger#8071]
Right now pretty-printing is its own action that kind of hacks its way into the source-loading process. This isn't idea because it means that the promise returned by `loadSourceText` can't consistently handle the case where a file is in the process of being pretty-printed, since don't have a way to know when pretty-printing completes.

**Comment by jasonLaster** [comment]
https://gist.github.com/c11a3614e8669ef071574476aefc747a

**Comment by nagpalm7** [comment]
@loganfsmyth Can I dive in this and give a shot?
