### ISSUE TITLE
Should we keep `Node` in getLibraryFromUrl.js ?

### ISSUE THREAD

**Issue by nchevobbe** [firefox-devtools/debugger#8074]
https://github.com/firefox-devtools/debugger/blob/005afbe56612dbf987c70926e24c97751cc16b55/src/utils/pause/frames/getLibraryFromUrl.js#L35-L38

Where is it supposed to show up? Was it an experiment for when we had Node support? It's causing issue for some frames that aren't part of Node (See [🐞 Bug 1532359](https://bugzilla.mozilla.org/show_bug.cgi?id=1532359) )

**Comment by digitarald** [comment]
@darkwing since this is causing issues with incorrect collapsing (now also in Console) with a very broad pattern, should we remove it for now?
