### ISSUE TITLE
"Skip pausing" UI state is lost after toggling toolbox and refreshing page

### ISSUE THREAD

**Issue by jryans** [firefox-devtools/debugger#8075]
STR:

1. Open debugger
2. Deactivate breakpoints by clicking the "tag with cross" icon in the right panel (this sets `devtools.debugger.skip-pausing` to `true`)
3. Close and reopen toolbox
4. Deactivate breakpoints button is still correctly highlighted
5. Reload the page you are debugging (Cmd-R)
6. Deactivate breakpoints button resets to inactive, but breakpoints are actually still being skipped

Bad:

<img width="359" alt="2019-03-05 at 12 00" src="https://user-images.githubusercontent.com/279572/53804046-5ea67400-3f3e-11e9-911e-c64ade608f68.png">

(pausing is still skipped, but the UI doesn't tell you)

Version:

Firefox Nightly 67.0a1 (2019-03-04)

**Comment by nagpalm7** [comment]
@jasonLaster @jryans Can I take up this issue if no one is working on this?

**Comment by jryans** [comment]
I think @jasonLaster fixed this in m-c via https://bugzilla.mozilla.org/show_bug.cgi?id=1532641.
