### ISSUE TITLE
The "From <generated>" footer unexpectedly always goes to line 1 of generated file

### ISSUE THREAD

**Issue by loganfsmyth** [firefox-devtools/debugger#8088]
When viewing a sourcemapped file, the editor shows a `(From <file>)` footer just below it that will take the users to the generated file. The problem is that this footer [always goes to the first line](https://github.com/firefox-devtools/debugger/blob/ccba51ce44cf97da08b35a33372f0125fc26f74b/src/components/Editor/Footer.js#L175) of the generated file, which I don't think is particularly useful once your bundle grows.

The quickest thing would be to find the line/column of the first mapping in the original file. In a perfect world though, we'd use the current editor scroll position on the original file to pick a specific mapping to jump to in the generated file. 

I'm not familiar with how we track the current position on files, but it may make sense to try to make some common logic for this kind of thing.

**Comment by janodvarko** [comment]
Cloned into Bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1695637

Firefox Developer Tools (including Debugger tool) development is now entirely happening in Bugzilla and new issues should be reported here: https://bugzilla.mozilla.org/enter_bug.cgi?product=DevTools&component=Debugger

Honza
