### ISSUE TITLE
[Column breakpoints] Unexpectedly getting the _second_ breakpoint enabled on line

### ISSUE THREAD

**Issue by loganfsmyth** [firefox-devtools/debugger#8092]
Steps:

1. Open Editor/Tabs.js
2. Find the line in `updateHiddenTabs` that has `hiddenTabs.find(tab => tab.id == selectedSource.id)`
3. Click to add a breakpoint

AR:
The _second_ column breakpoint is enabled.
<img width="493" alt="screen shot 2019-03-06 at 4 34 21 pm" src="https://user-images.githubusercontent.com/132260/53923596-ba035f80-402d-11e9-8bd7-ac6e0c386aec.png">

ER:
The first one would be enabled.

The cause of this is most likely that the second breakpoint is actually the first one, in the _generated_ file. We are likely sorting based on generated position, rather than based on the order for the file you are actually viewing.

It seems wrong that the breakpoints are ordered differently in this case, so I'll be filing a separate bug for that, perhaps the sourcemap is just bad in this case. Filed in #8093

**Comment by jasonLaster** [comment]
closing in favor of https://bugzilla.mozilla.org/show_bug.cgi?id=1533549

**Comment by jasonLaster** [comment]
Thanks @soniasingla this was actually finished in bugzilla
