### ISSUE TITLE
Debugger breaks after refresh and stays in incompleted paused state

### ISSUE THREAD

**Issue by digitarald** [firefox-devtools/debugger#8106]
Debugged profiler.firefox.com, adding and removing breakpoints to debug another issue (hitting breakpoints without having any active) that I have to file. At some piont the debugger would not load completely and show the file in `Loading…` state.

Important to note that the page at this point does not have any breakpoints set.

I can click _Resume_ and hit the next breakpoint (I had 2 set, which I then removed), but the files never load.

Hard and soft refresh on the page did *not* fix the issue. Same for closing and re-opening.

<img width="1025" alt="image" src="https://user-images.githubusercontent.com/8599/54057874-fd360d80-41a8-11e9-9cb6-3bbe09554b63.png">

*NOTE FROM LOGAN*: I'm not convinced that this stack trace is actually the cause of the file being stuck on "Loading..." so let's not focus too much on that for now.
```
error occurred while processing 'sources: Error: can't set breakpoint: script global is not a debuggee
Stack: addScript@resource://devtools/server/actors/breakpoint.js:73:14
setBreakpointAtEntryPoints@resource://devtools/server/actors/breakpoint.js:22:11
applyBreakpoint@resource://devtools/server/actors/source.js:523:5
_addSource@resource://devtools/server/actors/thread.js:1750:19
onSources@resource://devtools/server/actors/thread.js:1145:12
onPacket@resource://devtools/server/main.js:1291:58
receiveMessage@resource://devtools/shared/transport/child-transport.js:66:16
Line: 73, column: 14 main.js:1160
    _unknownError resource://devtools/server/main.js:1160
    onPacket resource://devtools/server/main.js:1294
    receiveMessage resource://devtools/shared/transport/child-transport.js:66
```

**Comment by loganfsmyth** [comment]
I think https://bugzilla.mozilla.org/show_bug.cgi?id=1534847 will resolve the issue of getting stuck in the "Loading..." state. The `onSources` exception seems like most likely a separate issue and we may want to file it in Bugzilla.

**Comment by jasonLaster** [comment]
This should be fixed. We can re-open if we see any new issues
