### ISSUE TITLE
[Preview] Mousing from the token to the popup fails

### ISSUE THREAD

**Issue by jasonLaster** [firefox-devtools/debugger#8107]
This is a fun bug if you mouse from the token to the popup without being careful it can close. The reason for this is that we only watch to see if your're either on the token, arrow, or popup, not the gap in between which i highlighted red.

![gap](https://user-images.githubusercontent.com/254562/54060532-09cb5d80-41cb-11e9-8f3c-c2265f60fdd3.jpg)

**Comment by jasonLaster** [comment]
Thanks @harshlele

**Comment by kciccolella** [comment]
Hello @harshlele,

I was wondering if you are still working on this issue.

**Comment by harshlele** [comment]
@kciccolella hey sorry for keeping this claimed i just got busy. You can take this!

**Comment by kciccolella** [comment]
Thank you @harshlele . Much appreciated.
