### ISSUE TITLE
[breakpoints] They can't be set

### ISSUE THREAD

**Issue by karlcow** [firefox-devtools/debugger#8109]
1. With Firefox Nightly 67.0a1 (2019-03-10) (64-bit) on macOS
2. Go to https://www.msn.com/en-xl/asia/photos/shockingly-realistic-robots/ss-AAxiMLu#image=7
3. Open the developer tools (debugger)
4. Go to [this script](https://c-8oqtgrjgwu46x24uvcvke-gpvgtvckpogpv-ywu-u-oup-eqox2ecmcockbgf.g01.msn.com/g00/3_c-8yyy.oup.eqo_/c-8OQTGRJGWU46x24jvvrux3ax2fx2fuvcvke-gpvgtvckpogpv-ywu-u-oup-eqo.cmcockbgf.pgvx2fgp-znx2fcukcx2f_uex2flux2fd665801c-x2ffktgevkqpx3dnvt.nqecngux3dgp-zn.vjgogux3ditca.frkx3dtguqnwvkqp4zx2ff7-f45908-d05f83e6x2ff9-7c5d88-fe31261dx2f40-3eg103-382f2c0gx2f71-59hge2-52g7f66dx2ff1-444627-7711fcdfx2f9g-c4hfg5-g98fdee5x2f1g-c9c477-80ffd4cdx2fc1-ce1d70-80ffd4cdx2f3d-4cefee-80ffd4cdx2f8e-45g1c0-ecg60141x2f1e-849d92-f3h0hd65x2f64-1c5e2e-4h8f8f30x2ffc-200ee7-7414784cx2f90-4826d3-80ffd4cdx2f8g-c20h19-80ffd4cdx3fx78gtx3d42312526_36819797x26hfjgcfx3dkpvtcctkpvnx2cowkfhnv483ehx2cowkfhnv522ehx2cuvctvgfig3ehx2crncvciagfig3ehx2cdkpieqnncdgfig3ehx2ceqornkcpeggfig3ehx2cctvkeng3ehx26euqrfx3d42302543207540x26euqrfdx3d42312440316063x26k32e.octmx3duetkrv_$/$/$/$/$/$/$/$/$/$/$/$/$/$/$/$/$/$/$/$/$/$?i10c.ua=2&i10c.dv=14)
5. Click on the braces `{}`
6. Go to the lines  
```js
    function tf() {
      wt.click(function (n) {
        pi(n, - 1);
        i.pub(lt, {
          args: n
        })
      }).on(ft, iu).on(ct, ru);
      pt.click(function (n) {
        pi(n, 1);
        i.pub(lt, {
          args: n
        })
      }).on(ft, iu).on(ct, ru);
```
7. Try to set a breakpoint on `wt.click(function (n) {` or anything in there in fact.

Expected:
The breakpoint is set

Actual:
Nothing happens.

**Comment by chujunlu** [comment]
Hey, can you point out the script file you went to in the source tree? Maybe make a screenshot? I can't find the script you have in step 4.

**Comment by jasonLaster** [comment]
Thanks for sharing @karlcow 

@loganfsmyth couldyou take a look?

**Comment by jasonLaster** [comment]
Hmm, so i was able to set breakpoints. My process was to 

1. go to the site
2. go to project search and search `wt.click`
3. click pretty print aka `{}`
4. search `wt.click`
5. click to add breakpoints

**Comment by karlcow** [comment]
Let me try this morning.
Working in `67.0a1 (2019-03-11) (64-bit)`
Thanks @jasonLaster
