### ISSUE TITLE
HMR updates duplicates files and breakpoints

### ISSUE THREAD

**Issue by digitarald** [firefox-devtools/debugger#8113]
Using a _next.js/typescript_ project, edits on `index.tsx` that trigger HMR add a new `index.tsx`, and duplicate its breakpoint.

STR:
- Set up a local project with next.js: [Instructions](https://github.com/zeit/next.js/tree/master#setup)
- Start the server
- Open page and debugger
- Edit the _index_ page in your editor

Reproduce on both Release (65) and Nightly (67).

Chrome does not reproduce the issue.

![ScreenFlow](https://user-images.githubusercontent.com/8599/54145540-715ff380-43eb-11e9-855e-bd07c8298020.gif)

**Comment by janodvarko** [comment]
Cloned into: https://bugzilla.mozilla.org/show_bug.cgi?id=1694907

Firefox Developer Tools (including Debugger tool) development is entirely happening in Bugzilla and new issues should be reported here: https://bugzilla.mozilla.org/enter_bug.cgi?product=DevTools&component=Debugger

Honza
