### ISSUE TITLE
Paused Debugger continues without interaction

### ISSUE THREAD

**Issue by digitarald** [firefox-devtools/debugger#8116]
Reproduced locally in a next.js project. While being paused the Debugger randomly continues and the page seems to refresh. Not sure if next.js triggers a refresh or something, but that should not interfer with the paused state.

![ScreenFlow](https://user-images.githubusercontent.com/8599/54255368-0ca0b800-4515-11e9-96de-1c13d41c1fe9.gif)

**Comment by janodvarko** [comment]
@digitarald is this still reproducible? If yes, do you have a public test case?
Honza

**Comment by digitarald** [comment]
I have not seen this for a while.
