### ISSUE TITLE
`this` resolved incorrectly as `undefined`

### ISSUE THREAD

**Issue by digitarald** [firefox-devtools/debugger#8117]
Local next.js project, need to work on a glitch to have a hosted STR later.

Pausing on a react DOM event, this should bound to the class instance. It is set, as the state can be read; but Debugger resolves it as `undefined`, but when maps are resolved and without.

<img width="322" alt="image" src="https://user-images.githubusercontent.com/8599/54255416-3f4ab080-4515-11e9-8efd-d11c9700109c.png">

**Comment by ruturajv** [comment]
So to understand it clearly ...
- the code runs fine
- its just that the debugger's `this` resolution is incorrect, is it ?

So the fix is essentially binding `this` to the correct `this`?

**Comment by shakti97** [comment]
Can I work on this issue? @digitarald can you please mention the file name

**Comment by digitarald** [comment]
@shakti97 me moved development to bugzilla and I have not seen this bug being filed there. Trying to reproduce without luck so far, so closing this one.

You can find more good first bugs in https://codetribute.mozilla.org/projects/devtools?tag%3Dgood-first-bug%26project%3DDebugger

**Comment by janodvarko** [comment]
Seems like this should have been closed in the last comment.
Closing now.
Honza
