### ISSUE TITLE
"Go to file" loses the ability to select results if hitting up or down key when results.length==0

### ISSUE THREAD

**Issue by fvsch** [firefox-devtools/debugger#8118]
STR:

1. Go to https://firefox-dev.tools/debugger-examples/examples/todomvc/ and open Debugger
2. Use the Ctrl+P shortcut to show the "Go to file" input
3. Type a search string that matches nothing, e.g. "fjklsfljkks"
4. Hit the Up arrow key once
5. Remove the non-matching search string and type "back"
6. Hit the Down arrow key once

Expected result:
After step 5, two results show up, with the first result (`backbone.js`) highlighted in blue.
In step 6, hitting the Down arrow should put the focus on the second result (`backbone.localStorage.js`).

Actual result:
After step 5, two results show up, and no result is highlighted.
In step 6, no result is highlighted.

**Comment by fvsch** [comment]
Using React Devtools, it looks like when you hit Up or Down in "Go to file" and there are currently 0 results, the `state.selectedIndex` ends up being `NaN`. From them on, if we try to add or substract `1` to that index, it will remain stuck at `NaN`, breaking the keyboard navigation completely.

![Debugger screenshot](https://user-images.githubusercontent.com/243601/54299887-17625800-45bc-11e9-92fc-8183047d588e.png)

**Comment by darkwing** [comment]
Great find @fvsch !

**Comment by WenInCode** [comment]
the good ol' divide by zero game!
