### ISSUE TITLE
"Go to file" selected index can be out of bounds when showing limiting the number of results

### ISSUE THREAD

**Issue by fvsch** [firefox-devtools/debugger#8119]
It looks like the "Go to file" result list is clipped at maybe 100 items, but when the actual result count is higher then users can use the keyboard to lose the currently selected index.
My guess is that we store an index for the currently selected item, and compare it to the result count instead of comparing it to the number of rendered items.

STR:

1. Go to https://firefox-dev.tools/debugger-examples/examples/500-sources.html
2. Hit Ctrl+P to show the "Go to file" input
3. Type "js" to show many results
4. Hit the Up key 5 times.
5. Hit the Down key 5 times.

Expected results:
- In step 3, we should get a list of 100 results displayed.
- In step 4, the first "Up" action should cycle back to the last item (index `99`, if it's a numeric 0-indexed value), then the next "Up" actions should go up in the list (up to index `95`).
- In step 5, the "Down" actions should go down in the list, and the fifth "Down" should cycle back to the first item in the list.

Actual results:
- In step 4, the first "Up" action removes any visible selection.
- In step 5, the fifth "Down" action restores the selected state to the first item.

**Comment by fvsch** [comment]
So, when we have 502 results in `QuickOpenModal`, we manage this component's `state.selectedIndex` according to that length. So hitting the Up key once gives you `state.selectedIndex === 501`:

![screenshot](https://user-images.githubusercontent.com/243601/54297651-91dca900-45b7-11e9-8448-c43e991f04c3.png)

Then we pass two things to the `ResultList` component:
```jsx
<ResultList
  selected={this.state.selectedIndex}
  items={this.state.results.slice(0, 100)}
/>
```
(Schematically, I haven't checked the actual code. :P)

So ResultList gets max 100 items, but it can get a selectedIndex above `99`:

![screenshot](https://user-images.githubusercontent.com/243601/54297842-ee3fc880-45b7-11e9-8082-eea0ab3489c9.png)

The fix might be to clip the number of results before adding them to QuickOpenModal's `state.results`.

**Comment by arosenfeld2003** [comment]
@fvsch I'd like to take a stab at this... first PR in the codebase.
