### ISSUE TITLE
Remove react-inlinesvg

### ISSUE THREAD

**Issue by fvsch** [firefox-devtools/debugger#8121]
Looks like we only have two inline SVG icons: one for breakpoints in the left gutter, and one for column breakpoints.

Since we use `react-inlinesvg` for that, and that the way we use it seems very limited (we don't do HTTP requests for external SVG icons with cross-domain IE polyfilling or that kind of thing), the feature we are using boils down to this bit of code:

```js
render() {
   return wrapper({
      style,
      className: this.getClassName(),
      dangerouslySetInnerHTML: html,
    }, content);
}
```

We could probably remove that dependency, and replace Svg.js with a more specific BreakpointSvg.js which hardcodes the two relevant SVG files in strings:

```jsx
const LINE_SVG = `<svg ...></svg>`;
const COLUMN_SVG = `<svg ...></svg>`;

...

render() {
  return <span dangerouslySetInnerHTML={this.props.column ? COLUMN_SVG : LINE_SVG} />
}
```

**Comment by jasonLaster** [comment]
This would be great!

**Comment by fvsch** [comment]
There is also a big section of https://github.com/firefox-devtools/debugger/blob/master/docs/local-development.md on SVG that will need to be updated. I can do that in a follow-up PR if needed.
