### ISSUE TITLE
Variable preview doesn't work on lines with column breakpoints

### ISSUE THREAD

**Issue by digitarald** [firefox-devtools/debugger#8122]
STR:
- Open Debugger on https://firefox-dev.tools/debugger-examples/examples/todomvc/
- Open `js/views/app-view.js` file
- Set line breakpoint in _line 52_, `var completed = app.todos.completed().length;`
- Add a todo in todomvc to trigger a render to hit the breakpoint
- Hover `completed` variable

AR: No tooltip on hover.
ER: Variable tooltip.

While being paused, the BP can be removed which makes the tooltip work.

Mouse is hovered over `completed`:
<img width="448" alt="image" src="https://user-images.githubusercontent.com/8599/54310437-99885780-458f-11e9-8a6a-b9dd62535ef3.png">

<img width="363" alt="image" src="https://user-images.githubusercontent.com/8599/54310600-fb48c180-458f-11e9-9a4a-951989f9df29.png">

**Comment by jasonLaster** [comment]
![](http://g.recordit.co/NMPs3jPEXZ.gif)

**Comment by nagpalm7** [comment]
I would like to work on this, Can you tell me from where should I start.

**Comment by phoenixking25** [comment]
![debugger](https://user-images.githubusercontent.com/22527880/54647025-1010e200-4ac7-11e9-8ec6-ffb79f4965be.gif)
Its working good for me

**Comment by janodvarko** [comment]
This seems to be fixed, closing.

Honza
