### ISSUE TITLE
Call stack does not show column information

### ISSUE THREAD

**Issue by digitarald** [firefox-devtools/debugger#8123]
When stepping through columns in the same line, I want to see the column information in the callstack, so that I can tell frames apart.

<img width="777" alt="image" src="https://user-images.githubusercontent.com/8599/54312322-e40bd300-4593-11e9-8b0c-a2be51edcee6.png">

**Comment by jasonLaster** [comment]
hmm,I feel like this could also be pretty noisy if we always include column information.

CC @fvsch @darkwing

**Comment by fvsch** [comment]
Two ideas to show the column numbers only in some conditions (and avoid noise in the majority cases):

1. By default, only show line numbers for frame locations. If the call stack contains a column breakpoint, also show column numbers for all frames. That way, call stacks that only have "line" breakpoints, call stacks for "paused on exception", etc., keep the same display as before, but if you use column breakpoints you also get that information.

2. Show the column number for a frame that corresponds to a column breakpoint. So the above example would have a call stack looking like:

```
default       pasteManager.js:13:64
default          pasteManager.js:13
```

**Comment by digitarald** [comment]
> Two ideas to show the column numbers only in some conditions (and avoid noise in the majority cases):

👍 , the solution should be smart enough to only show columns when needed to save precious space.

**Comment by nagpalm7** [comment]
What if we group all the call on the same line and show them as a drop-down list with columns specified as we are showing line numbers and line number will be only visible on the header. This way we can save space as well make it a little bit more elegant. @fvsch @digitarald

**Comment by fvsch** [comment]
Not sure, I'd like to see of mockup of that.
One thing to consider: we already group stacks in collapsible groups for common framework/lib frames, with the intent of telling users "you probably can ignore this", so if we use the same kind of grouping it could send the wrong message.

**Comment by nagpalm7** [comment]
> One thing to consider: we already group stacks in collapsible groups for common framework/lib frames, with the intent of telling users "you probably can ignore this", so if we use the same kind of grouping it could send the wrong message.

Hmm, it was a bad idea.

**Comment by fvsch** [comment]
Looking at Nightly, it seems we're always showing the column information for all breakpoints in the Breakpoints pane.

![Selection_003](https://user-images.githubusercontent.com/243601/54870692-43df5680-4daa-11e9-908c-42ff029fea77.png)

And Console locations are showing the column too when it's available:

![Selection_004](https://user-images.githubusercontent.com/243601/54870736-a33d6680-4daa-11e9-840c-dfa8b5df043e.png)

Should we just do the same for consistency's sake, at the risk of being noisy?

**Comment by janodvarko** [comment]
Cloned into:
https://bugzilla.mozilla.org/show_bug.cgi?id=1661465

We moved our bug tracking into bugzilla, so please report new bugs there: 
https://bugzilla.mozilla.org/enter_bug.cgi?product=DevTools&component=Debugger

Honza
