### ISSUE TITLE
[QuickOpen] we should show the end of the path

### ISSUE THREAD

**Issue by jasonLaster** [firefox-devtools/debugger#8124]
I've found it can be hard to see the relevant paths the way we're truncating

<img width="771" alt="Screen Shot 2019-03-13 at 5 31 26 PM" src="https://user-images.githubusercontent.com/254562/54316063-31993780-45b6-11e9-90e7-02923885e376.png">

**Comment by WenInCode** [comment]
@jasonLaster do you think it would be better to show end of the path over what is currently being displayed?

**Comment by WenInCode** [comment]
Or perhaps doing something like [ellipsis in the middle](https://ux.stackexchange.com/a/40329)

**Comment by WenInCode** [comment]
Some context for potential contributors:
- we [truncate the end of the relative path](https://github.com/firefox-devtools/debugger/blob/master/src/utils/quick-open.js#L67) of sources in the sources list
- [`endTruncateStr` function](https://github.com/firefox-devtools/debugger/blob/master/src/utils/utils.js#L47-L52)
