### ISSUE TITLE
[Sources] Improve design of thread group headers

### ISSUE THREAD

**Issue by fvsch** [firefox-devtools/debugger#8128]
It looks like in some situations we are grouping sources under "Main thread", "Workers", etc.

The UI for those group headers looks a bit raw:
- It adds a bit too much space at the top (we would like to keep items starting at 4px from the top edge).
- Not sure those headers have the same height as other items.
- Horizontal text alignment is a bit off.
- Most importantly, they don't come off as headers. Maybe we should make them bold or find some other way to make sure the grouping is obvious to users.

@jasonLaster do you know:
- if we have an existing UI spec for that, or we should just make it up and try to be consistent with other work on Debugger panes? (https://github.com/firefox-devtools/ux/issues/45)
- if there are specific steps to reproduce to show those headers? (I'm only seeing them in Nightly, not in launchpad, and only sometimes)

**Comment by fvsch** [comment]
Current style:

![debugger-sources-thread-header-current](https://user-images.githubusercontent.com/243601/54543159-6eda3c80-499d-11e9-99d8-57a9e8a803f5.png)

Here's what it would look like if we used the same style as accordion headers:

![debugger-sources-thread-header-improved](https://user-images.githubusercontent.com/243601/54543209-83b6d000-499d-11e9-9abe-7caa1a424995.png)

Maybe we should just go and use the accordion component, making each group collapsible?

**Comment by abhiaecs** [comment]
Hey!
Is this bug already claimed? Or can you assign it to me?

**Comment by fvsch** [comment]
We might need to decide on the design first.

@jasonLaster I remember you said on Slack that you wanted to have a single tree with the threads/workers as the first level nodes?

**Comment by jasonLaster** [comment]
yep - i was planning on a single tree.

**Comment by fvsch** [comment]
Fixed by Jason in 69 I believe.
