### ISSUE TITLE
[Scopes] Horizontally scrolling the Scopes panel hides its header

### ISSUE THREAD

**Issue by fvsch** [firefox-devtools/debugger#8129]
We are using `overflow: auto` on the wrong container for the Scopes panel, and when content overflows to the right and you scroll then the accordion header scrolls along with the content:

![Selection_026](https://user-images.githubusercontent.com/243601/54420435-4686df80-470a-11e9-800e-f0b70599f00e.png)

**Comment by helenatxu** [comment]
Hello! Is this still available? Can I /claim it?

**Comment by fvsch** [comment]
@helenatxu It's yours. :) Feel free to ask for any help or feedback.

**Comment by helenatxu** [comment]
Hello @fvsch 
Sorry I just saw your message. I will work on this right now, thanks!

**Comment by helenatxu** [comment]
@fvsch as I pushed my patch to Phabricator, should we close this issue? :)

**Comment by fvsch** [comment]
I don't think we can land the patch on Phabricator without a Bugzilla bug number.
Can you close the Diff on Phabricator and make a PR against this repo, instead?
