### ISSUE TITLE
Auto-fill watch expression text if expression is selected in editor

### ISSUE THREAD

**Issue by dhyey35** [firefox-devtools/debugger#8140]
This is a feature request. 

Most of the times when I am debugging after I select and hover over an expression I sometimes want to add it to the watch expressions. So I need to copy paste the value everytime. Instead we could have a feature where if the editor has some text selected than when the user clicks on `+` button in `Watch Expressions` panel, the selected text is automatically filled in the input box. 

I think this is a pretty practical use case.

![debugger-w1](https://user-images.githubusercontent.com/11143604/54605764-0314d400-4a70-11e9-87aa-5ef080f6b8fc.png)

In above screenshot `this.model` should have been added to the input box.

**Comment by WenInCode** [comment]
@dhyey35 I believe you can already do this via the context menu. Highlight the expression you wish to watch and right click to open the context menu, there should be an option to add as watch expression.

![watchexp](https://user-images.githubusercontent.com/5448834/54781148-1f844e00-4be1-11e9-9a1d-78aa1627e452.gif)

Does this cover what you are looking for?

**Comment by dhyey35** [comment]
@clarkbw Yes
