### ISSUE TITLE
Debugger pauses on exception once after disabling it

### ISSUE THREAD

**Issue by juliandescottes** [firefox-devtools/debugger#8143]
STRs:
- open Debugger
- uncheck all "Pause on exceptions" checkboxes
- go to https://zest-aardvark.glitch.me/
- in the Debugger, check "Pause on exceptions", then uncheck it
- in the webpage, click on the first button "exUncaught()"

ER: the Debugger should not stop on the uncaught exception
AR: the Debugger breaks on the exception. If you resume and click on the button again, the Debugger will not break anymore.

**Comment by loganfsmyth** [comment]
Refiled in https://bugzilla.mozilla.org/show_bug.cgi?id=1538054 since this is a server issue.
