### ISSUE TITLE
Remove animated background from the Threads list

### ISSUE THREAD

**Issue by digitarald** [firefox-devtools/debugger#8145]
DevTools doesn't animate backgrounds for current selection in other lists; and animating for both focus/blur makes the selection feel a bit noisy and slower than necessary.

![Screen Recording (Firefox Nightly)](https://user-images.githubusercontent.com/8599/54707312-06ef3780-4afe-11e9-8008-91999d9eff38.gif)

**Comment by chujunlu** [comment]
Hi @digitarald ! I wasn't able to make the "Threads" section display. I looked into ⁨`src⁩/⁨components⁩/SecondaryPanes/Workers.js` and ⁨`⁨src⁩/reducers⁩/debuggee.js` but I'm not sure that I'm heading to the right direction. Would you mind letting me know your STR? Thank you!

Here's what I have in debugger now:
<img width="385" alt="Screen Shot 2019-03-20 at 9 32 11 PM" src="https://user-images.githubusercontent.com/38041280/54729115-02f00380-4b58-11e9-9e65-5956ddc72179.png">

**Comment by digitarald** [comment]
@chujunlu sorry for not providing a clearer STR. For the _Thread_ panel to appear you need a page with a web worker running, like http://mdn.github.io/simple-web-worker/

**Comment by chujunlu** [comment]
Thanks for getting back to me! I used debugger launchpad to debug http://mdn.github.io/simple-web-worker/. Thread pane still doesn't show up. Are you using FireFox build?

**Comment by digitarald** [comment]
@darkwing could maybe help with why this isn't working.

**Comment by darkwing** [comment]
Hello @chujunlu !  This actually got fixed on Mozilla Central, so I'll close this one for now.  Thank you for looking into it!
