### ISSUE TITLE
[Threads] Align threads list with UI spec

### ISSUE THREAD

**Issue by fvsch** [firefox-devtools/debugger#8149]
UI spec here: https://github.com/firefox-devtools/ux/issues/45#issuecomment-457021260
It doesn't include anything on Threads, but the same general rules should apply.

**Comment by fvsch** [comment]
Related issue: #8145.

**Comment by nagpalm7** [comment]
@fvsch Can I take this issue?

**Comment by fvsch** [comment]
Definitely. :)

**Comment by fvsch** [comment]
Closing this issue in favor of the Bugzilla [bug 1543581](https://bugzilla.mozilla.org/show_bug.cgi?id=1543581), which should be close to landing.
