### ISSUE TITLE
Source sometimes missing in source pane after reopening DevTools

### ISSUE THREAD

**Issue by juliandescottes** [firefox-devtools/debugger#8150]
Tested in Firefox in latest central.

STRs:
- open https://rumbling-trail.glitch.me/ (default webpage from glitch)
- open debugger
- script.js should be visible 
![image](https://user-images.githubusercontent.com/1141550/54753287-f2d03680-4be0-11e9-9944-e3f8f29b171d.png)
- close and reopen devtools a few times. For me `script.js` is no longer visible after a few attempts. 
![image](https://user-images.githubusercontent.com/1141550/54753406-4478c100-4be1-11e9-878a-f4364065cd9c.png)

No relevant error in the browser console. If you reload the page, then script.js appears again.

**Comment by loganfsmyth** [comment]
This is tracked in https://bugzilla.mozilla.org/show_bug.cgi?id=1503422
