### ISSUE TITLE
FF Debugger doesn't show the file content

### ISSUE THREAD

**Issue by harry1989** [firefox-devtools/debugger#8160]
Cross posting from https://bugzilla.mozilla.org/show_bug.cgi?id=1538629:

I have an internal website for which the debugger doesn't show the file content, instead it shows absurd 30000. There are no error messages and helpful whatsoever regarding this. The functionality of the site isn't affected, but that debugger doesn't show any content, it is hindering the debugging.

**Actual results:** Debugger is showing '30000' instead of actual file content.
**Expected results:** Debugger should have shown the javascript file content properly
**User Agent:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.36 26.121 Safari/537.36
**Screenshot:** 
![Firefox debugger issue](https://user-images.githubusercontent.com/1428935/54933114-0c0b1700-4f42-11e9-810d-d88aaf40ae05.png)

**Comment by nmicht** [comment]
Closing this, no test case was provided neither response in the last 6 months.
