### ISSUE TITLE
CSS diff should show/have a reset/revert button

### ISSUE THREAD

**Issue by rugk** [firefox-devtools/debugger#8171]
The CSS inspector now has this nice "Changes" tab I can use to copy my changes.

**However**, when I got to this tab, what i (as a developer) expected to find, was also a "reset changes" or "revert" button on the same page, so I can (similar to when I view changes in git) just revert everything and restart from scratch.

AFAIK there is no other easy way (except of reloading, but this may not be possible/wanted) to restart from a clean state.

---

originally reported https://bugzilla.mozilla.org/show_bug.cgi?id=1539790, don't know what is the better place :thinking:

**Comment by nchevobbe** [comment]
hello, bugzilla is the place is supposed to be, so I'll close this one :) 

(this repo is only for the debugger panel)
