### ISSUE TITLE
detecting virtual keyboard with about:debugging (remote debugging)

### ISSUE THREAD

**Issue by karlcow** [firefox-devtools/debugger#8176]
Hi,

This is a practical example of a hurdle. It's probably a duplicate of breakpoints for events listeners. I just put here, because sometimes the devtools team is asking what are the practical issue.

0. With Firefox Nightly 68.0a1 (2019-04-01) (64-bit) on desktop AND android.
1. Open Firefox on desktop with about:debugging
2. On Firefox Android go to https://www.geeksforgeeks.org/loops-in-javascript/
3. On Desktop, Inspect and go to the debugger
4. On Device, tap login button, then tap on username or email

You see the modal window disappears on Firefox (not in Chrome).

What do we need:
Here I want to be able to detect the fact that the virtual keyboard has popped up and changed either height or triggered a resize event. So I can investigate the source. But because we lack the events debugger, we need to tap in the dark for investigating.

**Comment by karlcow** [comment]
And the practical issue where this is happening is 
https://webcompat.com/issues/28446

**Comment by janodvarko** [comment]
Thank you for the reporting this Karl

I just cloned it into Bugzilla report: https://bugzilla.mozilla.org/show_bug.cgi?id=1694905

Firefox Developer Tools (including Debugger tool) development is entirely happening in Bugzilla and new issues should be reported here: https://bugzilla.mozilla.org/enter_bug.cgi?product=DevTools&component=Debugger

Honza
