### ISSUE TITLE
Deactivate Breakpoints button not working in Launchpad

### ISSUE THREAD

**Issue by jaril** [firefox-devtools/debugger#8178]
Clicking on the deactivate breakpoints button does not toggle it to an active state where breakpoints are skipped.

![Apr-02-2019 10-44-33](https://user-images.githubusercontent.com/15959269/55411874-64d74280-5534-11e9-90cc-193db8809909.gif)

![image](https://user-images.githubusercontent.com/15959269/55412421-67866780-5535-11e9-9bfe-a012eaff2212.png)

**Comment by jasonLaster** [comment]
@jaril my guess is that you're not debugging Nightly...

**Comment by jaril** [comment]
Just double checked, this happens while debugging a Nightly tab `68.0a1 (2019-04-02)`.

**Comment by jasonLaster** [comment]
Thanks.

**Comment by AnshulMalik** [comment]
So this occurs in launchpad, because we have two thread-client files, one of them gets some change and not the other. We should merge both and try to keep them updated.
