### ISSUE TITLE
Command-G should find the next result within the file

### ISSUE THREAD

**Issue by mnoorenberghe** [firefox-devtools/debugger#8180]
STR:
1. Open file in debugger
2. Press Command-F to open the search bar
3. Type the search term… the first result gets highlighted and scrolled into view
4. Press Command-G to find the next result

Expected result:
the next result is brought into view

Actual result:
Nothing 😢 

One of my main annoyances with the debugger is that Command-G doesn't work to find the next match… I need to first focus the search bar and then hit Enter instead. It seems like this used to work since #1231 implemented it but it doesn't work for me on Nightly on macOS.

**Comment by chujunlu** [comment]
Hi, I did some experiment of this issue on my mac. When there are more than 2 matching results, `Command+G` works - showing the next result. It doesn't work when there are 2 matching results. Is it what you found?

**Comment by mnoorenberghe** [comment]
When I filed the bug I was searching for something with 2 matches so that’s
probably what I saw.
-- 
Sent from my phone

**Comment by arosenfeld2003** [comment]
@chujunlu are you working on this?  If not, I would like to claim it...

**Comment by arosenfeld2003** [comment]
So in my experiment, `Command+G` seems to skip every other search result.  Did you find this as well @mnoorenberghe or  @chujunlu?  Please let me know if you're working on this issue, otherwise I am considering claiming it if that's ok...

**Comment by chujunlu** [comment]
Hey @arosenfeld2003 ! Yes I found that too and I did some research in the code base for it. If you don't mind, may I continue to work on it? Thanks!

**Comment by chujunlu** [comment]
Hey, I submitted a patch to Mozilla central which fixed the issue. Once debugger on Github is synced and there isn't regression that the fix causes, this issue could be closed.
