### ISSUE TITLE
Welcome screen: Remove white bottom bar 

### ISSUE THREAD

**Issue by violasong** [firefox-devtools/debugger#8192]
This seems unnecessary and looks a little buggy when overlapped by the shortcut text:

<img width="795" alt="image" src="https://user-images.githubusercontent.com/55994/56323791-c77a3200-6121-11e9-80b9-acb671dc2655.png">

**Comment by darkwing** [comment]
@derek-li Care to look at this one?  I tried adding `z-index: 10` to the footer, which works, but it hides the right border

**Comment by violasong** [comment]
I looked at this just for fun :D what about:

.welcomebox {
- bottom: var(--editor-footer-height);
+ bottom: 0;
}

**Comment by derek-li** [comment]
@violasong 

Just tried your suggestion, seems like it's making the footer disappear completely? 
I'm seeing this:
![e9469dfc5ca12360959a93552bae4b19](https://user-images.githubusercontent.com/33161837/56394660-dbd73100-61ec-11e9-8d9c-2da6bcd30ab6.png)

**Comment by violasong** [comment]
Oh, I see - in dock-to-bottom mode, it shouldn't have a toolbar, but it does need the toolbar in dock-to-side.

<img width="1181" alt="image" src="https://user-images.githubusercontent.com/55994/56395124-33c26780-61ee-11e9-964b-e417a2ee3200.png">
