### ISSUE TITLE
Add hover state and title to sources entries

### ISSUE THREAD

**Issue by digitarald** [firefox-devtools/debugger#8193]
The sources tree can feel surprisingly non-interactive compared to Chrome

1. Chrome shows the full title of the entry via tooltip, which can help for smaller sources panel widths
2. Chrome has a visual hover state

<img width="369" alt="image" src="https://user-images.githubusercontent.com/8599/56389206-cb6b8a00-61dd-11e9-825d-d539a39ead2e.png">

<img width="369" alt="image" src="https://user-images.githubusercontent.com/8599/56389231-dcb49680-61dd-11e9-8e14-2b8e256f483d.png">

_(In both I hover the line after the selected entry, one day I figure out why OSX doesn't capture my cursor even with the option checked)_

Fixes:
1. Add title
2. Add hover state, similar to Inspector and Network panel

**Comment by darkwing** [comment]
Good idea.  For the hover color, we should use the same colors (for each theme) as we do the quick open hover

**Comment by darkwing** [comment]
THis was completed in MC>
