### ISSUE TITLE
I have a "TypeError: can't access dead object" on tab.onUpdate from console.log or the tab.js

### ISSUE THREAD

**Issue by AndRo-Marian** [firefox-devtools/debugger#8195]
let tabs = { status: "created", website: null };

    function onTabUpdated(id, changeInfo, tabInfo)
    {
        if (tabs.status === "loading")
        {
            console.log();
        }

        switch (tabs.status)
        {
            case "created":
            {
                if (changeInfo.hasOwnProperty("url"))
                {
                    let website = storage.addWebsite(changeInfo.url);
                    let page = browser.runtime.getURL("tab/tab.html");

                    tabs.status = "holding";
                    tabs.website = website;

                    browser.tabs.update(id, {
                        url: page
                    });
                }
                break;
            }
            case "loading":
            {
                break;
            }
            case "completed":
            {
                break;
            }
        }
    }

    function onTabActivated(activeInfo)
    {
        if (tabs !== undefined && tabs.status === "holding")
        {
            tabs.status = "loading";

            browser.tabs.update(activeInfo.tabId, {
                url: tabs.website.url.href,
            });
        }
    }

    browser.tabs.onUpdated.addListener(onTabUpdated);
    browser.tabs.onActivated.addListener(onTabActivated);

    // Html page:

    <!DOCTYPE html>
    <html lang="en">
        <head>
            <meta charset="UTF-8">
            <title>Holding Tab</title>
            <link id="icon" rel="shortcut icon" href="../icons/favicon.png" type="image/png">
        </head>
        <body>
            <div class="data">
                <span class="header">* REDIRECTING *</span>
                <div class="image"><img id="logo" src="" alt="logo"></div>
                <div class="title"><span id="title">...</span></div>
                <div class="url"><a id="url">...</a></div>
            </div>
            <script src="tab.js" type="text/javascript"></script>
        </body>
    </html>

    The tab.js is empty:

The error is after the tab was clicked:

    error occurred while processing 'sources: TypeError: can't access dead object
    Stack: createSourceActor@resource://devtools/server/actors/utils/TabSources.js:240:5
    onSources@resource://devtools/server/actors/thread.js:1238:7
    onPacket@resource://devtools/server/main.js:1286:15
    receiveMessage@resource://devtools/shared/transport/child-transport.js:66:5
    Line: 240, column: 5 main.js:1155
        _unknownError resource://devtools/server/main.js:1155
        onPacket resource://devtools/server/main.js:1289
        receiveMessage resource://devtools/shared/transport/child-transport.js:66

If i remove the console.log or the tab.js for html page the error disappear. But why ?

**Comment by janodvarko** [comment]
It's been a while and this should be fixed.

@AndRo-Marian if you are still experiencing this issue, can you please create a new report here:
https://bugzilla.mozilla.org/enter_bug.cgi?product=DevTools&component=Debugger

Firefox Developer Tools (including Debugger tool) development is entirely happening in Bugzilla and new issues should be reported there.

Honza
