### ISSUE TITLE
Allow to disable halting on 'debugger' statements

### ISSUE THREAD

**Issue by SebastianZ** [firefox-devtools/debugger#8228]
There are some websites that use dynamically generated `debugger` statements to protect their website from being inspected, e.g. by using code like `setInterval(function() { eval('debugger;'); }, 500);`.

Also, there are cases in which you don't want to stop on `debugger` statements you've set in your code and just skip over them.

For those cases there should be an option to simply skip over those statements and continue the execution.

See also the related issue #828, where this feature was already mentioned.

Sebastian

**Comment by schnippe** [comment]
I did a binary patch of the js debugger statement in libxul.so/dll to something else.

**Comment by schnippe** [comment]
As a one liner:
> cp -n libxul.so{,.prePatch}; dd of=libxul.so if=<(printf "dbbbgggr") obs=1 conv=notrunc seek=$(strings -t d libxul.so | egrep "^[0-9]* (debugger|padStart)$"| grep padStart -A 0 -B 1 | head -n 1|cut -d" " -f1); diff <(xxd libxul.so) <(xxd libxul.so.prePatch)
\< 05d17360: 6179 0064 6179 5065 7269 6f64 0064 6262  ay.dayPeriod.dbb
\< 05d17370: 6267 6767 7200 6465 6369 6d61 6c00 6465  bgggr.decimal.de
--
\> 05d17360: 6179 0064 6179 5065 7269 6f64 0064 6562  ay.dayPeriod.deb
\> 05d17370: 7567 6765 7200 6465 6369 6d61 6c00 6465  ugger.decimal.de


This will probably disturb Widevine DRM. 

@jasonLaster :
A simple "Disable debugger Statement", possibly in about:config would be very helpfull.

The js in the [stackoverflow post](http://stackoverflow.com/q/41801175/432681)  @SebastianZ  mentioned,  is crashing or lagging my developer tools windows and the current tab, in so far we are talking about a kind of denial of service bug.

**Comment by loganfsmyth** [comment]
Closing in favor of https://bugzilla.mozilla.org/show_bug.cgi?id=1578220

**Comment by jonluca** [comment]
It looks like conversation on this has stalled - as a web security researcher, this would be a great feature.

**Comment by arizvisa** [comment]
Yep. Agreed. Not sure why this problem has lasted 5 years either.

**Comment by SebastianZ** [comment]
The development of the Debugger doesn't happen here anymore. As @loganfsmyth pointed out three comments above, you should follow https://bugzil.la/1578220.

Also, please avoid "me too" comments there and instead vote for it or provide feedback that helps implementing that feature.

Sebastian
