### ISSUE TITLE
[event breakpoints] persistence of breakpoints across contexts

### ISSUE THREAD

**Issue by karlcow** [firefox-devtools/debugger#8235]
1. With Firefox Nightly 69.0a1 (2019-06-25) (64-bit) on macOs
2. Open a window on https://wikipedia.org/
3. Open the debugger
4. Click on any event checkbox on the right panel
5. Open a new window, go to https://www.mozilla.org/
6. Open the debugger.

Actual:
The selected events are the one of the first window.

Expected:
Selection of events in the debugger should be relative to the debugging context, not general to the application.

**Comment by janodvarko** [comment]
We've moved bug tracking into Bugzilla so, I cloned this report into
https://bugzilla.mozilla.org/show_bug.cgi?id=1660769

Honza
