### ISSUE TITLE
Consider adding a toggle for prefers-color-scheme dark

### ISSUE THREAD

**Issue by wkillerud** [firefox-devtools/debugger#8239]
Hello, and thanks for your great work on the Firefox devtools 🙌 

I've been experimenting with CSS that adapts to the preferred color scheme of the user and noticed while testing Safaris devtools that they include a useful toggle for "dark mode" that let me quickly test the opposite color scheme without changing the system settings. 

I tried looking for something similar in Nightly, but couldn't find it in the Inspector pane or in settings. I tried searching for related issues here (edit: I see now that this may be the wrong repo for this particular feature 😅) as well and didn't find anything on the topic. 

Is this a feature you would consider now that Firefox supports `prefers-color-scheme`? Perhaps a toggle could fit next to the print media simulation toggle?

![Dark mode toggle demo](https://user-images.githubusercontent.com/1223410/60703547-5bc68a80-9f02-11e9-9bf1-b73da6bd8f45.gif)

[Dark mode toggle 720p.zip](https://github.com/firefox-devtools/debugger/files/3361443/Dark.mode.toggle.zip)

**Comment by nchevobbe** [comment]
Hello William,

This repository is (was) for the debugger panel only, other panels are handled on Bugzilla.
Would you mind filing a bug in https://bugzilla.mozilla.org/enter_bug.cgi?product=DevTools&component=Inspector ? (you should be able to login with your github account)

For the feature itself, I'm pretty sure the team had a discussion about this not long ago, but I couldn't find any filed bug, so let's have one :) 

Thanks!

**Comment by wkillerud** [comment]
For sure, I noticed after submitting that this probably was the wrong repo 😅 I'll file in Bugzilla. Thanks!
