### ISSUE TITLE
README References out of date document

### ISSUE THREAD

**Issue by sneakycrow** [firefox-devtools/debugger#8248]
It looks like the README.md is referencing a document that is not the most up-to-date Google Doc referenced here: https://github.com/firefox-devtools/debugger/blob/master/README.md#L86

Screenshot since Github isn't line specific friendly for markdown: http://cl.ly/28be1e1f3182/Image%202019-07-31%20at%203.28.01%20PM.png

Currently referenced Google Doc: https://docs.google.com/document/d/146p7Y8Ues_AKjj4ReWCk6InOPWe3C3Koy6EQ1qnYKNM/edit

This is the most recent Google Doc as far as I can tell: https://docs.google.com/document/d/1lxy0IzUM14dYACk_q862vVYwpU1AA4NQVrUNAm6uc-8/edit#heading=h.onwi5ko98n17

**Comment by janodvarko** [comment]
I think that this isn't relevant anymore (the readme.md file changed in the meantime)

Honza
