### ISSUE TITLE
keyboard shortcut for finding next occurrence of search term not working on Windows, opens 'Go to line' prompt instead

### ISSUE THREAD

**Issue by Archaeopteryx** [firefox-devtools/debugger#8260]
Firefox Nightly 70.0a1 20190816215314, Firefox beta 69.0b14

The keyboard shortcut for finding the next occurrence of a search term does not work, at least on Windows. It opens the 'Go to line' prompt instead.

The source search ind next command key is defined in `sourceSearch.search.again.key3=Cmd+G` (from [bug 1488662](https://bugzilla.mozilla.org/show_bug.cgi?id=1488662)). That bug also added `gotoLineModal.key3=Ctrl+G`. Searching for the previous match with `sourceSearch.search.againPrev.key3=Cmd+Shift+G` works.

Steps to reproduce:
1. Open the debugger, e.g. with github open.
2. Open search across files by pressing Ctrl+Shift+F
3. Search for `let`.
4. Click on one of the the files from the result.
5. Click on one of the matches.
6. Press Ctrl+Shift+G (finding previous match, works).
7. Press Ctrl+G (finding next match) - doesn't work. F3 also doesn't work but opens the browser's Find In Page bar.

Expected: No confusion about Ctrl+G, shortcut to go to next match.

**Comment by janodvarko** [comment]
I can reproduce this, thanks for the report.

We've moved our bug tracking to Bugzilla so, I cloned this report here:
https://bugzilla.mozilla.org/show_bug.cgi?id=1660824

And I am closing this report.

Thanks,
Honza
