### ISSUE TITLE
Main area buttons in dark mode doesnt have background

### ISSUE THREAD

**Issue by pudymody** [firefox-devtools/debugger#8262]
Pretty much what title says, buttons in the main area of the Network, Performance and Memory panels doesnt have a background or different style to differentiate them from regular text.

![Dark screenshot of network,performance and memory panels](https://user-images.githubusercontent.com/814791/64054055-aad41900-cb5b-11e9-82f1-806639405852.jpg)

As you can see, the light variant is working fine.
![Light screenshot of network,performance and memory panels](https://user-images.githubusercontent.com/814791/64054056-aad41900-cb5b-11e9-9106-52941eada755.jpg)

This is happening with Nightly 70.0a1 (2019-08-30) (64-bit). BuildID: 20190830093857

**Comment by nchevobbe** [comment]
Hello Frederico, thanks for the bug report!

I filed https://bugzilla.mozilla.org/show_bug.cgi?id=1578681 to handle this :)
This repo is only about the debugger panel, and this impacts the whole devtools toolbox.

**Comment by pudymody** [comment]
Oh, my mistake. Thanks for filling it up. :)
