### ISSUE TITLE
Debugger seems to be "optimizing out" variables that are in use

### ISSUE THREAD

**Issue by irenesmith** [firefox-devtools/debugger#8265]
I'm debugging a small browser-based game and discovered that variables and global constants are being "optimized out" This seems to have started within the past few days. I started getting this message over the weekend but it is still happening in 70.0b5 which I just installed.

![2019-09-10](https://user-images.githubusercontent.com/192346/64637361-969ce100-d3d1-11e9-8039-fc2bdef17696.png)

**Comment by irenesmith** [comment]
It doesn't show in the first screenshot, but here is a close-up after I added the global constant to the watch list, showing that it too has been "optimized out"

![optimized_out](https://user-images.githubusercontent.com/192346/64638368-9271c300-d3d3-11e9-8e82-e04dee33f30c.png)

**Comment by YurySolovyov** [comment]
I agree.
This is really annoying.
Debugger should tell VM to skip optimizing a function when it has active breakpoint or `debugger` keyword.

**Comment by YurySolovyov** [comment]
Related: https://bugzilla.mozilla.org/show_bug.cgi?id=1186404

**Comment by janodvarko** [comment]
I am closing this report in favor of https://bugzilla.mozilla.org/show_bug.cgi?id=1186404

We've moved bug tracking into bugzilla and so, let's continue the discussion there.

Thanks,
Honza
