### ISSUE TITLE
quote differences in the source and the event flag excerpt

### ISSUE THREAD

**Issue by karlcow** [firefox-devtools/debugger#8269]
1. With Firefox Nightly 71.0a1 (2019-09-28) (64-bit)
2. With RDM mobile devices setting
2. Go to http://walmart.decipherinc.com/survey/selfserve/53a/wal18001
3. Accept the policy and continue
4. In the inspector look for the event flag on `.answers-table`
5. Click on the even flag and expand the code for `click` event on http://walmart2.surveyfiles.com/s/exp/tmp/043ce39b30db7a78f3629f20dcd72004.js <img width="776" alt="Capture d’écran 2019-09-30 à 09 28 36" src="https://user-images.githubusercontent.com/505230/65842259-31e7fd00-e365-11e9-9957-ed309b7ae4ea.png">
6. notice the quotes are double quotes
7. Follow the arrow (it doesn't bring you to the right position)
8. I had then to search the code and I searched the string `".grid-table-mode"` which didn't return any results. 
9. The string is in fact `'.grid-table-mode'`
<img width="456" alt="Capture d’écran 2019-09-30 à 09 28 50" src="https://user-images.githubusercontent.com/505230/65842909-af157100-e369-11e9-83ad-61f0c6783d1d.png">

Three possible choices:
1. Having the pointer to work to the right piece of the code
2. Make the `"` and `'` an alias when searching code. 
3. Make the code excerpts in event flags consistent with the code in the debugger.

**Comment by loganfsmyth** [comment]
We _should_ link to the right piece of code much more consistently now, so hopefully this is less of an issue, but I've also filed https://bugzilla.mozilla.org/show_bug.cgi?id=1652529 to track this in Bugzilla.
