### ISSUE TITLE
Frozen debugger after breakpoint activation on remote debugging.

### ISSUE THREAD

**Issue by karlcow** [firefox-devtools/debugger#8270]
1. With Firefox Fenix 71.0a1 (2019-09-28) on Android
2. On desktop, open about about:debugging for remote debugging.
3. Go to http://walmart.decipherinc.com/survey/selfserve/53a/wal18001 (Inspect this tab)
4. Accept the policy, continue
5. Scroll down to the state/Province dropdown
6. In the debugger, select click breakpoint on `click`
7. On the device, tap on the select

Actual:
A breakpoint is activated but nothing really happens.
On the device the contextual menu for breakpoint is not populated (play button, etc)
On the debugger the icon turns green for the debugger, but that's all, there's no in code context.
Worse we can't do anything about it, except closing the tab and restarting to the same result.

Expected:
step by step debugging. :)

**Comment by karlcow** [comment]
This is happening with multiple sites not only this one. 

This is the error message in the Browser Toolbox.

```
 Error: "Server did not specify an actor, dropping packet: {"error":"unknownError","message":"Component returned failure code: 0x80520012 (NS_ERROR_FILE_NOT_FOUND) [nsIIOService.newChannelFromURI]\nNetUtil_newChannel@resource://gre/modules/NetUtil.jsm:311:24\nthis.requireRawId@resource://devtools/shared/loader-plugin-raw.jsm:27:26\nrequireHook@resource://devtools/shared/Loader.jsm:88:16\nrequire@resource://devtools/shared/base-loader.js:384:14\nRequire/require.context/<@resource://devtools/shared/base-loader.js:503:14\ngetProperties@resource://devtools/shared/l10n.js:94:46\ngetStr@resource://devtools/shared/l10n.js:121:37\nshow@resource://devtools/server/actors/highlighters/paused-debugger.js:223:12\nshowOverlay@resource://devtools/server/actors/thread.js:459:25\n_pauseAndRespond@resource://devtools/server/actors/thread.js:829:12\n_pauseAndRespondEventBreakpoint@resource://devtools/server/actors/thread.js:763:17\n_makeEventBreakpointEnterFrame/<@resource://devtools/server/actors/thread.js:744:19\nc/<@https://www.nytimes.com/interactive/projects/well/workouts/js/main-8eb5bec40398f3a16c0b559e0045c61c397603c3.js:4:1\n"}"
    onPacket resource://devtools/shared/client/debugger-client.js:567
    _onJSONObjectReady resource://devtools/shared/transport/transport.js:464
    makeInfallible resource://devtools/shared/ThreadSafeDevToolsUtils.js:111
    makeInfallible resource://devtools/shared/ThreadSafeDevToolsUtils.js:111
ThreadSafeDevToolsUtils.js:90:13
    reportException resource://devtools/shared/ThreadSafeDevToolsUtils.js:90
    onPacket resource://devtools/shared/client/debugger-client.js:565
    _onJSONObjectReady resource://devtools/shared/transport/transport.js:464
    makeInfallible resource://devtools/shared/ThreadSafeDevToolsUtils.js:111
    makeInfallible resource://devtools/shared/ThreadSafeDevToolsUtils.js:111
```

**Comment by karlcow** [comment]
Testing on Firefox Developer Edition. 
Fenix Nightly 71 is still in a weird state.
BUT the debugger on Firefox Dev Edition is at least working. 70.0b13 (64-bit)

**Comment by karlcow** [comment]
@wisniewskit ran into that issue too on https://github.com/webcompat/web-bugs/issues/42325#issuecomment-542836991

**Comment by janodvarko** [comment]
@karlcow, thanks for the report!

When loading ` http://walmart.decipherinc.com/survey/selfserve/53a/wal18001` I see:

We appreciate your interest, but unfortunately this survey is now closed.

Do you have any other test page we could use to reproduce the bug on our machines?

**Comment by karlcow** [comment]
@janodvarko It breaks but in another way now.

* tested on macos firefox nightly 80
* Remote debugging activated
* Android 10 Firefox Nightly 80.

1. Go to http://walmart.decipherinc.com/survey/selfserve/53a/wal18003
2. Go to debugger
3. Activate Event Listener Breakpoints: "click"
4. Tap on Continue at the bottom of the page (the debugger opens)
5. click `{ }` at the bottom of the window 


The full debugger becomes white, all the context is lost.
click reload on the desktop browser top bar, reload the debugger

**Comment by janodvarko** [comment]
@karlcow thanks, the STRs is great help!

I can reproduce the issue clearly.

I cloned the bug into bugzilla:
https://bugzilla.mozilla.org/show_bug.cgi?id=1652679

We want to stop using this issue list and archive this entire repo eventually.
The source of truth is Bugzilla and m-c

Honza
