### ISSUE TITLE
yarn start no result: waiting for localhost ..  

### ISSUE THREAD

**Issue by CarpeDiemKopi** [firefox-devtools/debugger#8273]
I followed the instructions [Getting Set Up](http://firefox-dev.tools/debugger/docs/getting-setup.html) exactly and it doesn't work. 

![image](https://user-images.githubusercontent.com/32836136/67082963-83ccb780-f19a-11e9-92dd-4580ec9cc03a.png)

And the instructions are confusing. Suddenly, firefox is mentioned, which has already been started and of which there was no talk before.  

> Step 4. Start the debugger
> 
> Now that **Firefox is open**, let’s start the development server. In a new terminal tab, run these commands:
> 

windows 10 64 bit 1903

> 

```
D:\TiddlyWiki\My_TiddlyWikis\git\debugger>yarn start
yarn run v1.19.1
$ node bin/dev-server
Listening for WS on localhost:8116, all traffic is proxied to localhost:6080
Protocol messages can be logged by enabling `logging.firefoxProxy` `in /configs/local.json`
Hot Reloading - https://github.com/firefox-devtools/debugger.html/blob/master/docs/local-development.md#hot-reloading
View debugger examples here:

https://github.com/firefox-devtools/debugger-examples
Development Server Listening at http://localhost:8000
 
webpack: Compiled successfully.
 

```
And `yarn start`also messes with the internet connection.

**Comment by loganfsmyth** [comment]
Support for developing the debugger as a standalone application has been removed.
