### ISSUE TITLE
Call stack highlightling changes the links and names (through prettify)

### ISSUE THREAD

**Issue by karlcow** [firefox-devtools/debugger#8274]
This is done on Firefox Nightly 72.0a1 (2019-10-31) (64-bit)
with macOS 10.15

1. Go to https://www.ib-krautgartner.com/projekte-partner
2. set a breakpoint on one of the scripts.
    for example in https://static.parastorage.com/unpkg/@sentry/utils/src/supports.ts

When opening the call stack might open on bundle.min.js
Then if you prettify it displays the sourcemap version and the full call stack names change.
It's a bit hard to explain so I created a screencast.

https://imgur.com/a/aKOm81X

Hope it helps.

**Comment by jasonLaster** [comment]
Hi @karlcow, we switched to primarily using bugzilla this past february.

https://bugzilla.mozilla.org/show_bug.cgi?id=1593741
