### ISSUE TITLE
Clearly state that the debugger's development now happens elsewhere

### ISSUE THREAD

**Issue by julienw** [firefox-devtools/debugger#8275]
Currently there's no easy way to discover where the debugger is currently developed. The README should state that clearly so that nobody tries to use this code or even contribute from the github repository.

**Comment by digitarald** [comment]
Link would probably be https://docs.firefox-dev.tools/getting-started/

**Comment by janodvarko** [comment]
The readme is already updated and pointing to 
Bugzilla issue list
https://mzl.la/3gVEmbY
