### ISSUE TITLE
Source Maps not when using debugger with npm start

### ISSUE THREAD

**Issue by Anzumana** [firefox-devtools/debugger#8276]
I am not sure why but when i run the debugger inside firefox, the sources from webpack are being mapped correctly to the source files.
![Screen Shot 2019-11-11 at 9 17 10](https://user-images.githubusercontent.com/2629041/68571898-6078ed80-0464-11ea-8225-02e1ffd81a61.png)
But when i do the same running the debugger using npm start 
i get this
![Screen Shot 2019-11-11 at 9 17 27](https://user-images.githubusercontent.com/2629041/68571932-74245400-0464-11ea-8c40-fbab4bb55341.png)
Is there something i would have to configure additionally ?
In case you want to replicate
the project that i am using can be found https://github.com/Anzumana/thecorevisualizer.

The project was created using the react cli just fyi.

**Comment by loganfsmyth** [comment]
We've moved development of the debugger inside the Mozilla repository so the standalone `localhost` debugger is no longer supported.
