### ISSUE TITLE
backslash and escape sequence

### ISSUE THREAD

**Issue by miaomiaoji** [firefox-devtools/debugger#8289]
I found one old issuse #6577 about double backslash should represent just one when they in a string.
It's still exist 。
<https://github.com/webcompat/web-bugs/issues/52421>

**Comment by loganfsmyth** [comment]
Closing in favor of the Bugzilla bug mentioned in the webcompat issue: https://bugzilla.mozilla.org/show_bug.cgi?id=1635162
