### ISSUE TITLE
cheap-module-source-map does not show source maps.

### ISSUE THREAD

**Issue by andreicristianpetcu** [firefox-devtools/debugger#8292]
**Steps to reproduce**

Create a new project. Set it's `devtool: "cheap-module-source-map"`
https://webpack.js.org/configuration/devtool/

**Actual Behavior**
The source maps don't work

**Expected Behavior**
They should work. If I set `devtool: "eval-source-map"` it works.

**Comment by digitarald** [comment]
@andreicristianpetcu does the same `cheap-module-source-map` config work for Chrome?

**Comment by andreicristianpetcu** [comment]
Yes, @digitarald , the same source maps work in Chrome.

**Comment by digitarald** [comment]
That should be the https://bugzilla.mozilla.org/show_bug.cgi?id=1594550 . Closing this one, as we track all bugs in bugzilla now.
