### ISSUE TITLE
Variables in debugging are unreadable

### ISSUE THREAD

**Issue by sdavidg** [firefox-devtools/debugger#8293]
Create a variable like this:
var text = `
Lorem Ipsum is simply dummy text of the printing and typesetting industry.

Lorem Ipsum has been the industry's standard dummy text ever since the "1500s", when an unknown printer took a galley of type and scrambled it to make a type specimen book.

\t\t\tIt has survived not only five centuries, but also the leap "into" electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum
`;

If you use console.log(text); looks ok
![image](https://user-images.githubusercontent.com/4955944/87520577-6ffba680-c683-11ea-9973-c5061c8f8b75.png)

Using debugger, this variable is unreadable
![image](https://user-images.githubusercontent.com/4955944/87520595-7722b480-c683-11ea-841d-3e345246e811.png)

If this variable contains a buch of html code, the debugger is innusable

**Comment by janodvarko** [comment]
Thanks for the report.

The bug tracking has been moved to Bugzilla so, I cloned this bug into
https://bugzilla.mozilla.org/show_bug.cgi?id=1660766

Closing

Honza
