### ISSUE TITLE
No hover popup on variable

### ISSUE THREAD

**Issue by Kuinox** [firefox-devtools/debugger#8294]
Hello,
I got no popup while hovering variables.
![image](https://user-images.githubusercontent.com/18743295/87725938-76db0400-c7be-11ea-816a-06e8bcd19073.png)
I tried to hover every variables, but nothing show up.
I can see at the left in Scopes that the debugger know the values.

**Comment by janodvarko** [comment]
@Kuinox thanks for the report.

But, variable tooltips seem to be working for me.

Here is my STRs:
1) Load http://janodvarko.cz/tests/debugger/watchpoints/
2) Open DevTools Toolbox select the Debugger panel
3) Click the `Click Me!` button in Test Case #1, the Debugger should break on `debugger;` keyword
4) hover overl `person.age` on line 10 -> you should see the popup/tooltip.

This works for me.
Does it work for you?
Do you have a test case that I could use the see the issue on my machine?

Honza

**Comment by Kuinox** [comment]
Hello,
It work fine one most of the websites, but it does not work on a webapp I'm working on.
Your demo works fine, and it works elsewhere on my webapp too, but not on this function in particular...
I just reproduced on this getter again: 
![image](https://user-images.githubusercontent.com/18743295/91040045-e211c480-e60d-11ea-9a08-0ee148dd2348.png)
This is a vue2 in dev mode webapp, maybe it's related to getters ?

I will try to do a testcase.

**Comment by nchevobbe** [comment]
Is this using typescript or flow? Seems like the type annotations might cause issues

**Comment by janodvarko** [comment]
> I will try to do a testcase.

Thanks!

> Is this using typescript or flow? Seems like the type annotations might cause issues

Might be the reason, yes.

Honza

**Comment by Kuinox** [comment]
So, i'm trying to do a reproduction, but...
When I hit the breakpoint, the debugger disappear ? :D 
![image](https://user-images.githubusercontent.com/18743295/91067734-940fb780-e633-11ea-8a73-e46d90130681.png)

**Comment by nchevobbe** [comment]
Ouch! 
Could you open the browser console (https://developer.mozilla.org/en-US/docs/Tools/Browser_Console) and copy/paste the logs here please?

**Comment by Kuinox** [comment]
```
18:07:00.825 <unavailable> 2 ThreadSafeDevToolsUtils.js:82:13
18:07:01.485 Use of nsIFile in content process is deprecated. 13 NetUtil.jsm:253:8
18:07:01.486 ‘src’ attribute of <script> element is not a valid URI: “/build.polyfills.628299bceb6fa63d9da9.js” {025a4851-e652-44a1-83c5-4b2b4a1a0512}:1:1
18:07:01.486 ‘src’ attribute of <script> element is not a valid URI: “/build.vendors.628299bceb6fa63d9da9.js” {025a4851-e652-44a1-83c5-4b2b4a1a0512}:1:1
18:07:01.486 ‘src’ attribute of <script> element is not a valid URI: “/build.main.628299bceb6fa63d9da9.js” {025a4851-e652-44a1-83c5-4b2b4a1a0512}:1:1
18:07:01.486 NS_ERROR_FAILURE: Failed to open input source 'file:///' 2 DevToolsUtils.js:661
18:07:15.491 Cookie “io” will be soon treated as cross-site cookie against “http://localhost:5000/#/” because the scheme does not match. 2 localhost:5000
18:07:15.545 Cookie “io” will be soon treated as cross-site cookie against “http://localhost:5000/build.polyfills.628299bceb6fa63d9da9.js” because the scheme does not match. build.polyfills.628299bceb6fa63d9da9.js
18:07:15.546 Cookie “io” will be soon treated as cross-site cookie against “http://localhost:5000/vendors.css” because the scheme does not match. vendors.css
18:07:15.606 Cookie “io” will be soon treated as cross-site cookie against “http://localhost:5000/build.main.628299bceb6fa63d9da9.js” because the scheme does not match. build.main.628299bceb6fa63d9da9.js
18:07:17.051 Cookie “io” will be soon treated as cross-site cookie against “http://localhost:5000/build.vendors.628299bceb6fa63d9da9.js” because the scheme does not match. build.vendors.628299bceb6fa63d9da9.js
18:07:17.693 GEThttp://localhost:5000/favicon.ico
[HTTP/1.1 404 Not Found 2ms]

18:07:18.444 Cookie “io” will be soon treated as cross-site cookie against “http://localhost:5000/favicon.ico” because the scheme does not match. favicon.ico
18:07:18.444 [Exception... "Favicon at "http://localhost:5000/favicon.ico" failed to load: Not Found."  nsresult: "0x80004005 (NS_ERROR_FAILURE)"  location: "JS frame :: resource:///modules/FaviconLoader.jsm :: onStopRequest :: line 227"  data: no] FaviconLoader.jsm:227:22
18:07:18.445 debuggee 'http://localhost:5000/build.vendors.628299bceb6fa63d9da9.js line 2178 > eval:168726' would run event-loop.js:79:18
18:07:20.882 Error: source sourceURL-webpack-internal:///1165/originalSource-5232e3bf96c96b9ce8811861756ac7c7 does not exist
    getSourceFromId resource://devtools/client/debugger/src/reducers/sources.js:525
    mapStateToProps resource://devtools/client/debugger/src/components/SecondaryPanes/index.js:490
    Redux 10
    waitUntilService resource://devtools/client/debugger/src/actions/utils/middleware/wait-service.js:71
    promiseMiddleware resource://devtools/client/debugger/src/actions/utils/middleware/promise.js:46
    context resource://devtools/client/debugger/src/actions/utils/middleware/context.js:35
    thunk resource://devtools/client/debugger/src/actions/utils/middleware/thunk.js:29
    dispatch Redux
    mapFrames resource://devtools/client/debugger/src/actions/pause/mapFrames.js:150
react-dom.js:12769:13
    React 19
    Redux 5
    waitUntilService resource://devtools/client/debugger/src/actions/utils/middleware/wait-service.js:71
    promiseMiddleware resource://devtools/client/debugger/src/actions/utils/middleware/promise.js:46
    context resource://devtools/client/debugger/src/actions/utils/middleware/context.js:35
    thunk resource://devtools/client/debugger/src/actions/utils/middleware/thunk.js:29
    dispatch Redux
    mapFrames resource://devtools/client/debugger/src/actions/pause/mapFrames.js:150
18:07:20.889 Error: source sourceURL-webpack-internal:///1165/originalSource-5232e3bf96c96b9ce8811861756ac7c7 does not exist sources.js:525:11
18:07:20.964 Cookie “io” will be soon treated as cross-site cookie against “http://localhost:5000/116ec38166d2573aefbe.worker.js” because the scheme does not match. 8 116ec38166d2573aefbe.worker.js
18:07:58.717 uncaught exception: Object
18:09:05.946 No localization found for [undefined] 3 l10n.js:130:13
```

**Comment by Kuinox** [comment]
Using the browser console, I think I found the issue: 
![image](https://user-images.githubusercontent.com/18743295/91072391-bb698300-e639-11ea-9946-daa07a0d139a.png)
The line in question: 
![image](https://user-images.githubusercontent.com/18743295/91072461-d9cf7e80-e639-11ea-8113-8bae8095d272.png)

**Comment by nchevobbe** [comment]
Thanks for the logs!
Not sure what's happening, but yeah, something with sourcemaps going wrong (but the debugger should never go blank like that).
I tried with a simple typescript case and had no issue, using `as` or a `debugger` statement.
If you could provide us a simple test case where we could reproduce the issue, that would be great

I filed a bug on Bugzilla https://bugzilla.mozilla.org/show_bug.cgi?id=1660959 , where we track bugs now, so I'm going to close this issue here. You should be able to login into Bugzilla with your Github account so we can keep communicating about this issue :)
